<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @file
 * kb_lot.module
 */
// 50 items per page.
//define('TOTAL_ITEMS_PER_PAGE', 50);
// Admin uri links.
define('ADMIN_CONTENT_LOT_MANAGE_URI', 'admin/content/lot/manage/');
define('ADMIN_CONTENT_LOT_URI', 'admin/content/lot');

/**
 * Implements hook_entity_info().
 */
function kb_lot_entity_info() {
  $kb_lot_entity_info['kb_lot'] = array(
    'label' => t('Lot'),
    'label callback' => 'kb_lot_label_callback',
    'entity class' => 'Lot',
    'controller class' => 'LotController',
    'base table' => 'lot',
    'uri callback' => 'kb_lot_uri',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'idkl',
    ),
    'uri callback' => 'entity_class_uri',
    'load hook' => 'kb_lot_load',
    'static cache' => TRUE,
    'admin ui' => array(
      'path' => 'admin/content/lot',
      'controller class' => 'LotUIController',
      'file' => 'kb_lot.admin.inc',
    ),
    'module' => 'kb_lot',
    'access callback' => 'kb_lot_access_callback',
    'bundles' => array(
      'kb_lot' => array(
        'label' => 'Lot',
        'admin' => array(
          'path' => 'admin/structure/lot/manage/fields',
        //'access arguments' => array('administer lot'),
        ),
      ),
    ),
    'views controller class' => 'EntityDefaultViewsController',
  );

  return $kb_lot_entity_info;
}

/**
 * Implements hook_menu().
 */
function kb_lot_menu() {
  $items = array();

  $items['lot/%lot'] = array(
    'title' => 'Lot',
    'page callback' => 'kb_lot_view_entity',
    'page arguments' => array(1),
    'access callback' => 'kb_lot_access_menu_callback',
    'access arguments' => array('view', 1),
  );

  $items['lot/locate'] = array(
    'page callback' => 'kb_lot_locate_callback',
    'access arguments' => array('access content'),
  );

  $items['admin/content/l/bulk/delete/%'] = array(
    'title' => 'Bulk Delete Lot',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kb_lot_bulk_delete', 5),
    'access arguments' => array('administer lot entities'),
    'file' => 'kb_lot.admin.inc',
  );

  $items['admin/structure/lot'] = array(
    'title' => 'Lot Fields',
    'access arguments' => array('administer lot entities'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['import-lot'] = array(
    'title' => 'Import',
    'page callback' => 'action_import_lot',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );

  $items['import-lot-batch'] = array(
    'title' => 'Import',
    'page callback' => 'action_import_lot_batch',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );

  return $items;
}

function action_import_lot_batch() {
  $import_lot_batch = new import_lot_batch();
  return $import_lot_batch->start();
}

function action_import_lot() {
}

/**
 * Implements hook_permission().
 */
function kb_lot_permission() {
  return array(
    'administer lot entities' => array(
      'title' => t('Administer Lot Entities'),
      'description' => t('Allows a user to administer lawmaker entities'),
    ),
    'view lot entities' => array(
      'title' => t('View Lot Entity'),
      'description' => t('Allows a user to view the lot entities.'),
    ),
    'create lot entities' => array(
      'title' => t('Create Lot Entities'),
      'description' => t('Allows a user to create lot entities.'),
    ),
    'edit lot entities' => array(
      'title' => t('Edit Lot Entities'),
      'description' => t('Allows a user to edit lot entities.'),
    ),
    'delete lot entities' => array(
      'title' => t('Delete Lot Entities'),
      'description' => t('Allows a user to delete lot entities.'),
    ),
    'use lot bulk operations' => array(
      'title' => t('Do bulk operations on Lot entities'),
      'description' => t('Allows a user to do bulk operations.'),
    ),
  );
}

/**
 * Check access permission for Lot Entity UI.
 */
function kb_lot_access_menu_callback($op, $kb_lot = NULL, $account = NULL) {
  switch ($op) {
    case 'view':
      return user_access('view lot entities', $account);

    case 'create':
      return user_access('create lot entities', $account);

    case 'update':
      return user_access('edit lot entities', $account);

    case 'delete':
      return user_access('delete lot entities', $account);
  }

  return FALSE;
}

/**
 * Lot access callback.
 */
function kb_lot_access_callback() {
  if (user_is_anonymous() && !user_access('administer lot entities')) {
    return FALSE;
  } else {
    return TRUE;
  }
}

/**
 * Implements hook_theme().
 */
function kb_lot_theme() {
  return array(
    'kb_lot_full' => array(
      'variables' => array('kb_lot' => NULL),
      'file' => 'kb_lot.theme.inc',
    ),
  );
}

/**
 * Helper function for custom queries.
 */
function kb_lot_entity_query($conditions = array()) {

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'kb_lot');

  // Apply conditions.
  foreach ($conditions as $key => $value) {
    $query->propertyCondition($key, $value);
  }

  $result = $query->execute();

  if (isset($result['kb_lot'])) {
    $kb_lot = array_keys($result['kb_lot']);
  } else {
    $kb_lot = array();
  }

  return $kb_lot;
}

/**
 * Saves Lot to database.
 */
function kb_lot_save(kb_lot $kb_lot) {
  return $kb_lot->save();
}

/**
 * View for /kb_lot/<idkp> page.
 */
function kb_lot_view_entity($kb_lot) {
  // Path not entity.
  $kb_lot_output = theme('kb_lot_full', array('kb_lot' => $kb_lot));
  return $kb_lot_output;
}

/**
 * Lot custom entity class.
 */
class Lot extends Entity {

  /**
   * Override defaultUri().
   */
  protected
    function defaultUri() {
    return array('path' => 'lot/' . $this->identifier());
  }

}

/**
 * Menu autoloader for /kb_lot.
 */
function kb_lot_load($idkp, $reset = FALSE) {
  $kb_lot = kb_lot_load_multiple(array($idkp), array(), $reset);
  return reset($kb_lot);
}

/**
 * Load multiple kb_lot based on certain conditions.
 */
function kb_lot_load_multiple($idkp = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('kb_lot', $idkp, $conditions, $reset);
}

/**
 * Deletes a lawmaker.
 */
function kb_lot_delete(kb_lot $kb_lot) {
  $kb_lot->delete();
}

/**
 * Delete multiple kb_lot.
 */
function kb_lot_delete_multiple(array $idkp) {
  entity_get_controller('kb_lot')->delete($idkp);
}

/**
 * Custom controller for the kb_lot entity.
 */
class LotController extends EntityAPIController {
  /**
   * Override the save method.
   */
//  public function save($entity, DatabaseTransaction $transaction = NULL) {
//    if (isset($entity->is_new)) {
//      $entity->created = REQUEST_TIME;
//    }
//
//    $entity->changed = REQUEST_TIME;
//    return parent::save($entity, $transaction);
//  }
}

/**
 * Custom controller for the administrator UI.
 */
class LotUIController extends EntityDefaultUIController {

  /**
   * Override the menu hook for default ui controller.
   */
  public
    function hook_menu() {
    $items = parent::hook_menu();
    $items[$this->path]['title'] = t('Lot');
    $items[$this->path]['description'] = t('Manage lot, including fields.');
    $items[$this->path]['access callback'] = 'kb_lot_access_callback';
    $items[$this->path]['access arguments'] = array('administer lot entities');
    $items[$this->path]['type'] = MENU_LOCAL_TASK;
    return $items;
  }

  /**
   * Admin form for searching and doing bulk operations.
   */
  public
    function overviewForm($form, &$form_state) {
    $form['pager'] = array('#theme' => 'pager');

    $header = array(
      'idkp' => array('data' => t('ID'), 'field' => 'idkp'),
      'name' => array('data' => t('Name'), 'field' => 'name'),
      'operations' => array('data' => t('Operations'), 'field' => 'operations'),
    );

    $options = array();
    $search_term = !empty($_GET['search']) ? $_GET['search'] : NULL;

    $query = new EntityFieldQuery();
    $query
      ->entityCondition('entity_type', 'kb_lot');

    if (!empty($search_term)) {
      $query->propertyCondition('name', '%' . $search_term . '%', 'like');
    }
    // Check for sort order and sort key.
    if (!empty($_GET['sort']) && !empty($_GET['order'])) {
      $sort = strtoupper($_GET['sort']);
      $order = strtolower($_GET['order']);
      $order = str_replace(' ', '_', $order);
      if ($order != 'operations') {
        $query->propertyOrderBy($order, $sort);
      }
    }

    $query->pager(TOTAL_ITEMS_PER_PAGE);

    $result = $query->execute();
    $kb_lot_results = !empty($result['kb_lot']) ? $result['kb_lot'] : array();
    $kb_lot_array = !empty($kb_lot_results) ? kb_lot_load_multiple(array_keys($kb_lot_results)) : array();
    foreach ($kb_lot_array as $idkp => $kb_lot) {
      $options['idkp-' . $idkp] = array(
        'idkp' => l($kb_lot->idkp, 'lot/' . $kb_lot->idkp),
        'name' => l($kb_lot->name, 'lot/' . $kb_lot->idkp),
        'operations' =>
        l(t('View'), 'lot/' . $kb_lot->idkp) . ' ' .
        l(t('Edit'), ADMIN_CONTENT_LOT_MANAGE_URI . $idkp, array('query' => array('destination' => ADMIN_CONTENT_LOT_URI))) . ' ' .
        l(t('Delete'), ADMIN_CONTENT_LOT_MANAGE_URI . $idkp . '/delete', array('attributes' => array('class' => array('lot-delete-' . $kb_lot->idkp),), 'query' => array('destination' => ADMIN_CONTENT_LOT_URI))),
      );
    }

    $form['search'] = array(
      '#type' => 'fieldset',
      '#title' => t('Basic Search'),
      '#collapsible' => TRUE,
      '#collapsed' => !empty($search_term) ? FALSE : TRUE,
    );

    $form['search']['search_text'] = array(
      '#type' => 'textfield',
      '#title' => t('Search Term'),
      '#default_value' => !empty($search_term) ? $search_term : '',
    );

    $form['search']['search_submit'] = array(
      '#type' => 'submit',
      '#value' => t('Search'),
    );

    $form['bulk_operations'] = array(
      '#type' => 'fieldset',
      '#title' => t('Bulk Operations'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );

    $form['bulk_operations']['operations'] = array(
      '#type' => 'select',
      '#options' => array(
        0 => t('Select a bulk operation'),
        'delete' => t('Delete selected lot'),
      ),
    );

    $form['bulk_operations']['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Submit'),
    );

    $form['entities'] = array(
      '#type' => 'tableselect',
      '#header' => $header,
      '#options' => $options,
      '#attributes' => array('class' => array('entity-sort-table')),
      '#empty' => t('There are no lot.'),
    );

    return $form;
  }

  /**
   * Form Submit method.
   */
  public
    function overviewFormSubmit($form, &$form_state) {
    $values = $form_state['input'];
    $idkp = array();

    if (!empty($values['entities'])) {
      foreach ($values['entities'] as $index => $value) {
        if (!empty($value)) {
          $idkp[] = str_replace('idkp-', '', $value);
        }
      }

      switch ($values['operations']) {
        case 'delete':
          drupal_goto('admin/content/lot/bulk/delete/' . implode('|', $idkp));
          break;
      }
    }

    if (!empty($values['search_text'])) {
      drupal_goto('admin/content/lot', array('query' => array('search' => $values['search_text'])));
    }
  }

}
