<?php
/**
 * @file
 * Code for the K&B View Finance Archives feature.
 */

include_once 'kandb_view_finance_archives.features.inc';

/**
 * Define Selection URLs
 */
define('URL_FINANCE_ARCHIVES', 'archives');

/**
 * Implements hook_menu().
 */
function kandb_view_finance_archives_menu() {
    $menu = array();
    $menu[URL_FINANCE_ARCHIVES] = array(
        'title' => 'Archives',
        'page callback' => 'kandb_view_finance_archives_page',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
    );
    return $menu;
}

function kandb_view_finance_archives_page() {
    $content = array();
    $content['archives_documents'] = call_user_func_array(
        'views_embed_view',
        array_merge(
            array('archives', 'block')
        )
    );

    return theme('page_finance_archives', $content);
}

/**
 * Implements hook_theme().
 */
function kandb_view_finance_archives_theme($existing, $type, $theme, $path) {
    return array(
        'page_finance_archives' => array(
            'template' => 'templates/page_finance_archives',
            'variables' => array(),
        )
    );
}
