<?php
/**
 * @file
 * Code for the KandB Partenaire feature.
 */

include_once 'kandb_partenaire.features.inc';
include_once 'kandb_partenaire.archive_file.inc';
include_once 'kandb_partenaire.programme_txt.inc';

function kandb_partenaire_form_alter(&$form, &$form_state, $form_id) {
    if (arg(0) == 'node' && ((arg(1) == 'add' && arg(2) == 'partenaire') || arg(2) == 'edit')) {
        $partenaireJSPath = drupal_get_path('profile', 'kandb') . '/modules/features/kandb_partenaire/js/kandb_partenaire.js';
        drupal_add_js($partenaireJSPath);
        if (arg(1) == 'add' && arg(2) == 'partenaire') {
          $form['field_id_partenaire'][LANGUAGE_NONE][0]['value']['#default_value'] = generate_uuid();
        }
    }
}
