<?php

/**
 * Implements hook_menu().
 */
function kb_mail_menu() {
  $items = array();
  
  $items['admin/config/kb-mail'] = array(
    'title' => 'Kandb mail',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('config_mailing_list'),
    'file' => 'kb_mail.admin.inc',
    'access callback' => TRUE,
  );
  $items['admin/config/kb-mail/mailing-list'] = array(
    'title' => 'Configure list email for Call center',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  return $items;
}
/**
 * Implements hook_theme().
 */
function kb_mail_theme($existing, $type, $theme, $path) {
  return array(
    'etre_rappele_callback_request' => array(
      'template' => 'templates/etre-rappele-callback-request',
      'variables' => array(
        'mail_vars' => NULL
        ),
    ),
    'rendez_vous_book_appointment' => array(
      'template' => 'templates/rendez-vous-book-appointment',
      'variables' => array(
        'mail_vars' => NULL
      ),
    ),
    'user_confirmation_book_appointment' => array(
      'template' => 'templates/user-confirmation',
      'variables' => array(
        'mail_vars' => NULL
      ),
    ),
  );
}
/**
 * Implements hook_form_alter().
 */
function kb_mail_form_alter(&$form, &$form_state, $form_id) {
  $all_webform = array(
    '_tre_rappel_',
    'prendre_rendez_vous'
  );
  $all_forms = array();
  foreach ($all_webform as $webform_name) {
    $webform = webform_features_machine_name_load($webform_name);
    if ($webform) {
      $all_forms[] = 'webform_client_form_' . $webform->nid;
    }
  }
  if(in_array($form_id, $all_forms)) {
    array_unshift($form['#submit'], 'kandb_webform_submit'); 
  }
}
function kandb_webform_submit(&$form, &$form_state) {
  $node = NULL;
  $bien = NULL;
  $values = $form_state['values'];
  if (isset($values['submitted']['row_2']['rappeler_horaire'])) {
    if (isset ($form['submitted']['row_2']['rappeler_horaire']['#options'][$values['submitted']['row_2']['rappeler_horaire']])) {
      $values['submitted']['row_2']['rappeler_horaire'] = $form['submitted']['row_2']['rappeler_horaire']['#options'][$values['submitted']['row_2']['rappeler_horaire']];
    }
  }
  if (isset($values['submitted']['rdv_idkp']) && is_numeric($values['submitted']['rdv_idkp'])) {
    $db_query = db_select('field_data_field_id_programme', 'fidk');
    $db_query->fields('fidk', array('entity_id'));
    $db_query->condition('fidk.entity_type', 'node');
    $db_query->condition('fidk.bundle', 'programme');
    $db_query->condition('fidk.field_id_programme_value', $values['submitted']['rdv_idkp']);
    $nid = $db_query->execute()->fetchField();
    $node = node_load($nid);
  }
  if (isset($values['submitted']['rdv_idkl'])) {
    $db_query = db_select('field_data_field_id_bien', 'fidkl');
    $db_query->fields('fidkl', array('entity_id'));
    $db_query->condition('fidkl.entity_type', 'node');
    $db_query->condition('fidkl.bundle', 'bien');
    $db_query->condition('fidkl.field_id_bien_value', $values['submitted']['rdv_idkl']);
    $nid = $db_query->execute()->fetchField();
    $bien = node_load($nid);
  }
  $webform_name = isset($form['#node']->webform['machine_name']) ? $form['#node']->webform['machine_name'] : ''; 
  if ($webform_name == '_tre_rappel_' || $webform_name == 'prendre_rendez_vous') {
    $variables = kandb_webform_build_variable_mail($webform_name, $values, $node, $bien);
    $has_prefix = FALSE;
    if ($webform_name == '_tre_rappel_') {
//      $subject = t('Se Faire rappeler @programme_title / @programme_loc_ville / @programme_loc_department / @programme_idkp', array('@programme_title' => $variables['programme_title'], '@programme_loc_ville' => $variables['programme_loc_ville'], '@programme_loc_department' => $variables['programme_loc_department'], '@programme_idkp' => $variables['programme_idkp']));
      $subject = t('Se Faire rappeler ');
      $sub_vars = array('programme_title', 'programme_loc_ville', 'programme_loc_department', 'programme_idkp');
      foreach ($sub_vars as $var) {
        if ($variables[$var]) {
          if ($has_prefix) {
            $subject .= ' / ';
          }
          $subject .= $variables[$var];
          $has_prefix = TRUE;
        }
      }
      kandb_webform_send_mail('etre_rappele_callback_request', $subject, 'call_center', $variables);
    }
    else {
      $has_prefix = FALSE;
      $subject = t('Prise de RDV');
      $sub_vars = array('programme_title', 'programme_loc_ville', 'programme_loc_department');
      foreach ($sub_vars as $var) {
        if ($variables[$var]) {
          if ($has_prefix) {
            $subject .= ' / ';
          }
          else {
            $subject .= ' - ';
          }
          $subject .= $variables[$var];
          $has_prefix = TRUE;
        }
      }
      //Send to user
      kandb_webform_send_mail('user_confirmation_book_appointment', $subject, $variables['rdv_email'], $variables);
      //Send to call center
      if ($variables['programme_idkp']) {
          if ($has_prefix) {
            $subject .= ' / ';
          }
          else {
            $subject .= ' - ';
          }
          $subject .= $variables['programme_idkp'];
      }
      kandb_webform_send_mail('rendez_vous_book_appointment', $subject, 'call_center', $variables);
    }
  }
}
function kb_mail_mail($key, &$message, $params) {
  if($key == 'kb_webform_submit') {
    $message['subject'] .= $params['subject'];
    $message['body'][] = $params['body'];
  }
}
function kandb_webform_build_variable_mail($webform_name = '', $values = array(), $programme = NULL, $bien = NULL) {
  $variables = array();
  if($webform_name && $values) {
    $variables['programme_title'] = isset($programme->title) ? $programme->title : '';
    $variables['programme_loc_ville'] = '';
    $variables['programme_loc_department'] = '';
    $variables['programme_idkp'] = isset($programme->field_id_programme[LANGUAGE_NONE][0]['value']) ? $programme->field_id_programme[LANGUAGE_NONE][0]['value'] : '';
    $variables['programme_loc_type'] = isset($programme->field_programme_loc_type[LANGUAGE_NONE][0]['value']) ? $programme->field_programme_loc_type[LANGUAGE_NONE][0]['value'] : '';
    $variables['programme_loc_rue'] = isset($programme->field_programme_loc_rue[LANGUAGE_NONE][0]['value']) ? $programme->field_programme_loc_rue[LANGUAGE_NONE][0]['value'] : '';
    $variables['programme_nom_conseiller'] = isset($programme->field_nom_conseiller[LANGUAGE_NONE][0]['value']) ? $programme->field_nom_conseiller[LANGUAGE_NONE][0]['value'] : '';
    $variables['programme_espace_vente_tel'] = isset($programme->field_espace_vente_tel[LANGUAGE_NONE][0]['value']) ? $programme->field_espace_vente_tel[LANGUAGE_NONE][0]['value'] : '';
    $variables['programme_espace_vente_adresse'] = isset($programme->field_espace_vente_adresse[LANGUAGE_NONE][0]['value']) ? $programme->field_espace_vente_adresse[LANGUAGE_NONE][0]['value'] : '';
    $variables['programme_espace_vente_ville'] = isset($programme->field_espace_vente_ville[LANGUAGE_NONE][0]['value']) ? $programme->field_espace_vente_ville[LANGUAGE_NONE][0]['value'] : '';
    $variables['programme_espace_vente_horaire'] = isset($programme->field_espace_vente_horaire[LANGUAGE_NONE][0]['value']) ? $programme->field_espace_vente_horaire[LANGUAGE_NONE][0]['value'] : '';
    if (isset($programme->field_programme_loc_ville[LANGUAGE_NONE][0]['tid'])) {
      $ville = taxonomy_term_load($programme->field_programme_loc_ville[LANGUAGE_NONE][0]['tid']);
      if (isset($ville->name)) {
        $variables['programme_loc_ville'] = $ville->name;
      }
    }
    if (isset($programme->field_programme_loc_department[LANGUAGE_NONE][0]['tid'])) {
      $department = taxonomy_term_load($programme->field_programme_loc_department[LANGUAGE_NONE][0]['tid']);
      $variables['programme_loc_department'] = isset($department->field_numero_departement[LANGUAGE_NONE][0]['value']) ? $department->field_numero_departement[LANGUAGE_NONE][0]['value'] : '';
    }
    $variables['bien_type'] = '';
    $variables['bien_nb_pieces'] = '';
    $variables['bien_lot_id'] = '';
    $variables['bien_superficie'] = isset($bien->field_superficie[LANGUAGE_NONE][0]['value']) ? $bien->field_superficie[LANGUAGE_NONE][0]['value'] . ' m2' : '';
    if (isset($bien->field_type[LANGUAGE_NONE][0]['tid'])) {
      $bien_type = taxonomy_term_load($bien->field_type[LANGUAGE_NONE][0]['tid']);
      if (isset($bien_type->name)) {
        $variables['bien_type'] = $bien_type->name;
      }
    }
    if (isset($bien->field_nb_pieces[LANGUAGE_NONE][0]['tid'])) {
      $nb_pieces = taxonomy_term_load($bien->field_nb_pieces[LANGUAGE_NONE][0]['tid']);
      if (isset($nb_pieces->name)) {
        $variables['bien_nb_pieces'] = $nb_pieces->name;
      }
    }
    if (isset($bien->field_id_bien[LANGUAGE_NONE][0]['value'])) {
      if (isset($bien_type->name)) {
        $variables['bien_type'] = $bien_type->name;
      }
      if (strpos($bien->field_id_bien[LANGUAGE_NONE][0]['value'], '-') !== FALSE) {
        $variables['bien_lot_id'] = trim(substr($bien->field_id_bien[LANGUAGE_NONE][0]['value'], strpos($bien->field_id_bien[LANGUAGE_NONE][0]['value'], '-') + 1));
      }
      else {
        $variables['bien_lot_id'] = $bien->field_id_bien[LANGUAGE_NONE][0]['value'];
      }
    }
    if ($webform_name == '_tre_rappel_') {
      $variables['rappeler_nom'] = isset($values['submitted']['row_1']['rappeler_nom']) ? $values['submitted']['row_1']['rappeler_nom'] : '';
      $variables['rappeler_prenom'] = isset($values['submitted']['row_1']['rappeler_prenom']) ? $values['submitted']['row_1']['rappeler_prenom'] : '';
      $variables['rappeler_telephone'] = isset($values['submitted']['row_2']['rappeler_telephone']) ? $values['submitted']['row_2']['rappeler_telephone'] : '';
      $variables['rappeler_horaire'] = isset($values['submitted']['row_2']['rappeler_horaire']) ? $values['submitted']['row_2']['rappeler_horaire'] : '';
    }
    elseif ($webform_name == 'prendre_rendez_vous') {
      $book_appointment_arr = array(
        'rdv_nom',
        'rdv_prenom',
        'rdv_adresse1',
        'rdv_adresse2',
        'rdv_ville',
        'rdv_lieudit',
        'rdv_code_postal',
        'rdv_email',
        'rdv_telephone',
        'rdv_message',
        'rdv_nom',
      );
      foreach ($book_appointment_arr as $var_name) {
        $variables[$var_name] = isset($values['submitted'][$var_name]) ? $values['submitted'][$var_name] : '';
      }
      $variables['rdv_newsletter'] = isset($values['submitted']['rdv_newsletter'][1]) ? (bool) $values['submitted']['rdv_newsletter'][1] : FALSE;
    }
  }
  return $variables;
}
function kandb_webform_send_mail ($template = '', $subject = '', $send_to = 'call_center', $variables = array()) {
  if ($template == '' || $subject == '') {
    return ;
  }
  $content = theme($template, array('mail_vars' => $variables));
  if ($send_to == 'call_center') {
    $mailing_list = str_replace("\r\n", ',', variable_get('kb_call_center_mailing_list', ''));
  }
  else {
    $mailing_list = $send_to;
  }
  if ($mailing_list && $subject && $content) {
    $sender_name = variable_get('kb_call_center_sender_name', '');
    $sender_mail = variable_get('kb_call_center_sender_mail', '');
    $from = $sender_mail ? $sender_name . '<' . $sender_mail . '>' : NULL;
    drupal_mail('kb_mail', 'kb_webform_submit', $mailing_list, 'fr', $params = array('subject' => $subject, 'body' => $content), $from);
  }
  else {
    watchdog('kandb_mail', "Can not send mail to: @receiver", array("@receiver" => $mailing_list), WATCHDOG_ERROR);
  }
}