<?php

/**
 * Implements hook_menu().
 */
function kb_mail_menu() {
  $items = array();

  $items['admin/config/kb-mail'] = array(
    'title' => 'Kandb mail',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('config_mailing_list'),
    'file' => 'kb_mail.admin.inc',
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/config/kb-mail/mailing-list'] = array(
    'title' => 'Configure list email for Call center',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
   $items['admin/config/kb-mail/partage_email_progamme'] = array(
    'title' => 'Partage par email',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('partage_email'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'kb_mail.admin.inc',
  );
  return $items;
}
/**
 * Implements hook_theme().
 */
function kb_mail_theme($existing, $type, $theme, $path) {
  return array(
    'etre_rappele_callback_request' => array(
      'template' => 'templates/etre-rappele-callback-request',
      'variables' => array(
        'mail_vars' => NULL
        ),
    ),
    'rendez_vous_book_appointment' => array(
      'template' => 'templates/rendez-vous-book-appointment',
      'variables' => array(
        'mail_vars' => NULL
      ),
    ),
    'user_confirmation_book_appointment' => array(
      'template' => 'templates/user-confirmation',
      'variables' => array(
        'mail_vars' => NULL
      ),
    ),
    'avant_premiere_contact_us' => array(
      'template' => 'templates/avant-premiere-contact-us',
      'variables' => array(
        'mail_vars' => NULL
      ),
    ),
    'user_confirmation_avant_premiere_contact_us' => array(
      'template' => 'templates/user-confirmation-avant-premiere-contact-us',
      'variables' => array(
        'mail_vars' => NULL
      ),
    ),
  );
}
/**
 * Implements hook_form_alter().
 */
function kb_mail_form_alter(&$form, &$form_state, $form_id) {
  $all_webform = array(
    '_tre_rappel_',
    'prendre_rendez_vous',
    'avant_contactez_nous'
  );
  $all_forms = array();
  foreach ($all_webform as $webform_name) {
    $webform = webform_features_machine_name_load($webform_name);
    if ($webform) {
      $all_forms[] = 'webform_client_form_' . $webform->nid;
    }
  }
  if (arg(0) == 'node' && is_numeric(arg(1)) && arg(2) == NULL) {
    $form['#avant_premiere_id'] = arg(1);
  }
  if(in_array($form_id, $all_forms)) {
    array_unshift($form['#submit'], 'kandb_webform_submit');
  }
}
function kandb_webform_submit(&$form, &$form_state) {
  $node = NULL;
  $bien = NULL;
  $avant_premiere = NULL;
  $values = $form_state['values'];
  $webform_name = isset($form['#node']->webform['machine_name']) ? $form['#node']->webform['machine_name'] : '';
  if (isset($values['submitted']['row_2']['rappeler_horaire'])) {
    if (isset ($form['submitted']['row_2']['rappeler_horaire']['#options'][$values['submitted']['row_2']['rappeler_horaire']])) {
      $values['submitted']['row_2']['rappeler_horaire'] = $form['submitted']['row_2']['rappeler_horaire']['#options'][$values['submitted']['row_2']['rappeler_horaire']];
    }
  }
  if (isset($values['submitted']['rdv_connu'])) {
    if (isset ($form['submitted']['rdv_connu']['#options'][$values['submitted']['rdv_connu']])) {
      if ($form['submitted']['rdv_connu']['#options'][$values['submitted']['rdv_connu']] != '') {
        $values['submitted']['rdv_connu'] = $form['submitted']['rdv_connu']['#options'][$values['submitted']['rdv_connu']];
      }
      else {
        $values['submitted']['rdv_connu'] = '';
      }
    }
  }
  if (isset($values['submitted']['ap_connu'])) {
    if (isset ($form['submitted']['ap_connu']['#options'][$values['submitted']['ap_connu']])) {
      if ($form['submitted']['ap_connu']['#options'][$values['submitted']['ap_connu']] != '') {
        $values['submitted']['ap_connu'] = $form['submitted']['ap_connu']['#options'][$values['submitted']['ap_connu']];
      }
      else {
        $values['submitted']['ap_connu'] = '';
      }
    }
  }
  if (isset($form['#avant_premiere_id']) && is_numeric($form['#avant_premiere_id']) && $webform_name == 'avant_contactez_nous') {
    $avant_premiere = node_load($form['#avant_premiere_id']);
    if ($avant_premiere->type != 'avant_premiere') {
      $avant_premiere = NULL;
    }
  }
  if (isset($values['submitted']['rdv_idkp']) && is_numeric($values['submitted']['rdv_idkp'])) {
    $db_query = db_select('field_data_field_id_programme', 'fidk');
    $db_query->fields('fidk', array('entity_id'));
    $db_query->condition('fidk.entity_type', 'node');
    $db_query->condition('fidk.bundle', 'programme');
    $db_query->condition('fidk.field_id_programme_value', $values['submitted']['rdv_idkp']);
    $nid = $db_query->execute()->fetchField();
    if($nid) $node = node_load($nid);
  }
  if (isset($values['submitted']['rdv_idkl'])) {
    $db_query = db_select('field_data_field_id_bien', 'fidkl');
    $db_query->fields('fidkl', array('entity_id'));
    $db_query->condition('fidkl.entity_type', 'node');
    $db_query->condition('fidkl.bundle', 'bien');
    $db_query->condition('fidkl.field_id_bien_value', $values['submitted']['rdv_idkl']);
    $nid = $db_query->execute()->fetchField();
    if($nid) $bien = node_load($nid);
  }
  if ($webform_name == '_tre_rappel_' || $webform_name == 'prendre_rendez_vous' || $webform_name == 'avant_contactez_nous') {
    $variables = kandb_webform_build_variable_mail($webform_name, $values, $node, $bien, $avant_premiere);
    $has_prefix = FALSE;
    if ($webform_name == '_tre_rappel_') {
//      $subject = t('Se Faire rappeler @programme_title / @programme_loc_ville / @programme_loc_department / @programme_idkp', array('@programme_title' => $variables['programme_title'], '@programme_loc_ville' => $variables['programme_loc_ville'], '@programme_loc_department' => $variables['programme_loc_department'], '@programme_idkp' => $variables['programme_idkp']));
      $subject = t('Se Faire rappeler ');
      $sub_vars = array('programme_title', 'programme_loc_ville', 'programme_loc_department', 'programme_idkp');
      foreach ($sub_vars as $var) {
        if ($variables[$var]) {
          if ($has_prefix) {
            $subject .= ' / ';
          }
          $subject .= $variables[$var];
          $has_prefix = TRUE;
        }
      }
      kandb_webform_send_mail('etre_rappele_callback_request', $subject, 'call_center', $variables);
    }
    elseif ($webform_name == 'prendre_rendez_vous') {
      $has_prefix = FALSE;
      $subject = t('Prise de RDV');
      $sub_vars = array('programme_title', 'programme_loc_ville', 'programme_loc_department');
      foreach ($sub_vars as $var) {
        if ($variables[$var]) {
          if ($has_prefix) {
            $subject .= ' / ';
          }
          else {
            $subject .= ' - ';
          }
          $subject .= $variables[$var];
          $has_prefix = TRUE;
        }
      }
      //Send to user
      kandb_webform_send_mail('user_confirmation_book_appointment', $subject, $variables['rdv_email'], $variables);
      //Send to call center
      if ($variables['programme_idkp']) {
          if ($has_prefix) {
            $subject .= ' / ';
          }
          else {
            $subject .= ' - ';
          }
          $subject .= $variables['programme_idkp'];
      }
      kandb_webform_send_mail('rendez_vous_book_appointment', $subject, 'call_center', $variables);
    }
    else {
      $has_prefix = FALSE;
      $subject = t('Avant Première');
      $sub_vars = array('avant_premiere_title', 'avant_premiere_ville', 'avant_premiere_department');
      foreach ($sub_vars as $var) {
        if ($variables[$var]) {
          if ($has_prefix) {
            $subject .= ' / ';
          }
          else {
            $subject .= ' - ';
          }
          $subject .= $variables[$var];
          $has_prefix = TRUE;
        }
      }
      //Send mail to user
      kandb_webform_send_mail('user_confirmation_avant_premiere_contact_us', $subject, $variables['rdv_email'], $variables);
      //Send mail to call center
      kandb_webform_send_mail('avant_premiere_contact_us', $subject, 'call_center', $variables);
    }
  }
}
function kb_mail_mail($key, &$message, $params) {
  if($key == 'kb_webform_submit') {
    $message['subject'] .= $params['subject'];
    $message['body'][] = $params['body'];
    $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';

    $reply_name = variable_get('kb_call_center_reply_name', '');
    $reply_mail = variable_get('kb_call_center_reply_mail', '');
    $reply = $reply_mail ? $reply_name . '<' . $reply_mail . '>' : NULL;
    if($reply) {
      $message['headers']['Reply-To'] = $reply;
    }
  }
}
function kandb_webform_build_variable_mail($webform_name = '', $values = array(), $programme = NULL, $bien = NULL, $avant_premiere = NULL) {
  global $base_url;
  $variables = array();
  $variables['kandb_base_url'] = $base_url;
  if($webform_name && $values) {
    $variables['programme_title'] = isset($programme->title) ? $programme->title : '';
    $variables['programme_loc_ville'] = '';
    $variables['programme_loc_department'] = '';
    $variables['programme_idkp'] = isset($programme->field_id_programme[LANGUAGE_NONE][0]['value']) ? $programme->field_id_programme[LANGUAGE_NONE][0]['value'] : '';
    $variables['programme_loc_type'] = isset($programme->field_programme_loc_type[LANGUAGE_NONE][0]['value']) ? $programme->field_programme_loc_type[LANGUAGE_NONE][0]['value'] : '';
    $variables['programme_loc_rue'] = isset($programme->field_programme_loc_rue[LANGUAGE_NONE][0]['value']) ? $programme->field_programme_loc_rue[LANGUAGE_NONE][0]['value'] : '';
    $variables['programme_nom_conseiller'] = isset($programme->field_nom_conseiller[LANGUAGE_NONE][0]['value']) ? $programme->field_nom_conseiller[LANGUAGE_NONE][0]['value'] : '';
    $variables['programme_espace_vente_tel'] = isset($programme->field_espace_vente_tel[LANGUAGE_NONE][0]['value']) ? $programme->field_espace_vente_tel[LANGUAGE_NONE][0]['value'] : '';
    $variables['programme_espace_vente_adresse'] = isset($programme->field_espace_vente_adresse[LANGUAGE_NONE][0]['value']) ? $programme->field_espace_vente_adresse[LANGUAGE_NONE][0]['value'] : '';
    $variables['programme_espace_vente_ville'] = isset($programme->field_espace_vente_ville[LANGUAGE_NONE][0]['value']) ? $programme->field_espace_vente_ville[LANGUAGE_NONE][0]['value'] : '';
    $variables['programme_espace_vente_horaire'] = isset($programme->field_espace_vente_horaire[LANGUAGE_NONE][0]['value']) ? $programme->field_espace_vente_horaire[LANGUAGE_NONE][0]['value'] : '';
    if (isset($programme->field_programme_loc_ville[LANGUAGE_NONE][0]['tid'])) {
      $ville = taxonomy_term_load($programme->field_programme_loc_ville[LANGUAGE_NONE][0]['tid']);
      if (isset($ville->name)) {
        $variables['programme_loc_ville'] = $ville->name;
      }
    }
    if (isset($programme->field_programme_loc_department[LANGUAGE_NONE][0]['tid'])) {
      $department = taxonomy_term_load($programme->field_programme_loc_department[LANGUAGE_NONE][0]['tid']);
      $variables['programme_loc_department'] = isset($department->field_numero_departement[LANGUAGE_NONE][0]['value']) ? $department->field_numero_departement[LANGUAGE_NONE][0]['value'] : '';
    }
    $variables['bien_type'] = '';
    $variables['bien_nb_pieces'] = '';
    $variables['bien_lot_id'] = '';
    $variables['bien_superficie'] = isset($bien->field_superficie[LANGUAGE_NONE][0]['value']) ? $bien->field_superficie[LANGUAGE_NONE][0]['value'] . ' m2' : '';
    if (isset($bien->field_type[LANGUAGE_NONE][0]['tid'])) {
      $bien_type = taxonomy_term_load($bien->field_type[LANGUAGE_NONE][0]['tid']);
      if (isset($bien_type->name)) {
        $variables['bien_type'] = $bien_type->name;
      }
    }
    if (isset($bien->field_nb_pieces[LANGUAGE_NONE][0]['tid'])) {
      $nb_pieces = taxonomy_term_load($bien->field_nb_pieces[LANGUAGE_NONE][0]['tid']);
      if (isset($nb_pieces->name)) {
        $variables['bien_nb_pieces'] = $nb_pieces->name;
      }
    }
    if (isset($bien->field_id_bien[LANGUAGE_NONE][0]['value'])) {
      if (isset($bien_type->name)) {
        $variables['bien_type'] = $bien_type->name;
      }
      if (strrpos($bien->field_id_bien[LANGUAGE_NONE][0]['value'], '-') !== FALSE) {
        $variables['bien_lot_id'] = trim(substr($bien->field_id_bien[LANGUAGE_NONE][0]['value'], strrpos($bien->field_id_bien[LANGUAGE_NONE][0]['value'], '-') + 1));
      }
      else {
        $variables['bien_lot_id'] = $bien->field_id_bien[LANGUAGE_NONE][0]['value'];
      }
    }
    $variables['avant_premiere_title'] = isset($avant_premiere->title) ? $avant_premiere->title : '';
    $variables['avant_premiere_ville'] = '';
    $variables['avant_premiere_department'] = '';
    if (isset($avant_premiere->field_avant_premiere_ville[LANGUAGE_NONE][0]['tid'])) {
      $avant_premiere_ville = taxonomy_term_load($avant_premiere->field_avant_premiere_ville[LANGUAGE_NONE][0]['tid']);
      $variables['avant_premiere_ville'] = isset($avant_premiere_ville->name) ? $avant_premiere_ville->name : '';
    }
    if (isset($avant_premiere->field_avant_premiere_department[LANGUAGE_NONE][0]['tid'])) {
      $avant_premiere_department = taxonomy_term_load($avant_premiere->field_avant_premiere_department[LANGUAGE_NONE][0]['tid']);
      $variables['avant_premiere_department'] = isset($avant_premiere_department->field_numero_departement[LANGUAGE_NONE][0]['value']) ? $avant_premiere_department->field_numero_departement[LANGUAGE_NONE][0]['value'] : '';
    }
    if ($webform_name == '_tre_rappel_') {
      $variables['rappeler_nom'] = isset($values['submitted']['row_1']['rappeler_nom']) ? $values['submitted']['row_1']['rappeler_nom'] : '';
      $variables['rappeler_prenom'] = isset($values['submitted']['row_1']['rappeler_prenom']) ? $values['submitted']['row_1']['rappeler_prenom'] : '';
      $variables['rappeler_telephone'] = isset($values['submitted']['row_2']['rappeler_telephone']) ? $values['submitted']['row_2']['rappeler_telephone'] : '';
      $variables['rappeler_horaire'] = isset($values['submitted']['row_2']['rappeler_horaire']) ? $values['submitted']['row_2']['rappeler_horaire'] : '';
    }
    elseif ($webform_name == 'prendre_rendez_vous') {
      $variables['rdv_nom'] = isset($values['submitted']['row_1']['rdv_nom']) ? $values['submitted']['row_1']['rdv_nom'] : '';
      $variables['rdv_prenom'] = isset($values['submitted']['row_1']['rdv_prenom']) ? $values['submitted']['row_1']['rdv_prenom'] : '';
      $variables['rdv_code_postal'] = isset($values['submitted']['row_2']['rdv_code_postal']) ? $values['submitted']['row_2']['rdv_code_postal'] : '';
      $variables['rdv_ville'] = isset($values['submitted']['row_2']['rdv_ville']) ? $values['submitted']['row_2']['rdv_ville'] : '';
      $variables['rdv_pays'] = isset($values['submitted']['row_2']['rdv_pays']) ? $values['submitted']['row_2']['rdv_pays'] : '';
      $variables['rdv_adresse1'] = isset($values['submitted']['row_3']['rdv_adresse1']) ? $values['submitted']['row_3']['rdv_adresse1'] : '';
      $variables['rdv_adresse2'] = isset($values['submitted']['row_3']['rdv_adresse2']) ? $values['submitted']['row_3']['rdv_adresse2'] : '';
      $variables['rdv_email'] = isset($values['submitted']['row_4']['rdv_email']) ? $values['submitted']['row_4']['rdv_email'] : '';
      $variables['rdv_telephone'] = isset($values['submitted']['row_4']['rdv_telephone']) ? $values['submitted']['row_4']['rdv_telephone'] : '';
      $variables['rdv_lieudit'] = isset($values['submitted']['row_5']['rdv_lieudit']) ? $values['submitted']['row_5']['rdv_lieudit'] : '';
      $variables['rdv_message'] = isset($values['submitted']['rdv_message']) ? $values['submitted']['rdv_message'] : '';
      $variables['rdv_connu'] = isset($values['submitted']['rdv_connu']) ? $values['submitted']['rdv_connu'] : '';
      $variables['rdv_newsletter'] = isset($values['submitted']['rdv_newsletter'][1]) ? (bool) $values['submitted']['rdv_newsletter'][1] : FALSE;
    }
    elseif($webform_name == 'avant_contactez_nous') {
      $variables['rdv_nom'] = isset($values['submitted']['row_1']['ap_nom']) ? $values['submitted']['row_1']['ap_nom'] : '';
      $variables['rdv_prenom'] = isset($values['submitted']['row_1']['ap_prenom']) ? $values['submitted']['row_1']['ap_prenom'] : '';
      $variables['rdv_code_postal'] = isset($values['submitted']['row_2']['ap_code_postal']) ? $values['submitted']['row_2']['ap_code_postal'] : '';
      $variables['rdv_ville'] = isset($values['submitted']['row_2']['ap_ville']) ? $values['submitted']['row_2']['ap_ville'] : '';
      $variables['rdv_adresse1'] = isset($values['submitted']['row_3']['ap_adresse1']) ? $values['submitted']['row_3']['ap_adresse1'] : '';
      $variables['rdv_adresse2'] = isset($values['submitted']['row_3']['ap_adresse2']) ? $values['submitted']['row_3']['ap_adresse2'] : '';
      $variables['rdv_email'] = isset($values['submitted']['row_4']['ap_email']) ? $values['submitted']['row_4']['ap_email'] : '';
      $variables['rdv_telephone'] = isset($values['submitted']['row_4']['ap_telephone']) ? $values['submitted']['row_4']['ap_telephone'] : '';
      $variables['rdv_lieudit'] = isset($values['submitted']['row_5']['ap_lieudit']) ? $values['submitted']['row_5']['ap_lieudit'] : '';
      $variables['rdv_message'] = isset($values['submitted']['ap_message']) ? $values['submitted']['ap_message'] : '';
      $variables['rdv_connu'] = isset($values['submitted']['ap_connu']) ? $values['submitted']['ap_connu'] : '';
      $variables['rdv_newsletter'] = isset($values['submitted']['ap_newsletter'][1]) ? (bool) $values['submitted']['ap_newsletter'][1] : FALSE;
    }
  }
  return $variables;
}
function kandb_webform_send_mail ($template = '', $subject = '', $send_to = 'call_center', $variables = array()) {
  if ($template == '' || $subject == '') {
    return ;
  }
  $content = theme($template, array('mail_vars' => $variables));
  if ($send_to == 'call_center') {
    $mailing_list = str_replace("\r\n", ',', variable_get('kb_call_center_mailing_list', ''));
  }
  else {
    $mailing_list = $send_to;
  }
  if ($mailing_list && $subject && $content) {
    $sender_name = variable_get('kb_call_center_sender_name', '');
    $sender_mail = variable_get('kb_call_center_sender_mail', '');
    $from = $sender_mail ? $sender_name . '<' . $sender_mail . '>' : NULL;
    drupal_mail('kb_mail', 'kb_webform_submit', $mailing_list, 'fr', $params = array('subject' => $subject, 'body' => $content), $from);
  }
  else {
    watchdog('kandb_mail', "Can not send mail to: @receiver", array("@receiver" => $mailing_list), WATCHDOG_ERROR);
  }
}