<?php

  /**
   * Implementation of hook_menu()
   * @return array
   */
  function kandb_finance_archives_menu() {

    $items = array();

    // Front--finance-archives page
    $items['corporate/finance/archives'] = array(
      'title' => t('Documents à télécharger'),
      'page callback' => 'kandb_finance_archives_page',
      'access arguments' => array('access content'),
      'type' => MENU_NORMAL_ITEM,
    );

    $items['corporate/finance/archives/%'] = array(
      'title' => t('Documents à télécharger'),
      'page callback' => 'kandb_finance_archives_page',
      'page arguments' => array(3),
      'access arguments' => array('access content'),
      'type' => MENU_NORMAL_ITEM,
    );

    $items['corporate/finance/archives/%/%'] = array(
      'title' => t('Documents à télécharger'),
      'page callback' => 'kandb_finance_archives_page',
      'page arguments' => array(3, 4),
      'access arguments' => array('access content'),
      'type' => MENU_NORMAL_ITEM,
    );

    $items['download-document-file/%'] = array(
      'title' => t('Télécharger le PDF'),
      'page callback' => 'kandb_finance_archives_download_file',
      'page arguments' => array(1),
      'access arguments' => array('access content'),
      'type' => MENU_NORMAL_ITEM,
    );

    $items['admin/content/ketb/finance/archives'] = array(
      'title' => '[Finance] Archives',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('kandb_finance_archives_admin_form'),
      'access arguments' => array('administer K&B group page'),
      'file' => 'kandb_finance_archives.admin.inc',
      'type' => MENU_LOCAL_TASK,
    );

    return $items;
  }



  /**
   * Implements hook_theme().
   */
  function kandb_finance_archives_theme($existing, $type, $theme, $path) {
    return array(
      'archive' => array(
        'template' => 'templates/archive',
        'variables' => array(),
      ),
      'archive_display_1' => array(
        'template' => 'templates/archive_display_1',
        'variables' => array(),
      ),
      'archive_display_2' => array(
        'template' => 'templates/archive_display_2',
        'variables' => array(),
      ),
      'archive_display_3' => array(
        'template' => 'templates/archive_display_3',
        'variables' => array(),
      ),
    );
  }

function kandb_finance_archives_page($tid = 0, $lang = 'fr') {
  $display_mode = 0;
  if ($tid === 'en' || $tid === 'fr') {
    $lang = $tid;
    $tid = 0;
  }
  $language_id = $lang == 'en' ? 1 : 0;
  if ($lang != 'en') {
    $lang = 'fr';
  }
  $page_title = t('Documents à télécharger');
  if ($language_id == 1) {
    $page_title = variable_get('page_title_archives_en', $page_title);
  }
  else {
    $page_title = variable_get('page_title_archives_fr', $page_title);
  }
  drupal_set_title(t($page_title));
  $content_archives = array();
  $document_voca = taxonomy_vocabulary_machine_name_load('type_de_document');
  if (isset($document_voca->vid)) {
    $all_terms = taxonomy_get_tree($document_voca->vid);
    $base_archive = base_path() . 'corporate/finance/archives/';
    foreach ($all_terms as $term) {
      $term = taxonomy_term_load($term->tid);
//      if ($term->name == 'Assemblée générale' || $term->name == 'Assemblée Générale Extraordinaire') {
//        continue ;
//      }
//      elseif ($language_id == 1) {
      if ($language_id == 1) {
        if (isset ($term->field_name_in_english[LANGUAGE_NONE][0]['value'])) {
          $term->name = $term->field_name_in_english[LANGUAGE_NONE][0]['value'];
        }
      }
      $document = get_document_by_type($term->tid, $language_id, FALSE);
      if ($document && $term) {
        if ($tid == 0) {
          $tid = $term->tid;
          if (isset($term->field_display_mode[LANGUAGE_NONE][0]['value'])) {
            $display_mode = $term->field_display_mode[LANGUAGE_NONE][0]['value'];
          }
        }
        $content_archives['tab_header'][$term->tid] = array(
          'tab_title' => $term->name,
          'tab_url' => $base_archive . $term->tid . '/' . $lang,
          'class' => '',
        );
      }
      if ($term->tid == $tid) {
        $content_archives['tab_header'][$term->tid]['class'] = 'active';
      }
    }
  }
  if ($display_mode == 0 && $tid != 0) {
    $tmp_term = taxonomy_term_load($tid);
    if (isset($tmp_term->field_display_mode[LANGUAGE_NONE][0]['value'])) {
      $display_mode = $tmp_term->field_display_mode[LANGUAGE_NONE][0]['value'];
    }
  }
  $content_archives['tab_content'] = get_document_by_type($tid, $language_id, TRUE);
  $hidetab = TRUE;
  if (!$content_archives['tab_content'] && $tid != 0){
    drupal_goto($base_archive . $lang);
  } elseif(!$content_archives['tab_content'] && $tid == 0){
    $hidetab = FALSE;
  }
  return theme('archive', array(
    'content_archives' => $content_archives,
    'page_title' => $page_title,
    'pager' => theme('pager'),
    'hidetab' => $hidetab,
    'display_mode' => $display_mode,
  ));
}

function get_document_by_type($tid = 0, $language_id = 0, $paging = TRUE, $skip_year = 3) {
  $content = array();
  $current_year = date('Y', time());
  $end_time = strtotime($current_year - $skip_year . '-12-31 23:59:59');
  if ($paging) {
    $db_query = db_select('node', 'n')->extend('PagerDefault');
    $db_query->limit(50);
  }
  else{
    $db_query = db_select('node', 'n');
    $db_query->range(0, 1);
  }
  $db_query->fields('n', array('nid'));
  $db_query->condition('n.type', 'document');
  $db_query->condition('n.status', 1);
  $db_query->condition('n.title', '', '<>');

  $db_query->leftJoin('field_data_field_document_file', 'df', 'df.entity_id=n.nid');
  $db_query->condition('df.entity_type', 'node');
  $db_query->condition('df.bundle', 'document');
  $db_query->isNotNull('df.field_document_file_fid');

  $db_query->leftJoin('field_data_field_document_type', 'dt', 'dt.entity_id=n.nid');
  $db_query->condition('dt.entity_type', 'node');
  $db_query->condition('dt.bundle', 'document');
  $db_query->condition('dt.field_document_type_tid', $tid);

  $db_query->leftJoin('field_data_field_langue', 'dl', 'dl.entity_id=n.nid');

  if ($language_id == 1) {
    $db_query->condition('dl.entity_type', 'node');
    $db_query->condition('dl.bundle', 'document');
    $db_query->condition('dl.field_langue_value', $language_id);
  }
  else {
    $db_or = db_or();
      $db_and = db_and();
      $db_and->condition('dl.field_langue_value', $language_id);
      $db_and->condition('dl.bundle', 'document');
      $db_and->condition('dl.field_langue_value', $language_id);
    $db_or->condition($db_and);
    $db_or->isNull('dl.field_langue_value');
    $db_query->condition($db_or);
  }

  $db_query->leftJoin('field_data_field_document_date', 'dd', 'dd.entity_id=n.nid');
  $db_query->condition('dd.entity_type', 'node');
  $db_query->condition('dd.bundle', 'document');
  $db_query->addField('dd', 'field_document_date_value');
  $db_query->where('UNIX_TIMESTAMP(dd.field_document_date_value) < :val_end', array('val_end' => $end_time));
  $db_query->distinct();
  $db_query->orderBy('dd.field_document_date_value', 'DESC');
  $results = $db_query->execute()->fetchAll();
  foreach($results as $res) {
    $node = node_load($res->nid);
    $year = date('Y', strtotime($res->field_document_date_value));
    if (!isset($node->title) || $node->title == '' || !isset($node->field_document_file[LANGUAGE_NONE][0]['fid'])) {
      continue;
    }
    if (!isset($content[$year])) {
      $content[$year] = array();
    }
    $content[$year][] = $node;
  }
  krsort($content);
  return $content;
}

function kandb_finance_archives_download_file ($fid = 0) {
  $file = file_load($fid);
  if ($file && file_exists($file->uri)) {
    $content_disposition = 'attachment; filename="' . basename($file->uri) . '"';
    $content_type = file_get_mimetype(basename($file->uri));
    $headers = array
      (
      'Content-type' => $content_type,
      'Content-Disposition' => $content_disposition,
      'Content-Transfer-Encoding' => 'binary',
    );
    file_transfer($file->uri, $headers);
  } else {
    drupal_set_message(t('File does not exist.'));
  }
}