// Auteur: ALTO Informatique, 33 avenue du Maine 75015 Paris - 2015 - Tous droits r�serv�s
var a,AltoUtil=function(){};AltoUtil.dtrace=function(b){_g_alto.iComp++;b=AltoUtil.drawString(_g_alto,_mc,_g_alto.iComp+1E3,b,5,5,400,20,null);_g_alto._mc[b].maj()};AltoUtil.dtrace2=function(b,c,d,e,f,h){c=c?c:5;d=d?d:5;e=e?e:400;f=f?f:20;_g_alto.iComp++;b=AltoUtil.drawString(_g_alto,_mc,_g_alto.iComp+1E3,b,c,d,e,f,h);_g_alto._mc[b].maj()};
AltoUtil.drawLine=function(b,c,d,e,f,h,g){var j;if(d>f){j=d;d=f;f=j}if(e>h){j=e;e=h;h=j}f-d==0&&f++;h-e==0&&h++;b=c.createEmptyMovieClip(b,null,null,d,e,f-d,h-e);b.style.backgroundColor=typeof g!="undefined"?AltoUtil.getHtmlColor(g):"#000000";b.style.overflow="hidden"};AltoUtil.drawString=function(b,c,d,e,f,h,g,j,i){var l;l="label"+parseInt(Math.random()*1E10,10);c.createTextField(b,l,d,f,h,g,j);typeof i!="undefined"&&c[l].setNewTextFormat(i);c[l].text=e;c[l].selectable=false;c[l].maj();return l};
AltoUtil.HtmlToStr=function(b){b=b;b=AltoUtil.strReplace(b,"&#39;","'");b=AltoUtil.strReplace(b,"&#233;","\ufffd");b=AltoUtil.strReplace(b,"&#232;","\ufffd");b=AltoUtil.strReplace(b,"&#244;","\ufffd");b=AltoUtil.strReplace(b,"&#224;","\ufffd");b=AltoUtil.strReplace(b,"&lt;","<");b=AltoUtil.strReplace(b,"&gt;",">");return b=AltoUtil.strReplace(b,"&nbsp;"," ")};
AltoUtil.PaintRect=function(b,c,d,e,f,h,g,j,i){var l;l="rect"+parseInt(Math.random()*1E10,10);b=c.createEmptyMovieClip(b,l,null,d,e,f,h);if(typeof g!="undefined"&&g!=null){b.style.borderColor=AltoUtil.getHtmlColor(g);b.style.borderStyle="solid";b.style.borderWidth="1px"}else b.style.borderStyle="none";b.style.overflow="hidden";if(typeof j!="undefined"&&j!=null){b.style.backgroundColor=AltoUtil.getHtmlColor(j);if(typeof i!="undefined"){b.style.opacity=i/100;b.style.MozOpacity=i/100;b.style.Alpha=i}}return l};
AltoUtil.getColorFromStr=function(b){if(b.substr(0,1)=="#")b=b.substr(1);else if(b.substr(0,2)=="0x")b=b.substr(2);if(b.length==6){b=parseInt(b,16);if(!isNaN(b))return b}return-1};AltoUtil.getHtmlColor=function(b){try{var c;if(typeof b=="number")if(b==0)return"#000000";else{var d;c=b.toString(16);for(d=c.length;d<6;d++)c="0"+c;return"#"+c}else{c=""+b;if(c.substr(0,1)=="#")return c;else if(c.substr(0,2)=="0x")return c="#"+c.substr(2)}}catch(e){AltoUtil.dtrace("color : "+b)}return"#FF0000"};
AltoUtil.round=function(b,c){return b=c?Math.round(b*10*c)/(10*c):Math.round(b)};AltoUtil.setEnable=function(b,c,d){b.backgroundColor=c?16777215:d?d:13421772;b.selectable=c};
AltoUtil.SetTextBox=function(b,c,d,e,f,h,g,j,i,l,k){if(k&16){f+=2;h+=1;g-=4;j-=2}else if(document.compatMode=="CSS1Compat"){g-=2;j-=2}else _s_alto.IsHTML5||j++;c.createTextField(b,d,e,f,h,g,j);b=c[d];c=document.createElement("input");c.setAttribute("id",b.id+"_input");(k&1)==0?c.setAttribute("type",navigator.userAgent.indexOf("Chrome")!=-1?"text":"number"):c.setAttribute("type","text");c.style.zIndex=b.div.style.zIndex+1;c.style.position="absolute";c.style.width=b._width+"px";c.style.height=b._height+
"px";c.style.border="solid";c.style.padding=_s_alto.IsIE?"1px 0px 0px 0px":"0px 0px 1px 0px";if(k&16)c.style.border="none";b.div.appendChild(c);b.input=document.getElementById(b.id+"_input");b.type="input";b.multiline=true;if((k&16)==0){b.border=true;b.borderColor=l?l:8488911}b.background=true;b.setNewTextFormat(i);if((k&1)==0)b.restrict="[0-9]*";else if(k&2)b.restrict="^[0-9]*,?[0-9]+$"};AltoUtil.stricmp=function(b,c){b=b.toLowerCase();c=c.toLowerCase();return b==c?0:b<c?-1:1};
AltoUtil.strReplace=function(b,c,d){var e=c.length,f=d.length,h=0;if(b.length==0||e==0)return b;for(;;){h=b.indexOf(c,h);if(h==-1)break;b=b.substr(0,h)+d+b.substr(h+e);h+=f}return b};
AltoUtil.StrEncode=function(b,c){if(b==null||b.length==0)return b;if(c&1)b=AltoUtil.strReplace(b,"\\","\\\\");if(c&16)b=AltoUtil.strReplace(b,'"','\\"');if(c&32)b=AltoUtil.strReplace(b,"'","\\'");if(c&256){b=AltoUtil.strReplace(b,"\r","");b=AltoUtil.strReplace(b,"\n","\\n")}if(c&512)b=AltoUtil.strReplace(b,"\r\n","\\r\\n");if(c&4096)return'"'+b+'"';return b};
AltoUtil.JSON_FromString=function(b,c,d){var e=b.length,f,h,g=0,j=0,i=0,l=0;for(f=0;f<e;f++){var k=b.charAt(f);if(k=="["&&g==0){k=AltoUtil.JSON_FromStringSearchFinObj(b.substr(f));var m=b.substr(f+1,k-2);h=[];AltoUtil.JSON_FromString(m,h,2);if(d==2){c.push(h);f+=k}else return h}else if(k=="{"&&g==0){k=AltoUtil.JSON_FromStringSearchFinObj(b.substr(f));m=b.substr(f+1,k-2);h={};AltoUtil.JSON_FromString(m,h,1);if(d==2){c.push(h);i=g=j=0;f+=k}else return h}else if(k==":"&&g==1&&j==0){k=AltoUtil.JSON_FromStringSearchFinObj(b.substr(f+
1));g=b.substr(i,f-i);if(g.charAt(0)=='"'&&g.charAt(g.length-1)=='"')g=g.substr(1,g.length-2);c[g]=AltoUtil.JSON_FromString(b.substr(f+1,k),null,null);i=g=j=0;f+=k}else if(k==","&&g==1&&j==0){if(d==2){g=b.substr(i,f-i);c.push(g=="null"?null:parseFloat(g));i=g=j=0}}else if(d!=1&&(k=='"'||k=="'")&&(f==0||b.charAt(f-1)!="\\"))if(j==0){l=k=='"'?1:0;j=g=1;i=f+1}else{if(!(k=='"'&&l==0))if(!(k=="'"&&l==1))if(d==2){c.push(b.substr(i,f-i));i=g=j=0}else return b.substr(i,f-i)}else if(!((k==" "||k=="\r"||k==
"\n"||k=="\t")&&j==0))if(k!=","&&g==0){g=1;i=f}}if(g==1){if(d==2){g=b.substr(i);c.push(g=="null"?null:g=="true"?true:g=="false"?false:parseFloat(g));return 0}g=b.substr(i,f-i);return g=="null"?null:g=="true"?true:g=="false"?false:parseFloat(g)}return h};
AltoUtil.JSON_FromStringSearchFinObj=function(b){var c,d=b.length,e=null,f=0,h=0,g=0,j=0;for(c=0;c<d;c++){var i=b.charAt(c);if(g==0&&(i=="{"||i=="[")){if(e==null)e=i;if(i=="{")f++;else i=="["&&h++}else if(g==0&&(i=="}"||i=="]"))if(i=="}"){f--;if(f==0&&e=="{")return c+1}else{if(i=="]"){h--;if(h==0&&e=="[")return c+1}}else if(g==0&&i==","&&f==0&&h==0)return c;else if((i=='"'||i=="'")&&(c==0||b.charAt(c-1)!="\\"))if(g==0){j=i=='"'?1:0;g=1}else if(!(i=='"'&&j==0))if(!(i=="'"&&j==1))if(f==0&&h==0)return c+
1;else g=0}};AltoUtil.JSON_ToString=function(b,c){var d="";if(b==null)d="null";else if(typeof b=="object")if(c&2){d="[";for(var e=b.length,f=0;f<e;f++){if(f>0)d+=",";d+=AltoUtil.JSON_ToString(b[f],null)}d+="]"}else{d="{";e=0;if((c&1)==0){c=1;var h=0;for(f in b){if(f!=h){c=0;break}h++}if(c)return AltoUtil.JSON_ToString(b,2)}for(f in b){if(e>0)d+=",";c=f.charAt(0)=='"'?"":'"';d+=c+f+c+":"+AltoUtil.JSON_ToString(b[f],null);e++}d+="}"}else d=typeof b=="string"?'"'+AltoUtil.StrEncode(b,49)+'"':""+b;return d};var AltoFormatage=function(){};AltoFormatage.FormatFloat=function(b){b=""+parseFloat(Util_alto.strReplace(""+b,",","."));var c=b.indexOf(".");c=b.length-(c!=-1?c:0);for(var d=c-3;c>3;){b=AltoFormatage.StrInsert(b,d," ");c-=3;d-=3}return b=AltoUtil.strReplace(b,".",",")};AltoFormatage.FormatInteger=function(b){b=""+parseInt(""+b,10);for(var c=b.length,d=c-3;c>3;){b=AltoFormatage.StrInsert(b,d," ");c-=3;d-=3}return b};AltoFormatage.StrInsert=function(b,c,d){return b.slice(0,c)+d+b.slice(c,b.length)};
AltoFormatage.FloatFromFormatFloat=function(b){var c,d,e=b.length,f="";for(c=0;c<e;c++){d=b.charAt(c);if(d!=" "){if(d==",")d=".";f+=d}}return parseFloat(f)};AltoFormatage.IntFromFormatInteger=function(b){var c,d,e,f="";if(b==null)return null;e=b.length;for(c=0;c<e;c++){d=b.charAt(c);if(d!=" ")f+=d}return parseInt(f,10)};var AltoTextFormat=function(b,c,d,e,f,h,g,j,i,l,k,m,n){this.align=i;this.bold=e;this.color=d;this.font=b;this.indent=m;this.italic=f;this.leading=n;this.leftMargin=l;this.rightMargin=k;this.size=c;this.target=j;this.underline=h;this.url=g};var __g_alto={},_g_alto=null,_s_alto={},TFFF_F1_STR=0,TFFF_F1_INT=1,TFFF_F1_FLOAT=2,TFFF_F1_MASK=15,Util_alto=AltoUtil,Formatage_alto=AltoFormatage;_s_alto.IsEcranTactile=isTouchDevice();_s_alto.IsIE=navigator.userAgent.toLowerCase().indexOf("msie")!=-1||navigator.userAgent.toLowerCase().indexOf("trident/")!=-1?1:0;_s_alto.IsIE_10_ou_inf=_s_alto.IsIE==1&&(navigator.userAgent.indexOf("Trident")==-1||navigator.userAgent.indexOf("MSIE ")!=-1)?1:0;_s_alto.IsHTML5=IsHTML5();
_s_alto.CCursor={DEFAULT_CURSOR:0,N_RESIZE_CURSOR:1,W_RESIZE_CURSOR:2,SW_RESIZE_CURSOR:4,MASK_RESIZE_CURSOR:15,CursorType:null};_s_alto.ID_TAUX_FIXE=1;_s_alto.ID_TAUX_REV=2;_s_alto.ID_TAUX_REV_CAPE=3;_s_alto.ID_TAUX_CHOISI=9;_s_alto.TAB_ID_TAUX=new Array(_s_alto.ID_TAUX_FIXE,_s_alto.ID_TAUX_REV,_s_alto.ID_TAUX_REV_CAPE,_s_alto.ID_TAUX_CHOISI);_s_alto.ZONE_F_INIT_GRAPH=1;_s_alto.ZONE_F_GRAPH=2;_s_alto.ZONE_F_GRADUATION=4;_s_alto.ZONE_F_ALL=65535;_s_alto.ZCLIC_F_MENS_HAUT=1;
_s_alto.ZCLIC_F_MENS_DROITE=2;_s_alto.ZCLIC_F_MENS_DIAG=4;_s_alto.ZCLIC_F_PRET_HAUT=8;_s_alto.ZCLIC_F_GRAPH_MASK=15;_s_alto.ZCLIC_F_AIDE=256;_s_alto.ZCLIC_F_COPYRIGHT=512;_s_alto.TEXTFIELD_HAUTEUR=20;_s_alto.UNITE_PIXEL_X=12;_s_alto.PADDING_TOP=8;_s_alto.MARGE_GAUCHE=55;_s_alto.MARGE_HAUT=_s_alto.PADDING_TOP+55;_s_alto.MARGE_DROITE=15;_s_alto.X_DIST_ORIGINE_DEBUT=0;_s_alto.Y_DIST_ORIGINE_DEBUT=0;_s_alto.TAILLE_AXE_Y=160;_s_alto.TAILLE_AXE_X=248;_s_alto.TAILLE_AXE_Y_PRET=160;
_s_alto.TAILLE_AXE_X_PRET=80;_s_alto.BULLE_X_HAUTEUR_MIN=46;_s_alto.ATFG_PUT_FOCUS=1;_s_alto.ATFG_SELECTION=2;_s_alto.MODE_IDENT_NO=0;_s_alto.MODE_IDENT_AllInFlash=1;_s_alto.MODE_IDENT_FormFlash=2;_s_alto.MODE_IDENT_AllInHtml=3;
_s_alto.ONLS={NLS0:{revlib1:"Votre revenu :",revlib2:"/mois.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Taux du pr&ecirc;t :",revlib3:"/mois.",mensual:"mensualit&eacute;",duree:"dur&eacute;e",pret1:"Montant pr&ecirc;t",pret2:"montant<br/>du pr&ecirc;t",VotMensual:"Votre mensualit&eacute;",sur:"sur",ans:"ans et",ans2:"ans",mois:"mois",PC33:"33% du revenu",endettement:"tx endett. :",calcul:"Calcul"},NLS1033:{revlib1:"Your income :",revlib2:" / month.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Rate of loan :",
revlib3:" / month",mensual:"Monthly payment",duree:"period",pret1:"Loan amount",pret2:"Amount<br/>of loan",VotMensual:"Your monthly payment",sur:"over",ans:"years and",ans2:"years",mois:"months",PC33:"33% of income",endettement:"Debt ratio :",calcul:"Calculation"},NLS1040:{revlib1:"Il vostro stipendio :",revlib2:" / mese.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Importo tasso :",revlib3:" / mese.",mensual:"mensilit&agrave;",duree:"durata",pret1:"Importo mutuo",pret2:"Importo<br/>mutuo",VotMensual:"La vostra mensilit&agrave;",
sur:"su",ans:"Anni e",ans2:"Anni",mois:"mesi",PC33:"33% dello stipendio",endettement:"debito :",calcul:"Calcolo"},NLS2070:{revlib1:"O seu rendimento :",revlib2:" / m&ecirc;s.&nbsp;&nbsp;&nbsp;&nbsp;Taxa de empr&eacute;stimo :",revlib3:" / m&ecirc;s.",mensual:"mensalidade",duree:"prazo",pret1:"Empr&eacute;stimo",pret2:"empr&eacute;stimo",VotMensual:"A sua mensalidade",sur:"em",ans:"anos e",ans2:"anos",mois:"meses",PC33:"33% do rendimento",endettement:"taxa d&iacute;vida :",calcul:"C&Aacute;LCULO"},
NLS1049:{revlib1:"\u0412\u0430\u0448 \u0434\u043e\u0445\u043e\u0434:",revlib2:" / \u043c\u0435\u0441\u044f\u0446\t\u0412\u0430\u0448 \u0437\u0430\u0451\u043c\u041f\u043e \u0444\u0438\u043a\u0441. \u0441\u0442\u0430\u0432\u043a\u0435",revlib3:" / \u043c\u0435\u0441\u044f\u0446\t\u0412\u0430\u0448 \u0437\u0430\u0451\u043c",mensual:"\u0415\u0436\u0435\u043c\u0435\u0441\u044f\u0447\u043d\u044b\u0435 \u0432\u044b\u043f\u043b\u0430\u0442\u044b",duree:"\u0421\u0440\u043e\u043a",pret1:"\u0421\u0443\u043c\u043c\u0430 \u0437\u0430\u0439\u043c\u0430",
pret2:"\u0421\u0443\u043c\u043c\u0430 \u0437\u0430\u0439\u043c\u0430",VotMensual:"\u0412\u0430\u0448\u0438 \u0435\u0436\u0435\u043c\u0435\u0441\u044f\u0447\u043d\u044b\u0435 \u0432\u044b\u043f\u043b\u0430\u0442\u044b",sur:"\u043d\u0430 ",ans:"\u043b\u0435\u0442 \u0438",ans2:"\u043b\u0435\u0442",mois:"\u043c\u0435\u0441.",PC33:"33% \u0434\u043e\u0445\u043e\u0434\u0430",endettement:"\u0417\u0430\u0434\u043e\u043b\u0436\u0435\u043d\u043d\u043e\u0441\u0442\u044c :",calcul:"\u0420\u0430\u0441\u0441\u0447\u0438\u0442\u0430\u0442\u044c"}};
_s_alto.bw=1;if(navigator.userAgent.toLowerCase().indexOf("msie")!=-1)_s_alto.bw=0;var _gc_alto={TFContext:{OldValue:"",IsChanged:0,FlagFormat:0,size:0},CurrentCCursor:null};
function GlobalInit(b){b.root={};b.library={clip:[{id:"ImgAide1","import": ROOT_MODULE+"/library/aide1.png"},{id:"ImgAide2","import": ROOT_MODULE+"/library/aide2.png"},{id:"ImgLogoAlto","import": ROOT_MODULE+"/library/logo_alto.png"},{id:"ImgCopyright","import": ROOT_MODULE +"/library/_copyright.png"}]};b.IsPretToMensDuree=0;b.IsFixeMontantPret=0;b.NbMoisMaxi=360;b.RevenuOnLoad=2E3;b.mcPoigneeMens=null;b.mcPoigneeDuree=null;b.mcPoigneeMensDuree=null;b.mcPoigneePret=null;b.TabValTaux=new Array("&agrave; taux fixe","&agrave; taux r&eacute;visable",
"&agrave; taux r&eacute;v. Cap&eacute;","au taux suivant :");b.TabTauxIsPresent=new Array(0,0,0,1);b.IsTauxUnique=1;b.NbTypeTaux=1;b.TypeTaux=_s_alto.ID_TAUX_CHOISI;b.DefaultTypeTaux=0;b.Monnaie="&euro;";b.UrlTrameFondEcran=null;b.IsHideBottomTextBox=false;b.IsHideLabels=false;b.IsHideHelp=false;b.IsFieldsWithoutBorder=false;b.BtnCalcul_UrlImageHaut=null;b.BtnCalcul_UrlImageBas=null;b.BtnAide_UrlImageHaut=null;b.BtnAide_UrlImageBas=null;b.TaillePoignees=4;b.CodeNLS=0;b.ColorBG=15595006;b.ColorGraphBG=
13158655;b.ColorGraphContour=8947848;b.ColorBorder=null;b.ColorBulle=16774039;b.ColorBulleOmbre=8421504;b.Color33PC=3453238;b.ColorNomGraph=7829367;b.ColorCadre=13557759;b.ColorCadreBorder=0;b.ColorLabel=0;b.ColorFieldText=0;b.ColorFieldBorder=8488911;b.ColorDisabled=13421772;b.ColorAxeGraduation=0;b.ColorContourPoignees=1441999;b.ColorMensInf33PC=16762415;b.ColorMensSupp33PC=16715535;b.ColorPret=6139680;b.ColorBtnCalculBG=5275903;b.ColorBtnCalculText=16777215;b.PasNbMois=1;b.UnitePixelX=12;b.UnitePixelY=
12.5;b.UnitePixelPret=3E3;b.APPLET_DIMENSION={width:480,height:320};b.MargeGauche_Mens=50;b.MargeGauche_Pret=385;b.IsGraphiqueDessine=false;b.ModeIdentification=0;b.MyIdentPage="ident.php";b.AskEmail="saisissez votre e-mail";b.JSToCallForHtmlIdent="alto_flash_ShowHtmlFormIdent";b.JSToCallForSendIdent="alto_flash_SendIdent";b.TabTauxFixe={NbPlageTaux:7,tabTranche:[],tabTaux:[]};b.TabTauxVariable={NbPlageTaux:7,tabTranche:[],tabTaux:[]};b.HmcBarre33PC=30;b.IsCopyright=true;b.IsCopyrightActivate=false;
b.IsAideActivate=false;b.IsDeuxImgAide=false;b.MouseGestion={idDivPressed:null,ClientXIni:null,ClientYIni:null,ClientXLast:null,ClientYLast:null,ValXIni:null,ValYIni:null};b.LieuPressed={x:0,y:0,ZoneClic:0,IsCapture:false};b.Donnees={revenu:0,taux:4.5,mensualite:0,duree:180,pret:0,mensualiteMax:2E3,mensualiteMin:1,dureeMax:600,dureeMin:12,pretPlafond:0,pretMax:0,pretMin:0,revenuMax:15E3,revenuMin:500,dureeMaxAvantMensualite:300};b.OldDonnees={mensualite:0,duree:180,pret:0};b.iComp=0;b.PoliceStd="VERDANA";
b.fontLabel=new AltoTextFormat(b.PoliceStd,11);b.fontDialog=new AltoTextFormat(b.PoliceStd,11);b.LabelW1=100;b.LabelH1=20;b.TextBoxH=18}function IsHTML5(){if(document.doctype===null)return 0;var b=document.doctype;return"<!DOCTYPE "+b.name+(b.publicId?' PUBLIC"'+b.publicId+'"':"")+(!b.publicId&&b.systemId?" SYSTEM":"")+(b.systemId?' "'+b.systemId+'"':"")+">"==="<!DOCTYPE html>"?1:0}
function MkBulles(b,c){var d,e,f;c.createEmptyMovieClip(b,"mcBulleMensDuree",b.iComp++);f=c.mcBulleMensDuree;f._visible=false;d=new AltoTextFormat("ARIAL",10);d.align="center";d.leading=-2;PaintBulleRect(b,f,b.BulleMensCoord);e=Util_alto.drawString(b,f,null,"",b.BulleMensCoord.x,b.BulleMensCoord.y+5,b.BulleMensCoord.width,b.BulleMensCoord.height+10,d);f[e].multiline=true;b.label_BulleMensDuree=f[e];c.createEmptyMovieClip(b,"mcBullePret",b.iComp++);f=c.mcBullePret;PaintBulleRect(b,f,b.BullePretCoord);
f._visible=false;e=Util_alto.drawString(b,f,null,"",b.BullePretCoord.x,b.BullePretCoord.y+6,b.BullePretCoord.width,b.LabelH1,d);b.label_BullePret=f[e]}function PaintBulleRect(b,c,d){var e=16;Util_alto.PaintRect(b,c,d.x,d.y,d.width,d.height,0,_g_alto.ColorBulle)}
function paint(b,c,d){try{var e;if(d&_s_alto.ZONE_F_INIT_GRAPH){Util_alto.PaintRect(b,c,0,0,b.APPLET_DIMENSION.width-1,b.APPLET_DIMENSION.height-1,b.ColorBorder);c.createEmptyMovieClip(b,"mcPoignees",500,0,0,b.APPLET_DIMENSION.width-1,b.APPLET_DIMENSION.height-1);if(b.UrlTrameFondEcran==null||!b.UrlTrameFondEcran){Util_alto.PaintRect(b,c,_s_alto.MARGE_GAUCHE-48,_s_alto.PADDING_TOP,_s_alto.IsIE&&document.compatMode!="CSS1Compat"?467:465,_s_alto.IsIE&&document.compatMode!="CSS1Compat"?31:29,b.ColorCadreBorder,
b.ColorCadre);if(!b.IsHideBottomTextBox){PaintGraphTextfieldFond(b,c,b.RectMens.x-1,_s_alto.TAILLE_AXE_X+8);PaintGraphTextfieldFond(b,c,b.RectPret.x-1,_s_alto.TAILLE_AXE_X_PRET)}}if(!b.IsHideLabels){e=new AltoTextFormat(b.PoliceStd,11);e.color=b.ColorNomGraph;Util_alto.drawString(b,c,b.iComp++,b.OTxtLang.mensual,b.MargeGauche_Mens+5,_s_alto.MARGE_HAUT-5,200,b.LabelH1,e);e.align="right";Util_alto.drawString(b,c,b.iComp++,b.OTxtLang.duree,b.MargeGauche_Mens+_s_alto.TAILLE_AXE_X-b.LabelW1+4,_s_alto.MARGE_HAUT+
_s_alto.TAILLE_AXE_Y-14,b.LabelW1,b.LabelH1,e)}GraduationHorizontale(b,b.x_PointOrigine_util,c);PaintGraphEncadrement(b,c.mcGraphEncadrement)}if(d&_s_alto.ZONE_F_GRAPH){var f;if(d&_s_alto.ZONE_F_GRADUATION){GraduationVerticale(b,b.y_PointOrigine_util,c);GraduationVerticalePret(b)}MajRect(b);f=c.mcRectMensDuree;f.clear();Util_alto.PaintRect(b,f,b.RectMens.x,b.RectMens.y,b.RectMens.width,b.RectMens.height,null,b.ColorMensInf33PC);b.RectMens.y<b.Barre33PC&&Util_alto.PaintRect(b,f,b.RectMens.x,b.RectMens.y,
b.RectMens.width,b.RectMens.height-b.RevenuPourcentageGraphique,null,b.ColorMensSupp33PC);Util_alto.drawLine(b,f,b.RectMens.x,b.RectMens.y,b.RectMens.x+b.RectMens.width,b.RectMens.y,b.ColorContourPoignees);Util_alto.drawLine(b,f,b.RectMens.x+b.RectMens.width,b.RectMens.y,b.RectMens.x+b.RectMens.width,b.RectMens.y+b.RectMens.height,b.ColorContourPoignees);if(b.mcPoigneeMens){c.mcPoignees[b.mcPoigneeMens]._x=b.MargeGauche_Mens+b.RectMens.width/2-b.SizePoignee/2;c.mcPoignees[b.mcPoigneeMens]._y=b.RectMens.y-
b.SizePoignee/2;c.mcPoignees[b.mcPoigneeMens].maj()}else{b.mcPoigneeMens=Util_alto.PaintRect(b,c.mcPoignees,b.MargeGauche_Mens+b.RectMens.width/2-b.SizePoignee/2,b.RectMens.y-b.SizePoignee/2,b.SizePoignee,b.SizePoignee,null,_s_alto.IsEcranTactile?null:b.ColorContourPoignees);c.mcPoignees[b.mcPoigneeMens].div.style.cursor="n-resize";c.mcPoignees[b.mcPoigneeMens].div.id=b.DivId+"mcPoigneeMens";c.mcPoignees[b.mcPoigneeMens].div.onmousedown=function(i){IdentPoigneePressed(i,b)};c.mcPoignees[b.mcPoigneeMens].div.onmouseup=
function(){b.MouseGestion.IdDivPressed=null};if(_s_alto.IsEcranTactile){Util_alto.PaintRect(b,c.mcPoignees[b.mcPoigneeMens],b.EcartPoigneeVisible/2,b.EcartPoigneeVisible/2,b.SizePoignee-b.EcartPoigneeVisible,b.SizePoignee-b.EcartPoigneeVisible,null,b.ColorContourPoignees);c.mcPoignees[b.mcPoigneeMens].div.addEventListener("touchstart",function(i){touchHandler2(i,b)},false);c.mcPoignees[b.mcPoigneeMens].div.addEventListener("touchend",function(){b.MouseGestion.IdDivPressed=null},false)}}if(b.mcPoigneeDuree){c.mcPoignees[b.mcPoigneeDuree]._x=
b.MargeGauche_Mens+b.RectMens.width-b.SizePoignee/2;c.mcPoignees[b.mcPoigneeDuree]._y=b.RectMens.y+b.RectMens.height/2-b.SizePoignee/2;c.mcPoignees[b.mcPoigneeDuree].maj()}else{b.mcPoigneeDuree=Util_alto.PaintRect(b,c.mcPoignees,b.MargeGauche_Mens+b.RectMens.width-b.SizePoignee/2,b.RectMens.y+b.RectMens.height/2-b.SizePoignee/2,b.SizePoignee,b.SizePoignee,null,_s_alto.IsEcranTactile?null:b.ColorContourPoignees);c.mcPoignees[b.mcPoigneeDuree].div.style.cursor="e-resize";c.mcPoignees[b.mcPoigneeDuree].div.id=
b.DivId+"mcPoigneeDuree";c.mcPoignees[b.mcPoigneeDuree].div.onmousedown=function(i){IdentPoigneePressed(i,b)};c.mcPoignees[b.mcPoigneeDuree].div.onmouseup=function(){b.MouseGestion.IdDivPressed=null};if(_s_alto.IsEcranTactile){Util_alto.PaintRect(b,c.mcPoignees[b.mcPoigneeDuree],b.EcartPoigneeVisible/2,b.EcartPoigneeVisible/2,b.SizePoignee-b.EcartPoigneeVisible,b.SizePoignee-b.EcartPoigneeVisible,null,b.ColorContourPoignees);c.mcPoignees[b.mcPoigneeDuree].div.addEventListener("touchstart",function(i){touchHandler2(i,
b)},false);c.mcPoignees[b.mcPoigneeDuree].div.addEventListener("touchend",function(){b.MouseGestion.IdDivPressed=null},false)}}if(b.mcPoigneeMensDuree){c.mcPoignees[b.mcPoigneeMensDuree]._x=b.MargeGauche_Mens+b.RectMens.width-b.SizePoignee/2;c.mcPoignees[b.mcPoigneeMensDuree]._y=b.RectMens.y-b.SizePoignee/2;c.mcPoignees[b.mcPoigneeMensDuree].maj()}else{b.mcPoigneeMensDuree=Util_alto.PaintRect(b,c.mcPoignees,b.MargeGauche_Mens+b.RectMens.width-b.SizePoignee/2,b.RectMens.y-b.SizePoignee/2,b.SizePoignee,
b.SizePoignee,null,_s_alto.IsEcranTactile?null:b.ColorContourPoignees);c.mcPoignees[b.mcPoigneeMensDuree].div.style.cursor="ne-resize";c.mcPoignees[b.mcPoigneeMensDuree].div.id=b.DivId+"mcPoigneeMensDuree";c.mcPoignees[b.mcPoigneeMensDuree].div.onmousedown=function(i){IdentPoigneePressed(i,b)};c.mcPoignees[b.mcPoigneeMensDuree].div.onmouseup=function(){b.MouseGestion.IdDivPressed=null};if(_s_alto.IsEcranTactile){Util_alto.PaintRect(b,c.mcPoignees[b.mcPoigneeMensDuree],b.EcartPoigneeVisible/2,b.EcartPoigneeVisible/
2,b.SizePoignee-b.EcartPoigneeVisible,b.SizePoignee-b.EcartPoigneeVisible,null,b.ColorContourPoignees);c.mcPoignees[b.mcPoigneeMensDuree].div.addEventListener("touchstart",function(i){touchHandler2(i,b)},false);c.mcPoignees[b.mcPoigneeMensDuree].div.addEventListener("touchend",function(){b.MouseGestion.IdDivPressed=null},false)}}if(d&_s_alto.ZONE_F_GRADUATION)c.mcBarre33PC._y=b.Barre33PC-b.HmcBarre33PC;f=c.mcRectPret;f.clear();Util_alto.PaintRect(b,f,b.RectPret.x,b.RectPret.y,b.RectPret.width,b.RectPret.height,
null,b.ColorPret);Util_alto.drawLine(b,f,b.RectPret.x,b.RectPret.y,b.RectPret.x+b.RectPret.width,b.RectPret.y,b.ColorContourPoignees);if(b.mcPoigneePret){c.mcPoignees[b.mcPoigneePret]._y=b.RectPret.y-b.SizePoignee/2;c.mcPoignees[b.mcPoigneePret].maj()}else{b.mcPoigneePret=Util_alto.PaintRect(b,c.mcPoignees,b.RectPret.x+b.RectPret.width/2-b.SizePoignee/2,b.RectPret.y-b.SizePoignee/2,b.SizePoignee,b.SizePoignee,null,_s_alto.IsEcranTactile?null:b.ColorContourPoignees);c.mcPoignees[b.mcPoigneePret].div.style.cursor=
"n-resize";c.mcPoignees[b.mcPoigneePret].div.id=b.DivId+"mcPoigneePret";c.mcPoignees[b.mcPoigneePret].div.onmousedown=function(i){IdentPoigneePressed(i,b)};c.mcPoignees[b.mcPoigneePret].div.onmouseup=function(){b.MouseGestion.IdDivPressed=null};if(_s_alto.IsEcranTactile){Util_alto.PaintRect(b,c.mcPoignees[b.mcPoigneePret],b.EcartPoigneeVisible/2,b.EcartPoigneeVisible/2,b.SizePoignee-b.EcartPoigneeVisible,b.SizePoignee-b.EcartPoigneeVisible,null,b.ColorContourPoignees);c.mcPoignees[b.mcPoigneePret].div.addEventListener("touchstart",
function(i){touchHandler2(i,b)},false);c.mcPoignees[b.mcPoigneePret].div.addEventListener("touchend",function(){b.MouseGestion.IdDivPressed=null},false)}}c="";var h=b.Donnees.duree%_s_alto.UNITE_PIXEL_X,g=Math.round(b.Donnees.mensualite/b.Donnees.revenu*100);c+=Formatage_alto.FormatInteger(b.Donnees.mensualite)+" "+b.Monnaie+" "+b.OTxtLang.sur+(b.CodeNLS=="1049"?"":"<br/>")+Math.floor(b.Donnees.duree/_s_alto.UNITE_PIXEL_X)+" "+b.OTxtLang.ans2+(h?" + "+h+" "+b.OTxtLang.mois:"")+"<br/> "+b.OTxtLang.endettement+
" "+g+"%";b.label_BulleMensDuree.text=c;b.label_BulleMensDuree.maj();b.label_BullePret.text=Formatage_alto.FormatInteger(b.Donnees.pret)+" "+b.Monnaie;b.label_BullePret.maj()}}catch(j){trace("Paint Exception !"+j.toString())}}
function InitToolTipAide(b,c){var d,e;if(b.CodeNLS==2070){e="Esta ferramenta determina o montante m&aacute;ximo do empr&eacute;stimo que pode contrair, tendo em conta o seu rendimento mensal  e o prazo do empr&eacute;stimo.<br/><br/>Comece por introduzir o seu rendimento mensal, para que o programa possa determinar a mensalidade m&aacute;xima que pode assumir, normalmente limitada a 33% do rendimento.<br/><br/>";e+=ValueFromId(_s_alto.ID_TAUX_FIXE,_s_alto.TAB_ID_TAUX,b.TabTauxIsPresent)==1?"":"Introduza a taxa do empr&eacute;stimo.<br/><br/>";
e+="Poder&aacute; seleccionar e clicar nos gr&aacute;ficos para modificar a mensalidade, o prazo ou o montante do empr&eacute;stimo."}else if(b.CodeNLS==1040){e="Questa applicazione determina l'importo massimo di mutuo che potete chiedere tenuto conto del vostro stipendio mensile e della durata del mutuo.<br/><br/>Cominciate col inserire il vostro stipendio mensile, il programma calcoler&agrave; la rata massima che potete rimborsare, generalmente fissata al 33% dello stipendio.<br/><br/>";e+=ValueFromId(_s_alto.ID_TAUX_FIXE,
_s_alto.TAB_ID_TAUX,b.TabTauxIsPresent)==1?"Dopodich&eacute; inserite il tasso del prestito se lo conoscete.<br/>Senn&ograve; selezionare semplicemente il tipo di tasso scelto, fisso o variabile. Il programma stimer&agrave; automaticamente il tasso applicabile a seconda della durata del mutuo.<br/><br/>":"Dopodich&eacute; inserite il tasso del prestito.<br/><br/>";e+="Infine con il mouse cliccate sui grafici per modificare la rata, durata o importo totale del mutuo."}else if(b.CodeNLS==1033){e="This tool determines the maximum amount of the loan you can take out given your monthly income and the duration of the loan.<br/><br/>Begin by keying in your monthly income in order for the program to determine the maximum monthly repayment you can make, normally capped at 33 % of income.<br/><br/>";
e+=ValueFromId(_s_alto.ID_TAUX_FIXE,_s_alto.TAB_ID_TAUX,b.TabTauxIsPresent)==1?"Then, key in the rate of the loan if you know it.<br/>Otherwise, simply select the type of rate contemplated, either fixed or adjustable. The program will then automatically estimate the applicable rate according to the duration of the loan.<br/><br/>":"Then, key in the rate of the loan.<br/><br/>";e+="Lastly, use your mouse on one or the other of the graphs to change the monthly payment, the duration or the amount of the loan."}else{e=
"Cet outil d&eacute;termine le montant maximum du pr&ecirc;t que vous pouvez emprunter compte tenu de votre revenu mensuel et de la dur&eacute;e du pr&ecirc;t.<br/><br/>Commencez par saisir votre revenu mensuel, afin que le programme d&eacute;termine la mensualit&eacute; maximale que vous pouvez rembourser, normalement plafonn&eacute;e &agrave; 33% du revenu.<br/><br/>";e+=ValueFromId(_s_alto.ID_TAUX_FIXE,_s_alto.TAB_ID_TAUX,b.TabTauxIsPresent)==1?"Ensuite, Saisissez le taux du pr&ecirc;t si vous le connaissez.<br/>Sinon, s&eacute;lectionnez simplement le type de taux envisag&eacute;, fixe ou r&eacute;visable. Le programme estimera alors automatiquement le taux applicable en fonction de la dur&eacute;e du pr&ecirc;t.<br/><br/>":
"Ensuite, saisissez le taux de votre pr&ecirc;t.<br/><br/>";e+="Enfin, utilisez votre souris sur l'un ou l'autre des graphiques pour modifier la mensualit&eacute;, la dur&eacute;e, ou le montant du pret."}if(b.IsHideHelp==false){d=new AltoTextFormat(b.PoliceStd,11);d.align="justify";b.PanelToolTipAide=new AltoPanelToolTip(b,c,"PanelToolTipAide",1E3+b.iComp++,100,40,375,215,e,d);c.PanelToolTipAide._x=c.iImgAide1._x-c.PanelToolTipAide._width-4;c.PanelToolTipAide._y=c.iImgAide1._y+10}}
function setAideActivate(b,c){if(b.IsDeuxImgAide){b._mc.iImgAide1._visible=!c;b._mc.iImgAide2._visible=c;b._mc.iImgAide1.maj();b._mc.iImgAide2.maj()}b.PanelToolTipAide.setVisible(c);b.IsAideActivate=c}
function CalculUnitePixelYecartGraduation(b){var c,d;b.Donnees.mensualiteMax=Math.floor(0.5*b.Donnees.revenu);d=10;for(c=0;;c++){if(b.Donnees.mensualiteMax<=d*8)break;d*=c%2!=0?2.5:2}for(b.UnitePixelY=b.Donnees.mensualiteMax/(_s_alto.TAILLE_AXE_Y-5);Math.floor(b.Donnees.mensualiteMax/b.UnitePixelY)>_s_alto.TAILLE_AXE_Y-5;)b.UnitePixelY+=0.5;return d}
function CalculUnitePixelXecartGraduation(b){var c,d;d=12;for(c=0;;c++){if(b.Donnees.dureeMax<=d*12)break;d*=c%2!=0?2.5:2}for(b.UnitePixelX=b.Donnees.dureeMax/(_s_alto.TAILLE_AXE_X-5);Math.floor(b.Donnees.dureeMax/b.UnitePixelX)>_s_alto.TAILLE_AXE_X-5;)b.UnitePixelX+=0.5;return d}
function GraduationHorizontale(b,c,d){var e,f,h,g,j,i;i=CalculUnitePixelXecartGraduation(b);e=new AltoTextFormat("ARIAL",9);e.align="center";e.color=b.ColorAxeGraduation;d.mcGradHorizDuree.removeMovieClip();d.InitmcGradHorizDuree.duplicateMovieClip(b,"mcGradHorizDuree",b.iComp++);d.mcGradHorizDuree._height=b.APPLET_DIMENSION.height-10;d.mcGradHorizDuree.div.height=b.APPLET_DIMENSION.height-10;j=Math.floor(b.Donnees.dureeMax/i);for(h=1;h<=j;h++){g=h*i/12;f=Math.round(c.x+h*i/b.UnitePixelX);Util_alto.drawLine(b,
d.mcGradHorizDuree,f,c.y+4,f,c.y+1,b.ColorAxeGraduation);Util_alto.drawString(b,d.mcGradHorizDuree,b.iComp++,Formatage_alto.FormatInteger(g),f-10,c.y+4,21,b.LabelH1,e)}if(b.Donnees.dureeMax<=360){j=Math.floor(b.Donnees.dureeMax/12);i=i/b.UnitePixelX/(i/12);for(h=1;h<j;h++){g=i*h;f=Math.round(c.x+g);Util_alto.drawLine(b,d.mcGradHorizDuree,f,c.y+3,f,c.y+1,b.ColorAxeGraduation)}}e.align="left";Util_alto.drawString(b,d,b.iComp++,"0",b.PointOrigine_Mens.x-10,b.PointOrigine_Mens.y-2,100,20,e)}
function GraduationVerticale(b,c,d){var e,f,h,g,j,i;i=CalculUnitePixelYecartGraduation(b);if(b.Donnees.mensualite>b.Donnees.mensualiteMax){b.Donnees.mensualite=b.Donnees.mensualiteMax;if(!b.IsHideBottomTextBox){d.textField_mensualite.text=Formatage_alto.FormatInteger(b.Donnees.mensualite);d.textField_mensualite.maj()}CalculPretFromMensualDuree(b)}b.RevenuPourcentageGraphique=Math.floor(b.Donnees.revenu/3/b.UnitePixelY)+1;b.Barre33PC=b.PointOrigine_Mens.y-b.RevenuPourcentageGraphique;e=new AltoTextFormat("ARIAL",
9);e.align="right";e.color=b.ColorAxeGraduation;d.mcGradVertMens.removeMovieClip();d.InitmcGradVertMens.duplicateMovieClip(b,"mcGradVertMens",b.iComp++);j=Math.floor(b.Donnees.mensualiteMax/i);for(h=1;h<=j;h++){g=h*i;f=Math.round(c.y-h*i/b.UnitePixelY);Util_alto.drawLine(b,d.mcGradVertMens,c.x-3,f,c.x-1,f,b.ColorAxeGraduation);Util_alto.drawString(b,d.mcGradVertMens,b.iComp++,Formatage_alto.FormatInteger(g)+" "+b.Monnaie,c.x-b.LabelW1-4,f-8,b.LabelW1,b.LabelH1,e)}}
function CalculUnitePixelPretEcartGraduation(b){var c,d;CalculPretMin(b);CalculPretMax(b);d=10;for(c=0;;c++){if(b.Donnees.pretMax<=d*8)break;d*=d==500||d==5E4?c%2==0?2.5:2:c%2!=0?2.5:2}for(b.UnitePixelPret=b.Donnees.pretMax/(_s_alto.TAILLE_AXE_Y_PRET-5);Math.floor(b.Donnees.pretMax/b.UnitePixelPret)>_s_alto.TAILLE_AXE_Y_PRET-5;)b.UnitePixelPret+=0.5;return d}
function GraduationVerticalePret(b){var c,d,e,f,h,g=b._mc,j;f=CalculUnitePixelPretEcartGraduation(b);c=new AltoTextFormat("ARIAL",9);c.align="right";c.color=b.ColorAxeGraduation;g.mcGradVertPret.removeMovieClip();g.InitmcGradVertPret.duplicateMovieClip(b,"mcGradVertPret",b.mcGradVertPretDepth);h=Math.floor(b.Donnees.pretMax/f);for(j=0;j<=h;j++){e=j*f;d=Math.floor(b.PointOrigine_Mens.y-j*f/b.UnitePixelPret);Util_alto.drawLine(b,g.mcGradVertPret,b.RectPret.x-3,d,b.RectPret.x-1,d);Util_alto.drawString(b,
g.mcGradVertPret,null,Formatage_alto.FormatInteger(e)+" "+b.Monnaie,b.RectPret.x-b.LabelW1-4,d-8,b.LabelW1,b.LabelH1,c)}}
function CalculPretFromMensualDuree(b,c,d,e){if(typeof c=="undefined"){d=b.Donnees.taux/1200;if(b.Donnees.mensualite<2)b.Donnees.mensualite=2;CalculPretFromMensualDuree(b,b.Donnees.duree,b.Donnees.mensualite,d);if(!b.IsHideBottomTextBox){b._mc.textField_pret.text=Formatage_alto.FormatInteger(b.Donnees.pret);b._mc.textField_pret.maj()}}else{c=Math.pow(1+e,-c);b.Donnees.pret=Math.round(d*(1-c)/e)}}
function ImportationTauxFixeRev(b,c,d,e,f){var h,g,j;for(j=1;j<=20;j++){h=c[f]["t"+j];if(h==null){e.NbPlageTaux=j-1;break}g=h[0];h=h[1];e.tabTranche[j-1]=g;e.tabTaux[j-1]=h}if(e.NbPlageTaux!=0){SetValueId(d,1,_s_alto.TAB_ID_TAUX,b.TabTauxIsPresent);b.IsTauxUnique=0}}
function CalculPretMaxTrancheTaux(b,c){var d,e,f;for(f=b.Donnees.pretMax=0;f<c.NbPlageTaux;f++){d=c.tabTaux[f]/1200;e=c.tabTranche[f];if(e==0)e=b.Donnees.dureeMax;e=Math.pow(1+d,-e);d=Math.floor(b.Donnees.mensualiteMax*(1-e)/d);if(b.Donnees.pretMax<d)b.Donnees.pretMax=d}}
function CalculPretMax(b){if(b.TypeTaux==_s_alto.ID_TAUX_FIXE)CalculPretMaxTrancheTaux(b,b.TabTauxFixe);else if(b.TypeTaux==_s_alto.ID_TAUX_REV)CalculPretMaxTrancheTaux(b,b.TabTauxVariable);else if(b.TypeTaux==_s_alto.ID_TAUX_CHOISI){var c,d;c=b.Donnees.taux/100/12;d=Math.pow(1+c,-b.Donnees.dureeMax);b.Donnees.pretMax=Math.floor(b.Donnees.mensualiteMax*(1-d)/c)}if(b.Donnees.pretPlafond>0&&b.Donnees.pretMax>b.Donnees.pretPlafond)b.Donnees.pretMax=b.Donnees.pretPlafond}
function CalculPretMin(b){var c=b.Donnees.taux/100/12,d=Math.pow(1+c,-b.Donnees.dureeMin);b.Donnees.pretMin=Math.round(b.Donnees.mensualiteMin*(1-d)/c)}function PaintGraphFond(b,c,d,e,f,h){Util_alto.PaintRect(b,c,d,e,f,h,_g_alto.ColorGraphContour,_g_alto.ColorGraphBG)}
function PaintGraphTextfieldFond(b,c,d,e){Util_alto.PaintRect(b,c,d,_g_alto.PointOrigine_Mens.y+40,_s_alto.IsIE&&document.compatMode!="CSS1Compat"?e+2:e,_s_alto.IsIE&&document.compatMode!="CSS1Compat"?31:29,_g_alto.ColorCadreBorder,_g_alto.ColorCadre)}
function PaintGraphEncadrement(b,c){var d;PaintGraphFond(b,c,b.RectMens.x-1,b.PointOrigine_Mens.y-_s_alto.TAILLE_AXE_Y-8,_s_alto.TAILLE_AXE_X+8,_s_alto.TAILLE_AXE_Y+8-_s_alto.bw);Util_alto.drawLine(b,c,b.MargeGauche_Mens-1,_s_alto.MARGE_HAUT-8,b.PointOrigine_Mens.x-1,b.PointOrigine_Mens.y+1,b.ColorAxeGraduation);Util_alto.drawLine(b,c,b.PointOrigine_Mens.x,b.PointOrigine_Mens.y,_s_alto.TAILLE_AXE_X+b.MargeGauche_Mens+7+_s_alto.bw*2,_s_alto.TAILLE_AXE_Y+_s_alto.MARGE_HAUT,b.ColorAxeGraduation);if(!b.IsHideLabels){b.iComp+=
2E3;d=new AltoTextFormat(b.PoliceStd,11);d.color=b.ColorNomGraph;d.align="center";Util_alto.drawString(b,c,b.iComp++,b.OTxtLang.pret2,b.RectPret.x,_s_alto.MARGE_HAUT-5,b.RectPret.width,b.LabelH1+15,d)}PaintGraphFond(b,c,b.RectPret.x-1,b.PointOrigine_Mens.y-_s_alto.TAILLE_AXE_Y_PRET-8,_s_alto.TAILLE_AXE_X_PRET-_s_alto.bw,_s_alto.TAILLE_AXE_Y_PRET+8-_s_alto.bw);Util_alto.drawLine(b,c,b.RectPret.x-1,b.PointOrigine_Mens.y,b.RectPret.x-1,b.PointOrigine_Mens.y-_s_alto.TAILLE_AXE_Y_PRET-8,b.ColorAxeGraduation);
Util_alto.drawLine(b,c,b.RectPret.x+_s_alto.TAILLE_AXE_X_PRET-1,b.PointOrigine_Mens.y,b.RectPret.x+_s_alto.TAILLE_AXE_X_PRET-1,b.PointOrigine_Mens.y-_s_alto.TAILLE_AXE_Y_PRET-8,b.ColorAxeGraduation);Util_alto.drawLine(b,c,b.RectPret.x,b.PointOrigine_Mens.y,b.RectPret.x+_s_alto.TAILLE_AXE_X_PRET,b.PointOrigine_Mens.y,b.ColorAxeGraduation)}
function MajRect(b){b.RectMens.width=Math.floor(b.Donnees.duree/b.UnitePixelX);b.RectMens.height=Math.round(b.Donnees.mensualite/b.UnitePixelY);b.RectMens.y=_s_alto.MARGE_HAUT+_s_alto.TAILLE_AXE_Y-b.RectMens.height;if(b.RectMens.height==0)b.RectMens.height=1;b.BulleMensCoord.x=b.RectMens.x+b.RectMens.width+11;b.BulleMensCoord.y=b.RectMens.y+3;if(b.Donnees.mensualite<=_s_alto.BULLE_X_HAUTEUR_MIN*b.UnitePixelY)b.BulleMensCoord.y=b.PointOrigine_Mens.y-_s_alto.BULLE_X_HAUTEUR_MIN+3;b.RectPret.height=
Math.round(b.Donnees.pret/b.UnitePixelPret)+1;b.RectPret.y=_s_alto.MARGE_HAUT+_s_alto.TAILLE_AXE_Y_PRET-b.RectPret.height;b.BullePretCoord.y=b.RectPret.y-35}function Arrondir(b,c){if(c==_s_alto.ZCLIC_F_MENS_HAUT||c==_s_alto.ZCLIC_F_MENS_DIAG)b.Donnees.mensualite-=b.Donnees.mensualite%5;if(c==_s_alto.ZCLIC_F_PRET_HAUT)b.Donnees.pret=Math.round(b.Donnees.pret/1E3)*1E3}
function InterfaceEnabled(b,c,d){Util_alto.setEnable(c.textField_pret,d,b.ColorDisabled);Util_alto.setEnable(c.textField_mensualite,d,b.ColorDisabled);Util_alto.setEnable(c.textField_duree_an,d,b.ColorDisabled);Util_alto.setEnable(c.textField_duree_mois,d,b.ColorDisabled)}
function TauxModifiable(b,c){if(b.UrlTrameFondEcran&&!b.IsTauxUnique&&b.IsFieldsWithoutBorder)b._mc.mcCacheTextFieldTaux._visible=!c;b._mc.textField_taux._visible=c;b._mc.textField_taux.maj();b.label_taux_unite._visible=c;b.label_taux_unite.maj();b.label_taux._visible=!c;b.label_taux.maj()}
function ChangementTauxTrancheTaux(b,c){var d=0,e;TauxModifiable(b,false);for(e=c.NbPlageTaux;d<e-1&&c.tabTranche[d]<b.Donnees.duree;)d++;b.Donnees.taux=c.tabTaux[d];b.label_taux.text=Formatage_alto.FormatFloat(b.Donnees.taux)+" %";b.label_taux.maj()}
function RemplissageTextField_duree(b){b.textField_duree_an.text=Math.floor(_g_alto.Donnees.duree/_s_alto.UNITE_PIXEL_X);_g_alto._mc.textField_duree_an.maj();b.textField_duree_mois.text=Math.floor(_g_alto.Donnees.duree-Math.floor(_g_alto.Donnees.duree/_s_alto.UNITE_PIXEL_X)*_s_alto.UNITE_PIXEL_X);_g_alto._mc.textField_duree_mois.maj()}
function ChangementTaux(b,c){if(b.IsTauxUnique==0){b.TypeTaux=b.NbTypeTaux<2?b.DefaultTypeTaux:IdFromValue(b.choice_taux.getSelectedItem(),_s_alto.TAB_ID_TAUX,b.TabValTaux);if(b.TypeTaux==_s_alto.ID_TAUX_FIXE)ChangementTauxTrancheTaux(b,b.TabTauxFixe);else if(b.TypeTaux==_s_alto.ID_TAUX_REV)ChangementTauxTrancheTaux(b,b.TabTauxVariable);else if(b.TypeTaux==_s_alto.ID_TAUX_CHOISI){var d=c.textField_taux.text.charAt(c.textField_taux.text.length-1);TauxModifiable(b,true);b.Donnees.taux=Formatage_alto.FloatFromFormatFloat(c.textField_taux.text);
c.textField_taux.text=Formatage_alto.FormatFloat(b.Donnees.taux)+(d=="."||d==","?",":"");c.textField_taux.maj()}else trace("ChangementTaux erreur : g.TypeTaux trouv\ufffd non r\ufffdf\ufffdrenc\ufffd")}else{d=c.textField_taux.text.charAt(c.textField_taux.text.length-1);b.Donnees.taux=Formatage_alto.FloatFromFormatFloat(c.textField_taux.text);c.textField_taux.text=Formatage_alto.FormatFloat(b.Donnees.taux)+(d=="."||d==","?",":"");c.textField_taux.maj()}}
function CalculModifPret(b,c){if(c){CalculMensualite(b);if(b.Donnees.mensualite>=Math.floor(b.Donnees.revenu/3)&&b.Donnees.duree<b.Donnees.dureeMaxAvantMensualite)CalculDureeLimiteRevenu(b);else b.Donnees.mensualite>=Math.floor(b.Donnees.revenu/3)&&b.Donnees.duree<b.Donnees.dureeMax?CalculDuree(b,c,true):CalculMensualite(b)}else b.Donnees.mensualite<=Math.floor(b.Donnees.revenu/3)&&b.Donnees.duree>b.Donnees.dureeMin?CalculDuree(b,c,true):CalculMensualite(b)}
function CalculDureeLimiteRevenu(b){try{var c=b._mc,d=b.Donnees.taux/1200,e=b.Donnees.duree;do{e+=b.PasNbMois;if(e>=b.Donnees.dureeMaxAvantMensualite){e=b.Donnees.dureeMaxAvantMensualite;break}}while(b.Donnees.revenu/3*(1-Math.pow(1+d,-e))/d<b.Donnees.pret);b.Donnees.duree=e;ChangementTaux(b,c);CalculMensualite(b);b.Donnees.mensualite>Math.floor(b.Donnees.revenu/3)&&e<b.Donnees.dureeMaxAvantMensualite&&CalculDureeLimiteRevenu(b)}catch(f){AltoUtil.dtrace("calculDureeLimiteRevenu exception : "+f.toString())}}
function CalculDuree(b,c,d,e){try{var f=b._mc,h=b.Donnees.taux/1200,g=b.Donnees.duree;if(c){do{g+=b.PasNbMois;if(g>b.Donnees.dureeMax){g=b.Donnees.dureeMax;break}}while(b.Donnees.mensualite*(1-Math.pow(1+h,-g))/h<b.Donnees.pret);if(d&&g>b.Donnees.dureeMaxAvantMensualite&&b.Donnees.mensualite<b.Donnees.mensualiteMax)g=b.Donnees.dureeMaxAvantMensualite;else if(g>b.Donnees.dureeMax)g=b.Donnees.dureeMax}else{if(b.IsFixeMontantPret!=1||d==true)b.Donnees.mensualite=Math.floor(b.Donnees.revenu/3);for(g=
b.Donnees.dureeMin;;g+=b.PasNbMois){if(g>=b.Donnees.dureeMax){g=b.Donnees.dureeMax;b.Donnees.duree=b.Donnees.dureeMax;break}if(b.Donnees.mensualite*(1-Math.pow(1+h,-g))/h>=b.Donnees.pret)break}}b.Donnees.duree=g;ChangementTaux(b,f);CalculMensualite(b)}catch(j){AltoUtil.dtrace("calculDuree exception : "+j.toString())}}
function CalculMensualite(b){var c=b._mc;try{var d=b.Donnees.taux/1200,e=Math.pow(1+d,-b.Donnees.duree);b.Donnees.mensualite=Math.floor(b.Donnees.pret*d/(1-e));if(b.Donnees.mensualite<b.Donnees.mensualiteMin)b.Donnees.mensualite=b.Donnees.mensualiteMin;else if(b.Donnees.mensualite>b.Donnees.mensualiteMax)b.Donnees.mensualite=b.Donnees.mensualiteMax;if(!b.IsHideBottomTextBox){c.textField_mensualite.text=Formatage_alto.FormatInteger(b.Donnees.mensualite);c.textField_mensualite.maj()}}catch(f){AltoUtil.dtrace("calculMensualite exception : "+
f.toString())}}
function IsDebordementPret(b,c){if(b.Donnees.pret>=b.Donnees.pretMax){b.Donnees.pret=b.Donnees.pretMax;if(b.Donnees.pretMax!=b.Donnees.pretPlafond){b.Donnees.duree=b.Donnees.dureeMax;b.Donnees.mensualite=b.Donnees.mensualiteMax}else return true}else if(b.Donnees.pret<=b.Donnees.pretMin){b.Donnees.pret=b.Donnees.pretMin;b.Donnees.duree=b.Donnees.dureeMin;b.Donnees.mensualite=b.Donnees.mensualiteMin}if(b.Donnees.pret==b.Donnees.pretMax||b.Donnees.pret==b.Donnees.pretMin){if(!b.IsHideBottomTextBox){c.textField_mensualite.text=Formatage_alto.FormatInteger(b.Donnees.mensualite);
c.textField_duree_an.text=Math.floor(b.Donnees.duree/12);c.textField_duree_mois.text="0";c.textField_mensualite.maj();c.textField_duree_an.maj();c.textField_duree_mois.maj()}return true}else return false}function SetValueId(b,c,d,e){var f;for(f=0;f<d.length;f++)if(d[f]==b)break;e[f]=c}function ValueFromId(b,c,d){var e;for(e=0;e<c.length;e++)if(c[e]==b)break;return d[e]}function IdFromValue(b,c,d){var e;for(e=0;e<d.length;e++)if(d[e]==b)break;return c[e]}
function TransfertDonneesOldDonnees(b,c){var d=c?b.Donnees:b.OldDonnees;b=!c?b.Donnees:b.OldDonnees;b.duree=d.duree;b.mensualite=d.mensualite;b.pret=d.pret}function trace(b){self.alert(b)}function isTouchDevice(){return!!("ontouchstart"in window)}
function iniOnData(b,c){var d=b.NbMoisMaxi;if(c!=null)OCalcFinIni=c;if(typeof OCalcFinIni!="undefined"){var e,f;c=OCalcFinIni.General;var h=OCalcFinIni.Design;f=OCalcFinIni.Couleur;b.NbTypeTaux=0;e=c.IsPretToMensDuree;if(typeof e!="undefined"&&e!=null){if(e==true||e==1){b.IsPretToMensDuree=1;b.IsFixeMontantPret=1}}else trace("Erreur ou donn\ufffde manquante : fichierIni - General - IsPretToMensDuree");e=c.IsFixeMontantPret;if(typeof e!="undefined"&&e!=null)if(e==true||e==1)b.IsFixeMontantPret=1;e=
c.NbMoisMaxi;if(typeof e!="undefined"&&e!=null)d=parseInt(e,10);e=c.NbMoisMini;if(typeof e!="undefined"&&e!=null){e=parseInt(e,10);if(e>=b.Donnees.dureeMin&&e<=b.Donnees.dureeMax)b.Donnees.dureeMin=e;if(b.Donnees.duree<b.Donnees.dureeMin)b.Donnees.duree=b.Donnees.dureeMin}e=c.NbMoisDefaut;if(typeof e!="undefined"&&e!=null){b.Donnees.duree=parseInt(e,10);if(b.Donnees.duree>b.Donnees.dureeMax)b.Donnees.duree=b.Donnees.dureeMax;if(b.Donnees.duree<b.Donnees.dureeMin)b.Donnees.duree=b.Donnees.dureeMin}e=
c.NbMoisMaxAvtMens;if(typeof e!="undefined"&&e!=null){b.Donnees.dureeMaxAvantMensualite=parseInt(e,10);if(b.Donnees.dureeMaxAvantMensualite<b.Donnees.duree)b.Donnees.dureeMaxAvantMensualite=b.Donnees.duree;if(b.Donnees.dureeMaxAvantMensualite>b.Donnees.dureeMax)b.Donnees.dureeMaxAvantMensualite=b.Donnees.dureeMax}e=c.PasNbMois;if(typeof e!="undefined"&&e!=null){b.PasNbMois=parseInt(e,10);if(b.PasNbMois<1||b.PasNbMois>240)b.PasNbMois=1}e=c.RevenuDefaut;if(typeof e!="undefined"&&e!=null){b.root._RevenuOnLoad=
parseInt(e,10);if(b.root._RevenuOnLoad>b.Donnees.revenuMax)b.root._RevenuOnLoad=b.Donnees.revenuMax;if(b.root._RevenuOnLoad<b.Donnees.revenuMin)b.root._RevenuOnLoad=b.Donnees.revenuMin}e=c.PretMaxi;if(typeof e!="undefined"&&e!=null)b.Donnees.pretPlafond=parseInt(e,10);e=c.DefaultTauxSaisi;if(typeof e!="undefined"&&e!=null)b.Donnees.taux=e;e=c.CanSelectTF;if(typeof e!="undefined"&&e!=null)if(e==1){ImportationTauxFixeRev(b,OCalcFinIni,_s_alto.ID_TAUX_FIXE,b.TabTauxFixe,"BaremeTauxFixe");b.NbTypeTaux++}e=
c.CanSelectTR;if(typeof e!="undefined"&&e!=null)if(e==1){ImportationTauxFixeRev(b,OCalcFinIni,_s_alto.ID_TAUX_REV,b.TabTauxVariable,"BaremeTauxRevisable");b.NbTypeTaux++}e=c.Monnaie;if(e!=null&&e!="null"&&e.length>0)b.Monnaie=e=="livre"?"\ufffd":e=="dollar"?"$":"&euro;";e=h.UrlTrameFondEcran;if(e!=null&&e!="null"&&e.length>0)b.UrlTrameFondEcran=e;e=h.IsHideBottomTextBox;if(typeof e!="undefined"&&e!=null)if(e==true||e==1)b.IsHideBottomTextBox=true;e=h.IsHideLabels;if(typeof e!="undefined"&&e!=null)if(e==
true||e==1)b.IsHideLabels=true;e=h.IsHideHelp;if(typeof e!="undefined"&&e!=null)if(e==true||e==1)b.IsHideHelp=true;e=h.IsFieldsWithoutBorder;if(typeof e!="undefined"&&e!=null)if(e==true||e==1)b.IsFieldsWithoutBorder=true;e=h.BtnCalcul_UrlImageHaut;if(e!=null&&e!="null"&&e.length>0)b.BtnCalcul_UrlImageHaut=e;e=h.BtnCalcul_UrlImageBas;if(e!=null&&e!="null"&&e.length>0)b.BtnCalcul_UrlImageBas=e;e=h.BtnAide_UrlImageHaut;if(e!=null&&e!="null"&&e.length>0)b.BtnAide_UrlImageHaut=e;e=h.BtnAide_UrlImageBas;
if(e!=null&&e!="null"&&e.length>0)b.BtnAide_UrlImageBas=e;e=h.TaillePoignees;if(e!=null&&(e=="1"||e=="2"||e=="3"||e=="4"))b.TaillePoignees=parseInt(e,10);e=c.Flag1;if(typeof e!="undefined"&&e!=null)if(e=="0x01")b.IsCopyright=false;e=c.CodeNLS;if(typeof e!="undefined"&&e!=null)b.CodeNLS=parseInt(e,10);e=f.ColorBG;if(typeof e!="undefined"&&e!=null)b.ColorBG=Util_alto.getHtmlColor(e);e=f.ColorGraphBG;if(typeof e!="undefined"&&e!=null)b.ColorGraphBG=Util_alto.getHtmlColor(e);e=f.ColorGraphContour;if(typeof e!=
"undefined"&&e!=null)b.ColorGraphContour=Util_alto.getHtmlColor(e);e=f.ColorBorder;if(typeof e!="undefined"&&e!=null)b.ColorBorder=e=="none"?null:Util_alto.getHtmlColor(e);e=f.ColorCadre;if(typeof e!="undefined"&&e!=null)b.ColorCadre=Util_alto.getHtmlColor(e);e=f.ColorCadreBorder;if(typeof e!="undefined"&&e!=null)b.ColorCadreBorder=Util_alto.getHtmlColor(e);e=f.ColorLabel;if(typeof e!="undefined"&&e!=null)b.ColorLabel=Util_alto.getHtmlColor(e);e=f.ColorFieldText;if(typeof e!="undefined"&&e!=null)b.ColorFieldText=
Util_alto.getHtmlColor(e);e=f.ColorFieldBorder;if(typeof e!="undefined"&&e!=null)b.ColorFieldBorder=Util_alto.getHtmlColor(e);e=f.ColorDisabled;if(typeof e!="undefined"&&e!=null)b.ColorDisabled=Util_alto.getHtmlColor(e);e=f.ColorAxeGraduation;if(typeof e!="undefined"&&e!=null)b.ColorAxeGraduation=Util_alto.getHtmlColor(e);e=f.ColorMensInf33PC;if(typeof e!="undefined"&&e!=null)b.ColorMensInf33PC=Util_alto.getHtmlColor(e);e=f.ColorMensSupp33PC;if(typeof e!="undefined"&&e!=null)b.ColorMensSupp33PC=Util_alto.getHtmlColor(e);
e=f.ColorPret;if(typeof e!="undefined"&&e!=null)b.ColorPret=Util_alto.getHtmlColor(e);e=f.Color33PC;if(typeof e!="undefined"&&e!=null)b.Color33PC=Util_alto.getHtmlColor(e);e=f.ColorContourPoignees;if(typeof e!="undefined"&&e!=null)b.ColorContourPoignees=Util_alto.getHtmlColor(e);e=f.ColorBulle;if(typeof e!="undefined"&&e!=null)b.ColorBulle=Util_alto.getHtmlColor(e);e=f.ColorBtnCalculBG;if(typeof e!="undefined"&&e!=null)b.ColorBtnCalculBG=Util_alto.getHtmlColor(e);e=f.ColorBtnCalculText;if(typeof e!=
"undefined"&&e!=null)b.ColorBtnCalculText=Util_alto.getHtmlColor(e);e=c.DefaultTypeTaux;if(typeof e!="undefined"&&e!=null)b.DefaultTypeTaux=parseInt(e,10);if(b.IsTauxUnique==0){h=b.DefaultTypeTaux?0:1;f=false;e=c.CanSelectTS;if(typeof e!="undefined"&&e!=null)if(e==true||e==1){f=true;b.NbTypeTaux++}if(!f)for(c=e=0;c<b.TabTauxIsPresent.length;c++){b.TabTauxIsPresent[c]==1&&e++;if(e==2){SetValueId(_s_alto.ID_TAUX_CHOISI,0,_s_alto.TAB_ID_TAUX,b.TabTauxIsPresent);break}}for(c=0;c<b.TabTauxIsPresent.length;c++)if(b.TabTauxIsPresent[c]==
1&&_s_alto.TAB_ID_TAUX[c]==b.DefaultTypeTaux)h=1;if(h==0){trace("Taux par d\ufffdfaut non trait\ufffd [DefaultTypeTaux] !");return 0}}}else b.IsTauxUnique=1;if(d>=b.Donnees.dureeMin&&d<=b.Donnees.dureeMax)b.Donnees.dureeMax=d;if(b.Donnees.duree>b.Donnees.dureeMax)b.Donnees.duree=b.Donnees.dureeMax;if(b.Donnees.dureeMaxAvantMensualite>b.Donnees.dureeMax)b.Donnees.dureeMaxAvantMensualite=b.Donnees.dureeMax;init(b,b._mc)}
function init(b,c){var d,e,f,h,g,j;b.fontDialog.leftMargin=2;b.fontDialog.rightMargin=2;b.fontDialog.align="center";b.fontDialog.color=b.ColorFieldText;b.fontLabel.color=b.ColorLabel;b.SizePoignee=b.TaillePoignees==1?8:b.TaillePoignees==2?10:b.TaillePoignees==3?12:16;if(_s_alto.IsEcranTactile){b.EcartPoigneeVisible=22-b.SizePoignee;b.SizePoignee+=b.EcartPoigneeVisible}c._quality="HIGH";document.onmousemove=this_mouseMove;document.onmousedown=this_mouseDown;document.onmouseup=this_mouseUp;if(!_s_alto.IsIE){document.addEventListener("touchstart",
touchHandler,false);document.addEventListener("touchmove",touchHandler,false);document.addEventListener("touchend",touchHandler,false);document.addEventListener("touchcancel",touchHandler,false)}if(b.IsHideBottomTextBox)b.APPLET_DIMENSION.height-=70;if(b.IsPretToMensDuree){b.MargeGauche_Mens=216;b.MargeGauche_Pret=60}b.PointOrigine_Mens=new AltoPoint(b.MargeGauche_Mens,_s_alto.TAILLE_AXE_Y+_s_alto.MARGE_HAUT);b.PointOrigine_Pret=new AltoPoint(b.MargeGauche_Pret,b.PointOrigine_Mens.y);b.x_PointOrigine_util=
new AltoPoint(b.PointOrigine_Mens.x+_s_alto.X_DIST_ORIGINE_DEBUT,b.PointOrigine_Mens.y);b.y_PointOrigine_util=new AltoPoint(b.PointOrigine_Mens.x,b.PointOrigine_Mens.y+_s_alto.Y_DIST_ORIGINE_DEBUT);b.TabX_FlecheAxe_Y=[b.MargeGauche_Mens-5,b.MargeGauche_Mens-1,b.MargeGauche_Mens+3];b.TabY_FlecheAxe_Y=[_s_alto.MARGE_HAUT,_s_alto.MARGE_HAUT-8,_s_alto.MARGE_HAUT];b.TabX_FlecheAxe_X=[_s_alto.TAILLE_AXE_X+b.MargeGauche_Mens,_s_alto.TAILLE_AXE_X+b.MargeGauche_Mens+8,_s_alto.TAILLE_AXE_X+b.MargeGauche_Mens];
b.TabY_FlecheAxe_X=[_s_alto.TAILLE_AXE_Y+_s_alto.MARGE_HAUT-4,_s_alto.TAILLE_AXE_Y+_s_alto.MARGE_HAUT,_s_alto.TAILLE_AXE_Y+_s_alto.MARGE_HAUT+4];b.TabX_FlecheAxe_Y_PRET=[b.MargeGauche_Pret-5,b.MargeGauche_Pret-1,b.MargeGauche_Pret+3];b.TabY_FlecheAxe_Y_PRET=[_s_alto.MARGE_HAUT,_s_alto.MARGE_HAUT-8,_s_alto.MARGE_HAUT];d=b.CodeNLS=="1049"?120:b.CodeNLS=="1033"?105:92;f=b.CodeNLS=="1049"?30:41;if(_s_alto.IsIE&&document.compatMode!="CSS1Compat"){d+=2;f+=2}b.BulleMensCoord=new AltoRectangle(0,0,d,f);b.BullePretCoord=
new AltoRectangle(b.MargeGauche_Pret+7,0,_s_alto.IsIE&&document.compatMode!="CSS1Compat"?66:64,_s_alto.IsIE&&document.compatMode!="CSS1Compat"?23:21);b.RectMens=new AltoRectangle(b.MargeGauche_Mens,0,0,0);b.RectPret=new AltoRectangle(b.MargeGauche_Pret,0,_s_alto.TAILLE_AXE_X_PRET-1,0);if(b.CodeNLS=="1033")b.TabValTaux=new Array("fixed rate","adjustable rate","limit adjustable rate","following rate :");else if(b.CodeNLS=="1040")b.TabValTaux=new Array("a tasso fisso","a tasso Variabile","a tasso Variabile Cape",
"al tasso seguente :");else if(b.CodeNLS=="2070")b.TabValTaux=new Array("a taxa fixa","a taxa ajust\ufffdvel","a taxa ajust\ufffdvel limitados","a taxa de :");else if(b.CodeNLS=="1049")b.TabValTaux=new Array("\u041f\u043e \u0441\u0442\u0430\u0432\u043a\u0435","\ufffd taux r\ufffdvisable","\ufffd taux r\ufffdv. Cap\ufffd","\u041f\u043e \u0444\u0438\u043a\u0441. \u0441\u0442\u0430\u0432\u043a\u0435");if(b.UrlTrameFondEcran){c.createEmptyMovieClip(b,"McContainer_Trame",b.iComp++);c.McContainer_Trame.loadMovie(b,
b.UrlTrameFondEcran);if(!b.IsTauxUnique&&b.IsFieldsWithoutBorder){c.createEmptyMovieClip(b,"mcCacheComboTaux",b.iComp++);d=c.mcCacheComboTaux;d._x=365;d._y=_s_alto.PADDING_TOP+6;Util_alto.PaintRect(b,mcTmp,0,0,128,24,null,b.ColorBG);c.createEmptyMovieClip(b,"mcCacheTextFieldTaux",b.iComp++);d=c.mcCacheTextFieldTaux;d._x=500;d._y=_s_alto.PADDING_TOP+6;d._visible=false;Util_alto.PaintRect(b,mcTmp,0,0,48,24,null,b.ColorBG)}}b.iComp+=50;if(b.IsHideHelp==false){if(b.BtnAide_UrlImageHaut||b.BtnAide_UrlImageBas){c.createEmptyMovieClip(b,
"iImgAide1",1E3);c.iImgAide1.loadMovie(b,b.BtnAide_UrlImageHaut?b.BtnAide_UrlImageHaut:b.BtnAide_UrlImageBas)}else c.attachMovie(b,"ImgAide1","iImgAide1",1E3);d=c.iImgAide1;d._x=446;d._y=b.IsFieldsWithoutBorder?12:14;d._width=19;d._height=19;d.useHandCursor=true;d.div.id="iImgAide1";d.div.onmousedown=function(){b.MouseGestion.IdDivPressed=b.DivId+"iImgAide1"};d.div.onmouseout=function(){b.MouseGestion.IdDivPressed=null};if(b.BtnAide_UrlImageHaut||b.BtnAide_UrlImageBas)if(!b.BtnAide_UrlImageHaut||
!b.BtnAide_UrlImageBas)b.IsDeuxImgAide=false;else{b.IsDeuxImgAide=true;c.createEmptyMovieClip(b,"iImgAide2",1001);c.iImgAide2.loadMovie(b,b.BtnAide_UrlImageBas?b.BtnAide_UrlImageBas:b.BtnAide_UrlImageHaut)}else b.IsDeuxImgAide&&c.attachMovie(b,"ImgAide2","iImgAide2",1001);if(b.IsDeuxImgAide){d=c.iImgAide2;d._x=c.iImgAide1._x;d._y=c.iImgAide1._y;d.useHandCursor=true}}if(b.IsCopyright){c.attachMovie(b,"ImgCopyright","iImgCopyright",1002);d=c.iImgCopyright;d._x=b.APPLET_DIMENSION.width-114;d._y=b.APPLET_DIMENSION.height-
(b.IsHideBottomTextBox?18:20);d._width=109;d._height=16;d.useHandCursor=true;d.div.style.overflow="hidden";d.div.onmousedown=function(){b.MouseGestion.IdDivPressed=b.DivId+"iImgCopyright"};d.div.onmouseout=function(){b.MouseGestion.IdDivPressed=null}}b.OTxtLang=_s_alto.ONLS["NLS"+b.CodeNLS];if(b.CodeNLS==2070||b.CodeNLS==1033)b.fontLabel=new AltoTextFormat("ARIAL",12);d=_s_alto.MARGE_GAUCHE-42;f=_s_alto.PADDING_TOP+6;h=f+2;b.IsHideLabels||Util_alto.drawString(b,c,b.iComp++,b.OTxtLang.revlib1,d,h,
150,b.LabelH1,b.fontLabel);d+=b.CodeNLS==2070?110:b.CodeNLS==1040?116:b.CodeNLS==1033?80:88;Util_alto.SetTextBox(b,c,"textField_revenu",1E3,d,f,52,b.TextBoxH,b.fontDialog,b.ColorFieldBorder,b.IsFieldsWithoutBorder?16:0);c.textField_revenu.input.onfocus=function(i){textField_focusGained(i,b)};c.textField_revenu.input.onchange=function(){textField_revenu_focusLost(b)};c.textField_revenu._gc_alto.TFContext.FlagFormat=TFFF_F1_INT;d+=55;if(!b.IsHideLabels){e=Util_alto.drawString(b,c,b.iComp++,b.Monnaie+
b.OTxtLang.revlib2,d,h,220,b.LabelH1,b.fontLabel);g=c[e];g._visible=false;e=Util_alto.drawString(b,c,b.iComp++,b.Monnaie+b.OTxtLang.revlib3,d,h,220,b.LabelH1,b.fontLabel);j=c[e]}d+=b.CodeNLS==1040?56:b.CodeNLS==1033?92:84;if(!b.IsTauxUnique&&b.NbTypeTaux>1){if(b.CodeNLS==1033)d+=35;e=new AltoTextFormat(b.PoliceStd,11);e.color=b.ColorFieldText;b.choice_taux=new AltoCCombo(b,c,"choice_taux",1E3+b.iComp++,d,f,(b.CodeNLS==1040?132:b.CodeNLS==1033?112:121)+2-_s_alto.bw*2,b.TextBoxH-_s_alto.bw*2,100,e,
b.ColorFieldBorder,b.IsFieldsWithoutBorder?16:0);b.choice_taux._mcChoix.div.onmousedown=function(i){choice_taux_mouseDown(i,b)};b.choice_taux._mcBtnChoix.div.onmousedown=function(i){choice_taux_mouseDown(i,b)};d+=10;if(b.CodeNLS==1040)d+=11;else if(b.CodeNLS==1033)d-=9}d+=b.CodeNLS==2070?97:119;if(b.UrlTrameFondEcran)d+=4;e=new AltoTextFormat(b.PoliceStd,12,0,true);e.color=b.ColorFieldText;e=Util_alto.drawString(b,c,b.iComp++,"",d+2,h,55,b.LabelH1,e);b.label_taux=c[e];Util_alto.SetTextBox(b,c,"textField_taux",
1E3,d,f,b.UrlTrameFondEcran?35:39,b.TextBoxH,b.fontDialog,b.ColorFieldBorder,b.IsFieldsWithoutBorder?16:0);c.textField_taux.input.onfocus=function(i){textField_focusGained(i,b)};c.textField_taux.input.onchange=function(){textField_taux_focusLost(b)};c.textField_taux._gc_alto.TFContext.FlagFormat=TFFF_F1_FLOAT;c.textField_taux._gc_alto.TFContext.size=2.2;c.textField_taux.text=Formatage_alto.FormatFloat(b.Donnees.taux);d+=b.UrlTrameFondEcran?37:41;b.IsHideLabels||(e=Util_alto.drawString(b,c,b.iComp++,
"%",d,h,20,b.LabelH1,b.fontLabel));b.label_taux_unite=c[e];if(!b.IsHideBottomTextBox){d=b.MargeGauche_Mens+5;f=_s_alto.MARGE_HAUT+206;Util_alto.SetTextBox(b,c,"textField_mensualite",1E3,d,f,51,b.TextBoxH,b.fontDialog,b.ColorFieldBorder,b.IsFieldsWithoutBorder?16:0);c.textField_mensualite.input.onfocus=function(i){textField_focusGained(i,b)};c.textField_mensualite.input.onchange=function(){textField_mensualite_focusLost(b)};c.textField_mensualite._gc_alto.TFContext.FlagFormat=TFFF_F1_INT;if(b.CodeNLS==
1033)b.fontLabel=new AltoTextFormat("ARIAL",10);d+=53;h=f+2;b.IsHideLabels||Util_alto.drawString(b,c,b.iComp++,b.Monnaie,d,h,12,b.LabelH1,b.fontLabel);d+=b.CodeNLS==1033?11:16;b.IsHideLabels||Util_alto.drawString(b,c,b.iComp++,b.OTxtLang.sur,d,h,28,b.LabelH1,b.fontLabel);d+=b.CodeNLS==2070?28:b.CodeNLS==1033?26:30;Util_alto.SetTextBox(b,c,"textField_duree_an",1E3,d,f,31,b.TextBoxH,b.fontDialog,b.ColorFieldBorder,b.IsFieldsWithoutBorder?16:0);c.textField_duree_an.input.onfocus=function(i){textField_focusGained(i,
b)};c.textField_duree_an.input.onchange=function(){textField_duree_an_focusLost(b)};c.textField_duree_an._gc_alto.TFContext.FlagFormat=TFFF_F1_INT;d+=33;b.IsHideLabels||Util_alto.drawString(b,c,b.iComp++,b.OTxtLang.ans,d,h,48,b.LabelH1,b.fontLabel);d+=b.CodeNLS==2070?42:49;Util_alto.SetTextBox(b,c,"textField_duree_mois",1E3,d,f,31,b.TextBoxH,b.fontDialog,b.ColorFieldBorder,b.IsFieldsWithoutBorder?16:0);c.textField_duree_mois.input.onfocus=function(i){textField_focusGained(i,b)};c.textField_duree_mois.input.onchange=
function(){textField_duree_mois_focusLost(b)};c.textField_duree_mois._gc_alto.TFContext.FlagFormat=TFFF_F1_INT;d+=34;b.IsHideLabels||Util_alto.drawString(b,c,b.iComp++,b.OTxtLang.mois,d,h,44,b.LabelH1,b.fontLabel);if(b.CodeNLS==1033)b.fontLabel=new AltoTextFormat("VERDANA",12);Util_alto.SetTextBox(b,c,"textField_pret",1E3,b.MargeGauche_Pret+6,f,61,b.TextBoxH,b.fontDialog,b.ColorFieldBorder,b.IsFieldsWithoutBorder?16:0);Util_alto.drawString(b,c,b.iComp++,b.Monnaie,b.MargeGauche_Pret+70,h,20,b.LabelH1,
b.fontLabel);c.textField_pret.input.onfocus=function(i){textField_focusGained(i,b)};c.textField_pret.input.onchange=function(){textField_pret_focusLost(b)};c.textField_pret._gc_alto.TFContext.FlagFormat=TFFF_F1_INT;e=new AltoTextFormat("ARIAL",b.CodeNLS==1049||b.CodeNLS==1033?10:12,b.ColorBtnCalculText,true);(new AltoCButton(b,c,"button_calculer",1E3,b.IsPretToMensDuree?b.MargeGauche_Pret+_s_alto.TAILLE_AXE_X_PRET+6:b.MargeGauche_Mens+_s_alto.TAILLE_AXE_X+16,_s_alto.MARGE_HAUT+204-(b.IsFieldsWithoutBorder?
1:0),62,22,b.OTxtLang.calcul,e,b.BtnCalcul_UrlImageHaut,b.BtnCalcul_UrlImageBas)).setBackgroundColor(b.ColorBtnCalculBG)}c.opaqueBackground=b.ColorBG;c.div.style.backgroundColor=AltoUtil.getHtmlColor(c.opaqueBackground);c.createEmptyMovieClip(b,"mcGraphEncadrement",b.iComp++);c.createEmptyMovieClip(b,"InitmcGradVertMens",b.iComp++);c.InitmcGradVertMens.duplicateMovieClip(b,"mcGradVertMens",b.iComp++);c.createEmptyMovieClip(b,"InitmcGradHorizDuree",b.iComp++);c.InitmcGradHorizDuree.duplicateMovieClip(b,
"mcGradHorizDuree",b.iComp++);c.createEmptyMovieClip(b,"InitmcGradVertPret",b.iComp++);b.mcGradVertPretDepth=b.iComp++;c.InitmcGradVertPret.duplicateMovieClip(b,"mcGradVertPret",b.mcGradVertPretDepth);c.createEmptyMovieClip(b,"mcRectMensDuree",b.iComp++);c.createEmptyMovieClip(b,"mcRectPret",b.iComp++);c.createEmptyMovieClip(b,"mcBarre33PC",b.iComp++);c.mcBarre33PC._visible=false;c.mcBarre33PC._x=b.PointOrigine_Mens.x;e=new AltoTextFormat(b.PoliceStd,11);e.color=b.Color33PC;Util_alto.drawString(b,
c.mcBarre33PC,b.iComp++,b.OTxtLang.PC33,_s_alto.TAILLE_AXE_X-(b.CodeNLS==1040?121:b.CodeNLS==2070?120:95),b.HmcBarre33PC-17,b.LabelW1+20,b.LabelH1,e);Util_alto.drawLine(b,c.mcBarre33PC,0,b.HmcBarre33PC,_s_alto.TAILLE_AXE_X-8,b.HmcBarre33PC,b.Color33PC);MkBulles(b,c);paint(b,c,_s_alto.ZONE_F_INIT_GRAPH);if(!b.IsHideLabels&&!b.IsHideBottomTextBox){e=Util_alto.drawString(b,c,b.iComp++,b.OTxtLang.VotMensual,b.MargeGauche_Mens+4,_s_alto.MARGE_HAUT+184,200,b.LabelH1-2,b.fontLabel);e=Util_alto.drawString(b,
c,b.iComp++,b.OTxtLang.pret1,b.MargeGauche_Pret+(b.CodeNLS==1033?-2:b.CodeNLS==1040?-3:1),_s_alto.MARGE_HAUT+184,90,b.LabelH1-2,b.fontLabel)}b.IsHideBottomTextBox||InterfaceEnabled(b,c,false);if(b.IsHideHelp==false){InitToolTipAide(b,c);setAideActivate(b,b.IsAideActivate)}if(b.IsCopyright){b.iComp+=20;e=new AltoTextFormat(b.PoliceStd,11);b.PanelToolTipCopyright=new AltoPanelToolTip(b,c,"PanelToolTipCopyright",1E3+b.iComp++,c.iImgCopyright._x-150,c.iImgCopyright._y-105,240,105);b.PanelToolTipCopyright.setMarge(29);
b.PanelToolTipCopyright.setNewTextFormat(e);b.PanelToolTipCopyright.setText("Tour Maine-Montparnasse<br/>33 avenue du Maine<br/>75015 PARIS<br/>t&eacute;l : 01 43 35 49 18<br/>email : contact@alto-informatique.com");b.PanelToolTipCopyright.paint(b);d=c.PanelToolTipCopyright;e=new AltoTextFormat(b.PoliceStd,13,96);d.createTextField(b,"tt_txt2",1E3+b.iComp++,28,7,150,20);d.tt_txt2.setNewTextFormat(e);d.tt_txt2.text="alto informatique";d.attachMovie(b,"ImgLogoAlto","iImgLogoAlto",1E3+b.iComp++);d=d.iImgLogoAlto;
d._x=5;d._y=5}if(b.IsTauxUnique==1){b.label_taux._visible=false;if(j){j._visible=false;j.maj()}b.choice_taux&&b.choice_taux.setVisible(false);if(g){g._visible=true;g.maj()}}else{if(b.UrlTrameFondEcran&&!b.IsTauxUnique&&b.IsFieldsWithoutBorder){c.mcCacheComboTaux._visible=false;c.mcCacheComboTaux.maj()}for(d=0;d<b.TabTauxIsPresent.length&&b.choice_taux;d++)b.TabTauxIsPresent[d]==1&&b.choice_taux.add(b,b.TabValTaux[d])}if(!b.IsTauxUnique||b.NbTypeTaux<2)if(b.DefaultTypeTaux!=0)for(d=0;d<_s_alto.TAB_ID_TAUX.length;d++)if(b.DefaultTypeTaux==
_s_alto.TAB_ID_TAUX[d]){if(b.NbTypeTaux<2){j._visible=false;j.maj();g.text=j.text+" "+b.TabValTaux[d];g._visible=true;g.maj()}else b.choice_taux.selectVal(b.TabValTaux[d]);b.TabValTaux[d]!=_s_alto.ID_TAUX_CHOISI&&ChangementTaux(b,c);break}ChangementTaux(b,c);if((g=b.root._RevenuOnLoad&&b.root._RevenuOnLoad!=0?b.root._RevenuOnLoad:b.RevenuOnLoad)&&g!=0){c.textField_revenu.text=""+g;c.textField_revenu.maj();textField_revenu_focusLost(b)}}
function touchHandler(b){var c=b.changedTouches[0];switch(b.type){case "touchstart":myMouseDown(c.clientY,c.clientX);break;case "touchmove":myMouseMove(c.clientY,c.clientX);break;case "touchend":myMouseUp(c.clientY,c.clientX);break;default:return}}function touchHandler2(b,c){var d=b.changedTouches[0];b.clientX=d.clientX;b.clientY=d.clientY;switch(b.type){case "touchstart":IdentPoigneePressed(b,c);break;case "touchend":IdentPoigneePressed(b,c);break;default:return}}
function MyRepaint(b,c){var d=b._mc;MajRect(b);paint(b,b._mc,c);d.mcBulleMensDuree._x=b.BulleMensCoord.x;d.mcBulleMensDuree._y=b.BulleMensCoord.y;d.mcBullePret._y=b.BullePretCoord.y;d.mcBulleMensDuree.maj();d.mcBullePret.maj()}
function IdentPoigneePressed(b,c){if(window.event)b=window.event;var d=b.target?b.target:b.srcElement;if(d.id.indexOf("Poignee")==-1)d=d.parentNode;c.MouseGestion.IdDivPressed=d.id;c.MouseGestion.ClientXIni=b.clientX;c.MouseGestion.ClientYIni=b.clientY;c.MouseGestion.ClientXLast=b.clientX;c.MouseGestion.ClientYLast=b.clientY;if(c.MouseGestion.IdDivPressed==c.DivId+"mcPoigneeMens")c.MouseGestion.ValYIni=c.Donnees.mensualite;else if(c.MouseGestion.IdDivPressed==c.DivId+"mcPoigneeDuree")c.MouseGestion.ValXIni=
c.Donnees.duree;else if(c.MouseGestion.IdDivPressed==c.DivId+"mcPoigneeMensDuree"){c.MouseGestion.ValYIni=c.Donnees.mensualite;c.MouseGestion.ValXIni=c.Donnees.duree}else if(c.MouseGestion.IdDivPressed==c.DivId+"mcPoigneePret")c.MouseGestion.ValYIni=c.Donnees.pret}
function GetZoneCliquable(b){return b.IsHideHelp==false&&(b.MouseGestion.IdDivPressed==b.DivId+"iImgAide1"||b.MouseGestion.IdDivPressed==b.DivId+"iImgAide2")?_s_alto.ZCLIC_F_AIDE:b.IsCopyright&&(b.MouseGestion.IdDivPressed==b.DivId+"iImgCopyright"||b.MouseGestion.IdDivPressed==b.DivId+"iImgCopyright")?_s_alto.ZCLIC_F_COPYRIGHT:b.MouseGestion.IdDivPressed==b.DivId+"mcPoigneeMens"?_s_alto.ZCLIC_F_MENS_HAUT:b.MouseGestion.IdDivPressed==b.DivId+"mcPoigneeDuree"?_s_alto.ZCLIC_F_MENS_DROITE:b.MouseGestion.IdDivPressed==
b.DivId+"mcPoigneeMensDuree"?_s_alto.ZCLIC_F_MENS_DIAG:b.MouseGestion.IdDivPressed==b.DivId+"mcPoigneePret"?_s_alto.ZCLIC_F_PRET_HAUT:0}function this_mouseMove(b){var c=_g_alto._mc,d=c.div.style.left?parseInt(c.div.style.left):0;c=c.div.style.top?parseInt(c.div.style.top):0;if(window.event)b=window.event;myMouseMove(b.clientY-c,b.clientX-d)}
function myMouseMove(b,c){var d=_g_alto._mc;if(_g_alto.LieuPressed.IsCapture){var e=_g_alto.MouseGestion.ClientYIni-b,f=_g_alto.MouseGestion.ClientXIni-c;TransfertDonneesOldDonnees(_g_alto,true);if(_g_alto.LieuPressed.ZoneClic&_s_alto.ZCLIC_F_GRAPH_MASK){if(_g_alto.LieuPressed.ZoneClic==_s_alto.ZCLIC_F_MENS_HAUT||_g_alto.LieuPressed.ZoneClic==_s_alto.ZCLIC_F_MENS_DIAG){_g_alto.Donnees.mensualite=_g_alto.MouseGestion.ValYIni+Math.floor(e*_g_alto.UnitePixelY);if(_g_alto.Donnees.mensualite<=_g_alto.Donnees.mensualiteMin)_g_alto.Donnees.mensualite=
_g_alto.Donnees.mensualiteMin;else if(_g_alto.Donnees.mensualite>=_g_alto.Donnees.mensualiteMax)_g_alto.Donnees.mensualite=_g_alto.Donnees.mensualiteMax;else Arrondir(_g_alto,_g_alto.LieuPressed.ZoneClic);if(_g_alto.IsFixeMontantPret==1&&_g_alto.LieuPressed.ZoneClic==_s_alto.ZCLIC_F_MENS_HAUT){CalculDuree(_g_alto,_g_alto.MouseGestion.ClientYLast>b?false:true,false);_g_alto.IsHideBottomTextBox||RemplissageTextField_duree(d)}else CalculPretFromMensualDuree(_g_alto);if(IsDebordementPret(_g_alto,d)){if(_g_alto.LieuPressed.ZoneClic==
_s_alto.ZCLIC_F_MENS_HAUT){_g_alto.Donnees.pret=_g_alto.Donnees.pretMax;CalculMensualite(_g_alto)}else TransfertDonneesOldDonnees(_g_alto,false);if(!_g_alto.IsHideBottomTextBox){_g_alto._mc.textField_pret.text=Formatage_alto.FormatInteger(_g_alto.Donnees.pret);_g_alto._mc.textField_pret.maj()}}else if(!_g_alto.IsHideBottomTextBox){d.textField_mensualite.text=Formatage_alto.FormatInteger(_g_alto.Donnees.mensualite);_g_alto._mc.textField_mensualite.maj()}}if(_g_alto.LieuPressed.ZoneClic==_s_alto.ZCLIC_F_PRET_HAUT&&
_g_alto.MouseGestion.ClientYLast!=b){_g_alto.Donnees.pret=_g_alto.MouseGestion.ValYIni+Math.floor(e*_g_alto.UnitePixelPret);if(!IsDebordementPret(_g_alto,d)||_g_alto.Donnees.pret>=_g_alto.Donnees.pretMax){if(_g_alto.Donnees.pret>=_g_alto.Donnees.pretMax)_g_alto.Donnees.pret=_g_alto.Donnees.pretMax;e=_g_alto.MouseGestion.ClientYLast>b?true:false;Arrondir(_g_alto,_g_alto.LieuPressed.ZoneClic);CalculModifPret(_g_alto,e);_g_alto.IsHideBottomTextBox||RemplissageTextField_duree(d)}if(!_g_alto.IsHideBottomTextBox){d.textField_pret.text=
Formatage_alto.FormatInteger(_g_alto.Donnees.pret);_g_alto._mc.textField_pret.maj()}}if(_g_alto.LieuPressed.ZoneClic==_s_alto.ZCLIC_F_MENS_DROITE||_g_alto.LieuPressed.ZoneClic==_s_alto.ZCLIC_F_MENS_DIAG){_g_alto.Donnees.duree=_g_alto.MouseGestion.ValXIni-Math.floor(f*_g_alto.UnitePixelX);if(_g_alto.PasNbMois!=1)_g_alto.Donnees.duree=Math.round(_g_alto.Donnees.duree/_g_alto.PasNbMois)*_g_alto.PasNbMois;if(_g_alto.Donnees.duree<=_g_alto.Donnees.dureeMin)_g_alto.Donnees.duree=_g_alto.Donnees.dureeMin;
else if(_g_alto.Donnees.duree>=_g_alto.Donnees.dureeMax)_g_alto.Donnees.duree=_g_alto.Donnees.dureeMax;else Arrondir(_g_alto,_g_alto.LieuPressed.ZoneClic);ChangementTaux(_g_alto,d);if(_g_alto.IsFixeMontantPret==1&&_g_alto.LieuPressed.ZoneClic==_s_alto.ZCLIC_F_MENS_DROITE)CalculMensualite(_g_alto);else{CalculPretFromMensualDuree(_g_alto);if(IsDebordementPret(_g_alto,d)){if(_g_alto.LieuPressed.ZoneClic==_s_alto.ZCLIC_F_MENS_DROITE){_g_alto.Donnees.pret=_g_alto.Donnees.pretMax;CalculDuree(_g_alto,true,
false);CalculPretFromMensualDuree(_g_alto)}else TransfertDonneesOldDonnees(_g_alto,false);if(!_g_alto.IsHideBottomTextBox){_g_alto._mc.textField_pret.text=Formatage_alto.FormatInteger(_g_alto.Donnees.pret);_g_alto._mc.textField_pret.maj()}}}_g_alto.IsHideBottomTextBox||RemplissageTextField_duree(d)}MyRepaint(_g_alto,_s_alto.ZONE_F_GRAPH)}_g_alto.MouseGestion.ClientYLast=b;_g_alto.MouseGestion.ClientXLast=c}if(_g_alto.IsAideActivate||_g_alto.IsCopyrightActivate){b=GetZoneCliquable(_g_alto);if(b!=_s_alto.ZCLIC_F_AIDE&&
_g_alto.IsAideActivate)setAideActivate(_g_alto,false);else if(_g_alto.IsCopyright&&b!=_s_alto.ZCLIC_F_COPYRIGHT&&_g_alto.IsCopyrightActivate){_g_alto.IsCopyrightActivate=false;_g_alto.PanelToolTipCopyright.setVisible(_g_alto.IsCopyrightActivate)}}}function this_mouseDown(b){var c=_g_alto._mc,d=c.div.style.left?parseInt(c.div.style.left):0;c=c.div.style.top?parseInt(c.div.style.top):0;if(window.event)b=window.event;myMouseDown(b.clientY-c,b.clientX-d)}
function myMouseDown(b,c){_g_alto.LieuPressed.ZoneClic=GetZoneCliquable(_g_alto);if(_g_alto.LieuPressed.ZoneClic!=0)_g_alto.LieuPressed.IsCapture=true;_g_alto.choice_taux&&_g_alto.choice_taux._mcListe._visible&&choice_taux_onListeSelectRelease(_g_alto);if(_g_alto.LieuPressed.ZoneClic==_s_alto.ZCLIC_F_AIDE&&!_g_alto.IsAideActivate)setAideActivate(_g_alto,true);else if(_g_alto.IsCopyright&&_g_alto.LieuPressed.ZoneClic==_s_alto.ZCLIC_F_COPYRIGHT&&!_g_alto.IsCopyrightActivate){_g_alto.IsCopyrightActivate=
true;_g_alto.PanelToolTipCopyright.setVisible(_g_alto.IsCopyrightActivate)}}function this_mouseUp(b){var c=_g_alto._mc,d=c.div.style.left?parseInt(c.div.style.left):0;c=c.div.style.top?parseInt(c.div.style.top):0;if(window.event)b=window.event;myMouseUp(b.clientY-c,b.clientX-d)}function myMouseUp(b,c){_g_alto.LieuPressed.IsCapture=false;myMouseMove(b,c)}
function textField_focusGained(b,c){var d;if(window.event)b=window.event;b=b.target?b.target.parentNode.id:b.srcElement.parentNode.id;if(b.substr(0,c.DivId.length)==c.DivId)b=b.substr(c.DivId.length);b=c._mc[b];d=b._gc_alto.TFContext;c.choice_taux&&c.choice_taux._mcListe._visible&&choice_taux_onListeSelectRelease(c);d.IsChanged=0;d.OldValue=b.text;b.input.focus()}
function textField_revenu_focusLost(b){var c=b._mc.textField_revenu,d=c._gc_alto.TFContext;c.textField_focusLost();if(d.IsChanged==1){d=b._mc;b.IsHideBottomTextBox||InterfaceEnabled(b,d,true);d.mcBulleMensDuree._visible=true;d.mcBullePret._visible=true;d.mcBarre33PC._visible=true;b.Donnees.revenu=Formatage_alto.IntFromFormatInteger(c.text);if(b.Donnees.revenu<b.Donnees.revenuMin)b.Donnees.revenu=b.Donnees.revenuMin;else if(b.Donnees.revenu>b.Donnees.revenuMax)b.Donnees.revenu=b.Donnees.revenuMax;
c.text=Formatage_alto.FormatInteger(b.Donnees.revenu);c.maj();b.Donnees.mensualite=Math.floor(b.Donnees.revenu/3);GraduationVerticale(b,b.y_PointOrigine_util,d);ChangementTaux(b,d);GraduationVerticalePret(b);CalculPretFromMensualDuree(b);if(IsDebordementPret(b,d)){b.Donnees.pret=b.Donnees.pretMax;if(!b.IsHideBottomTextBox){b._mc.textField_pret.text=Formatage_alto.FormatInteger(b.Donnees.pret);b._mc.textField_pret.maj()}CalculMensualite(b);CalculDuree(b,false,false)}if(!b.IsHideBottomTextBox){d.textField_mensualite.text=
Formatage_alto.FormatInteger(b.Donnees.mensualite);d.textField_mensualite.maj();RemplissageTextField_duree(d)}MyRepaint(b,_s_alto.ZONE_F_GRAPH|_s_alto.ZONE_F_GRADUATION);b.IsGraphiqueDessine=true}}function textField_taux_focusLost(b){var c=b._mc.textField_taux,d=c._gc_alto.TFContext;c.textField_focusLost();if(d.IsChanged==1)if(AltoFormatage.FloatFromFormatFloat(c.text)==0){d.IsChanged=0;AltoMovieClip.TFRestoreOldValue(c,d)}else InterfaceTauxChangement(b)}
function textField_mensualite_focusLost(b){var c=b._mc.textField_mensualite,d=c._gc_alto.TFContext;c.textField_focusLost();if(d.IsChanged==1){d=b._mc;var e=b.Donnees.mensualite;b.Donnees.mensualite=Formatage_alto.IntFromFormatInteger(c.text);if(b.Donnees.mensualite>b.Donnees.mensualiteMax)b.Donnees.mensualite=b.Donnees.mensualiteMax;else if(b.Donnees.mensualite<b.Donnees.mensualiteMin)b.Donnees.mensualite=b.Donnees.mensualiteMin;if(b.IsFixeMontantPret==1){CalculDuree(b,e<b.Donnees.mensualite?false:
true,false);RemplissageTextField_duree(d)}else{CalculPretFromMensualDuree(b);if(IsDebordementPret(b,b._mc)){b.Donnees.pret=b.Donnees.pretMax;if(!b.IsHideBottomTextBox)b._mc.textField_pret.text=Formatage_alto.FormatInteger(b.Donnees.pret);CalculMensualite(b)}}if(!b.IsHideBottomTextBox)d.textField_mensualite.text=Formatage_alto.FormatInteger(b.Donnees.mensualite);MyRepaint(b,_s_alto.ZONE_F_GRAPH)}}
function textField_duree_an_focusLost(b){var c=b._mc.textField_duree_an,d=c._gc_alto.TFContext;c.textField_focusLost();if(d.IsChanged){var e=Math.floor(b.Donnees.dureeMin/12),f=Math.floor(b.Donnees.dureeMax/12);c=Formatage_alto.IntFromFormatInteger(c.text);if(isNaN(c)||c<e||c>f)d.IsChanged=0}d.IsChanged&&DureeFocusLost(b)}function textField_duree_mois_focusLost(b){var c=b._mc.textField_duree_mois,d=c._gc_alto.TFContext;c.textField_focusLost();d.IsChanged&&DureeFocusLost(b)}
function textField_pret_focusLost(b){var c=b._mc.textField_pret,d=c._gc_alto.TFContext;c.textField_focusLost();if(d.IsChanged==1){d=b._mc;b.Donnees.pret=Formatage_alto.IntFromFormatInteger(c.text);if(IsDebordementPret(b,d)){if(b.Donnees.pretMax==b.Donnees.pretPlafond){if(b.Donnees.duree!=b.Donnees.dureeMax){b.Donnees.mensualite=b.Donnees.revenu/3;CalculDuree(b,true,true)}b.Donnees.mensualite!=b.Donnees.mensualiteMax&&CalculMensualite(b)}}else CalculModifPret(b,b.Donnees.pret>b.OldPret);if(!b.IsHideBottomTextBox){d.textField_pret.text=
Formatage_alto.FormatInteger(b.Donnees.pret);RemplissageTextField_duree(d)}MyRepaint(b,_s_alto.ZONE_F_GRAPH)}}function choice_taux_mouseDown(b,c){c.choice_taux.onChoixPress(c)}function choice_taux_onListeSelectRelease(b){b.choice_taux.onListeSelectRelease();b.choice_taux._isChanged&&InterfaceTauxChangement(b)}
function InterfaceTauxChangement(b){var c=_g_alto._mc;ChangementTaux(b,c);if(b.IsGraphiqueDessine){GraduationVerticalePret(b);CalculPretFromMensualDuree(b);if(IsDebordementPret(b,c)){b.Donnees.pret=b.Donnees.pretMax;CalculDuree(b,false,true);if(!b.IsHideBottomTextBox)b._mc.textField_pret.text=Formatage_alto.FormatInteger(b.Donnees.pret)}MyRepaint(b,_s_alto.ZONE_F_GRAPH)}}
function DureeFocusLost(b){var c=_g_alto._mc;b.Donnees.duree=Math.floor(parseInt(c.textField_duree_an.text,10)*_s_alto.UNITE_PIXEL_X+parseInt(c.textField_duree_mois.text));if(b.PasNbMois!=1)b.Donnees.duree=Math.floor(b.Donnees.duree/b.PasNbMois)*b.PasNbMois;if(b.Donnees.duree>b.Donnees.dureeMax)b.Donnees.duree=b.Donnees.dureeMax;else if(b.Donnees.duree<b.Donnees.dureeMin)b.Donnees.duree=b.Donnees.dureeMin;ChangementTaux(b,c);if(b.IsFixeMontantPret==1)CalculMensualite(b);else{CalculPretFromMensualDuree(b);
if(IsDebordementPret(b,c)){b.Donnees.pret=b.Donnees.pretMax;CalculDuree(b,true,false);CalculPretFromMensualDuree(b)}}b.IsHideBottomTextBox||RemplissageTextField_duree(c);MyRepaint(b,_s_alto.ZONE_F_GRAPH)}function ChangeCalculette(b){_g_alto=__g_alto[b]}
function LoadAltoCalcFin(b,c){var d,e,f={},h;if(arguments.length<1||b==null)b="IdAltoCalcFin";if(arguments.length<2)c=null;f.DivId=b;e=document.getElementById(b);e.style.position="relative";e.style.textAlign="left";document.onselectstart=function(g){if(!g){g=event;g.target=g.srcElement}if(g.target.nodeName.toLowerCase()!="input"){if(g.preventDefault)g.preventDefault();else g.returnValue=false;return false}};h=new AltoMovieClip(e);_g_alto=f;__g_alto[b]=f;f._mc=h;h.g=f;GlobalInit(f);for(d=0;d<20;d++){_g_alto.TabTauxFixe.tabTranche[d]=
0;_g_alto.TabTauxFixe.tabTaux[d]=0;_g_alto.TabTauxVariable.tabTranche[d]=0;_g_alto.TabTauxVariable.tabTaux[d]=0}iniOnData(f,c);e.onmouseover=function(){ChangeCalculette(b)};e.style.width=f.APPLET_DIMENSION.width+"px";e.style.height=f.APPLET_DIMENSION.height+"px";h.majMovieClipChildrens()};var AltoPoint=function(b,c){this.x=b;this.y=c};var AltoRectangle=function(b,c,d,e){this.x=b;this.y=c;this.width=d;this.height=e;this.contains=function(f,h){return f>=this.x&&f<=this.x+this.width&&h>=this.y&&h<=this.y+this.height?true:false}};var AltoMovieClip=function(b){this.div=b};
AltoMovieClip.prototype.createEmptyMovieClip=function(b,c,d,e,f,h,g){var j=document.createElement("div");c&&j.setAttribute("id",b.DivId+c);j.style.zIndex=d?d:this.div.style.zIndex+1;j.style.position="absolute";this.div.appendChild(j);if(arguments.length>4)j.style.width=h+"px";if(arguments.length>5)j.style.height=g+"px";if(arguments.length>2)j.style.left=e+"px";if(arguments.length>3)j.style.top=f+"px";if(c){var i=new AltoMovieClip(document.getElementById(b.DivId+c));i._x=e;i._y=f;i._width=h;i._height=
g;i.MCType="div";i.parent=this;i.id=b.DivId+c;this[c]=i}return j};AltoMovieClip.prototype.majMovieClipChildrens=function(){var b;for(b in this)if(typeof this[b].MCType!="undefined"&&this[b].MCType!=null){AltoMovieClip.majMovieClip(this[b]);for(item2 in this[b])AltoMovieClip.majMovieClip(this[b][item2])}};AltoMovieClip.prototype.maj=function(){AltoMovieClip.majMovieClip(this)};
AltoMovieClip.majMovieClip=function(b){if(b!=null&&typeof b=="object"&&typeof b.MCType!="undefined"&&b.MCType!=null){if(typeof b._x!="undefined")b.div.style.left=b._x+"px";if(typeof b._y!="undefined")b.div.style.top=b._y+"px";if(typeof b._width!="undefined")b.div.style.width=b._width+"px";if(typeof b._height!="undefined")b.div.style.height=b._height+"px";if(typeof b._visible!="undefined")b.div.style.visibility=b._visible==false?"hidden":"visible";if(typeof b._display!="undefined")b.div.style.display=
b._display==false?"none":"";if(typeof b.useHandCursor!="undefined")b.div.style.cursor=b.useHandCursor==true?"pointer":"auto";if(typeof b.opaqueBackground!="undefined"){b.opaqueBackground=AltoUtil.getHtmlColor(b.opaqueBackground);b.div.style.backgroundColor=b.opaqueBackground}}if(b!=null&&typeof b=="object"&&b.MCType=="textfield"){if(typeof b.text!="undefined")if(b.input){b.input.value=b.text;if(!_s_alto.IsIE)b.input.type="input"}else b.div.innerHTML=b.text;if(typeof b.selectable!="undefined")b.div.style.cursor=
b.selectable?"auto":"pointer";if(typeof b.backgroundColor!="undefined"){b.backgroundColor=AltoUtil.getHtmlColor(b.backgroundColor);if(b.input)b.input.style.backgroundColor=b.backgroundColor;else b.div.style.backgroundColor=b.backgroundColor}if(typeof b.borderColor!="undefined"&&b.borderColor!=null){b.borderColor=AltoUtil.getHtmlColor(b.borderColor);if(b.input){b.input.style.borderColor=b.borderColor;b.input.style.borderWidth="1px"}else{b.div.style.borderColor=b.borderColor;b.div.style.borderStyle=
"solid";b.div.style.borderWidth="1px"}}}};AltoMovieClip.prototype.createTextField=function(b,c,d,e,f,h,g){this.createEmptyMovieClip(b,c,d,e,f,h,g);this[c].MCType="textfield";this[c].type=null;this[c].input=null;this[c]._gc_alto={TFContext:{FlagFormat:0,size:0}};return this[c]};
AltoMovieClip.prototype.textField_focusLost=function(){var b=this,c=this._gc_alto.TFContext;b.text=b.input.value;if(b.text==c.OldValue)c.IsChanged=0;else if(c.FlagFormat&(TFFF_F1_INT|TFFF_F1_FLOAT)){var d=0,e=false;d=c.FlagFormat&TFFF_F1_INT?AltoFormatage.IntFromFormatInteger(b.text):AltoFormatage.FloatFromFormatFloat(b.text);if(!isNaN(d)&&d>0&&c.size){var f=parseInt(c.size,10);if((""+parseInt(""+d,10)).length>f)e=true}if(e||isNaN(d)||d<0){c.IsChanged=0;AltoMovieClip.TFRestoreOldValue(b,c)}else c.IsChanged=
1}else c.IsChanged=1};AltoMovieClip.TFRestoreOldValue=function(b,c){b.text=c.OldValue;b.maj();b.input.focus()};a=AltoMovieClip.prototype;a.getNewTextFormat=function(){return this.TextFormat};
a.setNewTextFormat=function(b){try{var c=this.input?this.input.style:this.div.style;if(typeof b.color!="undefined")c.color=AltoUtil.getHtmlColor(b.color);if(typeof b.font!="undefined")c.fontFamily=b.font;if(typeof b.size!="undefined")c.fontSize=b.size+"px";if(typeof b.bold!="undefined")c.fontWeight=b.bold==true?"bold":"normal";if(typeof b.italic!="undefined")c.fontStyle=b.italic;if(typeof b.align!="undefined")c.textAlign=b.align;if(typeof b.leading!="undefined")c.lineHeight=(c.lineHeight==""?13:parseInt(c.lineHeight))+
b.leading+"px";this.TextFormat=b}catch(d){AltoUtil.dtrace(d.toString()+"  [id:"+this.id+"]")}};a.duplicateMovieClip=function(b,c,d){this.parent.createEmptyMovieClip(b,c,d)};a.removeMovieClip=function(){var b;this.div.parentNode.removeChild(this.div);for(b in this)this[b]=null};a.clear=function(){this.div.innerHTML=""};a.loadMovie=function(b,c){b=document.createElement("img");b.setAttribute("src",c);b.style.zIndex=this.div.style.zIndex+1;this.div.appendChild(b)};
a.attachMovie=function(b,c,d,e){var f;this.createEmptyMovieClip(b,d,e);for(f=0;f<_g_alto.library.clip.length;f++)if(_g_alto.library.clip[f].id==c){c=document.createElement("img");c.setAttribute("src",b.library.clip[f]["import"]);c.style.zIndex=e?e:this[d].div.style.zIndex+1;this[d].div.appendChild(c);break}};a.isPointInMovieClip=function(b,c){if(b>=this._x&&b<=this._x+this._width&&c>=this._y&&c<=this._y+this._height)return true;return false};var AltoPanelToolTip=function(b,c,d,e,f,h,g,j,i,l){this._McParent=c;this._width=g;this._height=j;this._backgroundColor=16774039;this._OmbreColor=8421504;this._marge_bas=this._marge_haut=4;this._marge_droite=this._marge_gauche=5;this._IsPaintNow=true;this._angle=0;c="tt_txt"+parseInt(Math.random()*1E8,10);this._McParent.createEmptyMovieClip(b,d,e);this._mcptt=this._McParent[d];this._mcptt._x=f;this._mcptt._y=h;this._mcptt._focusrect=false;this._mcptt._visible=false;this._mcptt.createTextField(b,c,
null,this._marge_gauche,this._marge_haut,0,0);this.TTTF=this._mcptt[c];this.TTTF.selectable=false;this.TTTF.multiline=true;this.TTTF.autoSize=true;this.TTTF.align="justify";typeof l!="undefined"&&this.TTTF.setNewTextFormat(l);if(typeof i!="undefined")this.TTTF.text=i;if(typeof g=="undefined"||g==null||g<=0)g=this.CalculLargeur();if(typeof j=="undefined"||j==null||j<=0)j=this.CalculHauteur();this._width=g;this._height=j;this._mcptt._width=g;this._mcptt._height=j;this._mcptt[c]._width=g-this._marge_gauche-
this._marge_droite;this.paint(b)};a=AltoPanelToolTip.prototype;a.setText=function(b){this.TTTF.text=b;this.TTTF.maj()};a.setNewTextFormat=function(b){this.TTTF.setNewTextFormat(b)};a.setBackgroundColor=function(b,c){this._backgroundColor=c;_IsPaintNow&&this.paint(b)};
a.setMarge=function(b,c,d,e){if(typeof b!="undefined")this._marge_haut=b;if(typeof c!="undefined")this._marge_droite=c;if(typeof d!="undefined")this._marge_bas=d;if(typeof e!="undefined")this._marge_gauche=e;this.TTTF._x=this._marge_gauche;this.TTTF._y=this._marge_haut};a.setVisible=function(b){this._mcptt._visible=b;this._mcptt.maj()};a.CalculHauteur=function(){return this._marge_haut+this.TTTF._height+this._marge_bas};a.CalculLargeur=function(){return this._marge_gauche+this.TTTF._width+this._marge_droite};
a.paint=function(b){var c=this._mcptt,d;d=AltoUtil.PaintRect(b,c,2,2,this._width,this._height,this._OmbreColor,this._OmbreColor);c[d].div.style.zIndex=100;d=AltoUtil.PaintRect(b,c,0,0,this._width,this._height,0,this._backgroundColor);c[d].div.style.zIndex=100};a.dtrace=function(b,c,d,e,f,h,g,j,i){AltoUtil.drawString(b,c,d,e,f?f:5,h?h:5,g?g:400,j?j:20,i)};var AltoCButton=function(b,c,d,e,f,h,g,j,i,l,k,m){this.g=b;this._height=this._width=this._mc=null;this._backgroundColor=13421772;this._UrlImageHaut=k&&k.length>0?k:null;this._UrlImageBas=m&&m.length>0?m:null;c.createEmptyMovieClip(b,d,e);this._mc=c[d];this._mc.CButton=this;c=this._mc;if(this._UrlImageHaut&&!this._UrlImageBas)this._UrlImageBas=this._UrlImageHaut;if(this._UrlImageBas&&!this._UrlImageHaut)this._UrlImageHaut=this._UrlImageBas;if(typeof f!="undefined"){c._x=f;c._y=h;this._width=g;this._height=
j}c.useHandCursor=true;c._focusrect=false;if(this._UrlImageHaut){c.createEmptyMovieClip(b,"McContainer_Image_Haut",1);c.McContainer_Image_Haut.loadMovie(b,this._UrlImageHaut);if(this._UrlImageHaut!=this._UrlImageBas){c.createEmptyMovieClip(b,"McContainer_Image_Bas",2);c.McContainer_Image_Bas.loadMovie(b,this._UrlImageBas)}}else{c.createTextField(b,"btn_txt",e+1E4,2,2,this._width-2,this._height-2);e=c.btn_txt;e.selectable=false;if(typeof l!="undefined"){l.align="center";e.setNewTextFormat(l)}else{l=
e.getNewTextFormat();l.align="center";e.setNewTextFormat(l)}if(typeof i!="undefined")e.text=i}c.div.IdDivGlobal=b.DivId;this.DrawButton(c)};a=AltoCButton.prototype;a.setText=function(b){this._mc.btn_txt.text=b;this._mc.btn_txt.maj()};a.getText=function(){return this._mc.btn_txt.text};a.setBackgroundColor=function(b){this._backgroundColor=b;this.drawEtatHaut()};a.getBackgroundColor=function(){return this._backgroundColor};
a.DrawButton=function(b){if(this._UrlImageHaut==null||this._UrlImageHaut!=this._UrlImageBas){b.div.onmousedown=this.drawEtatBas;b.div.onmouseup=this.drawEtatHaut;b.div.onmouseout=this.drawEtatHaut}this.drawEtatHaut()};
a.drawEtatHaut=function(b){var c,d;if(this._mc){d=this.g;c=this._mc}else{if(window.event)b=window.event;c=b.target?b.target.parentNode.id:b.srcElement.parentNode.id;d=__g_alto[b.target?b.target.parentNode.IdDivGlobal:b.srcElement.parentNode.IdDivGlobal];if(c.substr(0,d.DivId.length)==d.DivId)c=c.substr(d.DivId.length);c=d._mc[c];if(!c){c=b.target?b.target.parentNode.parentNode.id:b.srcElement.parentNode.parentNode.id;if(c.substr(0,d.DivId.length)==d.DivId)c=c.substr(d.DivId.length);c=d._mc[c]}}b=
c.CButton;if(b._UrlImageBas){if(b._UrlImageHaut!=b._UrlImageBas){c.McContainer_Image_Bas._visible=false;c.McContainer_Image_Bas.maj()}}else{c.btn_txt._x=2;c.btn_txt._y=4;c.btn_txt.maj();AltoUtil.PaintRect(d,c,0,0,b._width,b._height,null,b._backgroundColor);AltoUtil.drawLine(d,c,b._width,0,b._width,b._height,4473924,1);AltoUtil.drawLine(d,c,b._width,b._height,0,b._height,4473924,1);AltoUtil.drawLine(d,c,0,b._height,0,0,16777215,1);AltoUtil.drawLine(d,c,0,0,b._width,0,16777215,1)}};
a.drawEtatBas=function(b){var c,d;if(window.event)b=window.event;c=b.target?b.target.parentNode.id:b.srcElement.parentNode.id;d=__g_alto[b.target?b.target.parentNode.IdDivGlobal:b.srcElement.parentNode.IdDivGlobal];if(c.substr(0,d.DivId.length)==d.DivId)c=c.substr(d.DivId.length);c=d._mc[c];if(!c){c=b.target?b.target.parentNode.parentNode.id:b.srcElement.parentNode.parentNode.id;if(c.substr(0,d.DivId.length)==d.DivId)c=c.substr(d.DivId.length);c=d._mc[c]}b=c.CButton;if(b._UrlImageBas){c.McContainer_Image_Bas._visible=
true;c.McContainer_Image_Bas.maj()}else{c.btn_txt._x=1;c.btn_txt._y=3;c.btn_txt.maj();AltoUtil.drawLine(d,c,b._width,0,b._width,b._height,16777215,1);AltoUtil.drawLine(d,c,b._width,b._height,0,b._height,16777215,1);AltoUtil.drawLine(d,c,0,b._height,0,0,4473924,1);AltoUtil.drawLine(d,c,0,0,b._width,0,4473924,1)}};var AltoCCombo=function(b,c,d,e,f,h,g,j,i,l,k,m){this._TFHeight=this._height=this._width=this._mcListeSelect_tf=this._mcListeSelect=this._mcListe=this._mcBtnChoix=this._mcChoix_tf=this._mcChoix=this._mc=null;this._BorderColor=this._backgroundColor=16777215;this._marge_haut=0;this._marge_droite=this._marge_gauche=this._marge_bas=2;this._wBtnChoixCadre=20-_s_alto.bw*2;this._textFormat=null;this._iComp=1;this._NbItemAdded=0;this._tItem=[];this._indexSelect=this._indexToSelect=-1;this._isChanged=false;
c.createEmptyMovieClip(b,d,e);this._mc=c[d];this._mc.CCombo=this;c=this._mc;this._iComp=e+1;if(typeof f!="undefined"){if(m&16){h+=1;g-=2;i-=4;j-=2;this._wBtnChoixCadre-=2}else if(_s_alto.IsIE_10_ou_inf&&document.compatMode=="CSS1Compat"){j--;g-=2;i-=1;this._wBtnChoixCadre-=2}else j++;c._x=f;c._y=h;this._width=g;this._height=i;this._TFHeight=j}if(k)this._BorderColor=k;c.useHandCursor=true;c._focusrect=false;c.createEmptyMovieClip(b,d+"_choix",this._iComp++);this._mcChoix=c[d+"_choix"];this._mcChoix._focusrect=
false;this._mcChoix._focusEnabled=true;c.createEmptyMovieClip(b,d+"_BtnChoix",this._iComp++);this._mcBtnChoix=c[d+"_BtnChoix"];this._mcBtnChoix._x=this._width-this._wBtnChoixCadre;c.createEmptyMovieClip(b,d+"_liste",this._iComp++);this._mcListe=c[d+"_liste"];this._mcListe._visible=false;this._mcListe._focusrect=false;this._mcListe.useHandCursor=true;this._mcListe._y=this._TFHeight-1+_s_alto.bw*2;this._mcListe.maj();this._mcListe.createEmptyMovieClip(b,d+"_ListeSelect",this._iComp+110);this._mcListeSelect=
this._mcListe[d+"_ListeSelect"];this._mcListeSelect._visible=false;this._mcListeSelect.useHandCursor=true;this._mcListeSelect.maj();this._mcChoix.createTextField(b,d+"_Choix_tf",this._iComp++,this._marge_gauche+2,this._marge_haut+2,this._width,j);this._mcChoix_tf=this._mcChoix[d+"_Choix_tf"];this._mcChoix_tf.selectable=false;this._mcListeSelect.createTextField(b,d+"_ListeSelect_tf",this._iComp+210,this._marge_gauche+2,this._marge_haut+2,this._width,j);this._mcListeSelect_tf=this._mcListeSelect[d+
"_ListeSelect_tf"];this._mcListeSelect_tf.selectable=false;if(typeof l!="undefined"){this._mcChoix_tf.setNewTextFormat(l);this._mcListeSelect_tf.setNewTextFormat(l);this._textFormat=l}this._mcListeSelect_tf.div.style.color="#FFFFFF";this.paint(b,7|m)};a=AltoCCombo.prototype;a.setVisible=function(b){this._mc._visible=b;this._mc.maj()};
a.paint=function(b,c){if(c&1){var d=this._mcChoix;this._mcChoix.rect&&document.getElementById(b.DivId+this._mcChoix.rect).parentNode.removeChild(document.getElementById(b.DivId+this._mcChoix.rect));this._mcChoix.rect=Util_alto.PaintRect(b,d,0,0,this._width,this._TFHeight,c&16?null:this._BorderColor,c&16?null:this._backgroundColor);document.getElementById(b.DivId+this._mcChoix.rect).style.zIndex=this._mcChoix.div.style.zIndex-1;d=this._mcBtnChoix;(c&16)==0&&Util_alto.PaintRect(b,d,0,0,this._wBtnChoixCadre,
this._TFHeight,this._BorderColor,16777215);for(var e=this._wBtnChoixCadre/2,f=0,h=_s_alto.IsIE_10_ou_inf&&document.compatMode=="CSS1Compat"?0:1;e-1>this._wBtnChoixCadre/4-h+_s_alto.bw;e--,f+=2)Util_alto.PaintRect(b,d,e,e+1,f,_s_alto.IsIE_10_ou_inf&&document.compatMode!="CSS1Compat"?2:0,this._BorderColor)}if(c&2){d=this._mcListe;this._mcListe.rect&&document.getElementById(b.DivId+this._mcListe.rect).parentNode.removeChild(document.getElementById(b.DivId+this._mcListe.rect));this._mcListe.rect=Util_alto.PaintRect(b,
d,0,0,this._width,this._height,8947848,this._backgroundColor);document.getElementById(b.DivId+this._mcListe.rect).style.zIndex=this._mcListe.div.style.zIndex-1}if(c&4){d=this._mcListeSelect;this._mcListeSelect.rect&&document.getElementById(b.DivId+this._mcListeSelect.rect).parentNode.removeChild(document.getElementById(b.DivId+this._mcListeSelect.rect));this._mcListeSelect.rect=Util_alto.PaintRect(b,d,0,0,this._width,this._TFHeight,0,3238597);document.getElementById(b.DivId+this._mcListeSelect.rect).style.zIndex=
200+parseInt(this._mcListeSelect.div.style.zIndex-1)}};a.onChoixPress=function(b){this._isChanged=false;if(this._mcListe){if(this._mcListe._visible){this._mcListeSelect._visible=false;this._mcListeSelect.maj();this._mcListe._visible=false}else{if(this._indexSelect>=0){this._indexToSelect=this._indexSelect;this.showListeSelect(b)}this._mcListe._visible=true}this._mcListe.maj();if(this._indexSelect>=0){this._mcListeSelect._visible=this._mcListe._visible;this._mcListeSelect.maj()}this._IsClicked=0}};
a.onListeSelectRelease=function(){if(this._IsClicked){if(this._indexToSelect!=-1&&this._indexSelect!=this._indexToSelect){this._isChanged=true;this._indexSelect=this._indexToSelect;this._mcChoix_tf.text=this._tItem[this._indexSelect].val;this._mcChoix_tf.maj()}this._mcListeSelect._visible=false;this._mcListeSelect.maj();this._mcListe._visible=false;this._mcListe.maj()}else this._IsClicked=1};
a.showListeSelect=function(b){if(!(this._indexToSelect<0)){this._mcListeSelect._y=this._indexToSelect*this._TFHeight;this._mcListeSelect_tf.text=this._tItem[this._indexToSelect].val;if(this._mcListeSelect._visible==false)this._mcListeSelect._visible=true;this._mcListeSelect.maj();this._mcListeSelect_tf.maj();this._mcListeSelect_tf.div.style.zIndex=document.getElementById(b.DivId+this._mcListeSelect.rect).style.zIndex+200}};
a.add=function(b,c,d){var e=this._mcListe,f;this._NbItemAdded++;e.createTextField(b,"tfItem"+this._NbItemAdded,100+this._iComp++,this._marge_gauche+2,this._marge_haut+2+this._tItem.length*this._TFHeight,this._width,this._TFHeight);f=e["tfItem"+this._NbItemAdded];f.setNewTextFormat(this._textFormat);f.text=c;f.selectable=false;f.visibility=true;f.index=this._NbItemAdded-1;f.cb=this;f.maj();f.div.onmousemove=function(){if(f.index!=f.cb._indexToSelect){f.cb._indexToSelect=f.index;f.cb._mcListe._visible==
true&&f.cb.showListeSelect(b)}};if(typeof d=="undefined")d=this._tItem.length;this._tItem.push({id:d,val:c});this._height=this._tItem.length*this._TFHeight;this.paint(b,2)};a.getSelectedItem=function(){if(this._indexSelect<0)return"";return this._tItem[this._indexSelect].val};a.getSelectedId=function(){if(this._indexSelect<0)return-1;return this._tItem[this._indexSelect].id};
a.selectVal=function(b){var c;for(c=this._tItem.length-1;c>=0;c--)if(this._tItem[c].val==b){this._indexSelect=c;this._mcChoix_tf.text=b;this._mcChoix_tf.maj()}};
// Auteur: ALTO Informatique, 33 avenue du Maine 75015 Paris - 2015 - Tous droits r�serv�s