<?php

/**
 * @file
 * Code for the K&B Dossier feature.
 */
include_once 'kandb_dossier.features.inc';

function kandb_form_dossier_node_form_alter(&$form, &$form_state) {
  $form['#submit'][] = 'kandb_set_alias_submit';
}

function kandb_set_alias_submit($form, &$form_state) {
  //path dossier
  $path_dossier = $form['additional_settings']['group']['#groups']['additional_settings'][4]['alias']['#value'];
  if (!$path_dossier) {
    return;
  }
  //set alias for block 1
  if (isset($form['field_articles_block1_ref']['und']) && count($form['field_articles_block1_ref']['und'])) {
    $array_article = $form['field_articles_block1_ref']['und'];
    foreach ($array_article as $index => $article) {
      // if numeric --> is article id
      if (is_numeric($index)) {
        $id_article = $article['target_id']['#entity']->field_articles_block1_ref['und'][$index]['target_id'];
        if ($id_article) {
          // get alias of this id article
          $query = db_select('url_alias', 'n')
              ->fields('n', array('alias'))
              ->condition('source', 'node/' . $id_article);
          $alias = $query->execute()->fetchCol();
          if (count($alias)) {
            $new_alias = $path_dossier . '/';
            $alias = explode("/", $alias[0]);
            $path_article = $alias[1];
            $new_alias .= $path_article;
            //check if exists this alias
            $query = db_select('url_alias', 'n')
                ->fields('n', array('alias'))
                ->condition('alias', $new_alias);
            $exist_alias = $query->execute()->fetchCol();
            krumo($exist_alias);
            if (!count($exist_alias)) {
              $path = array('source' => "node/$id_article", 'alias' => $new_alias);
              path_save($path);
            }
          }
        }
      }
    }
  }

  //set alias for block 2
  if (isset($form['field_articles_block2_ref']['und']) && count($form['field_articles_block2_ref']['und'])) {
    $array_article = $form['field_articles_block2_ref']['und'];
    foreach ($array_article as $index => $article) {
      // if numeric --> is article id
      if (is_numeric($index)) {
        $id_article = $article['target_id']['#entity']->field_articles_block2_ref['und'][$index]['target_id'];
        if ($id_article) {
          // get alias of this id article
          $query = db_select('url_alias', 'n')
              ->fields('n', array('alias'))
              ->condition('source', 'node/' . $id_article);
          $alias = $query->execute()->fetchCol();
          if (count($alias)) {
            $new_alias = $path_dossier . '/';
            $alias = explode("/", $alias[0]);
            $path_article = $alias[1];
            $new_alias .= $path_article;
            //check if exists this alias
            $query = db_select('url_alias', 'n')
                ->fields('n', array('alias'))
                ->condition('alias', $new_alias);
            $exist_alias = $query->execute()->fetchCol();
            krumo($exist_alias);
            if (!count($exist_alias)) {
              $path = array('source' => "node/$id_article", 'alias' => $new_alias);
              path_save($path);
            }
          }
        }
      }
    }
  }

  //set alias for block 3
  if (isset($form['field_articles_block3_ref']['und']) && count($form['field_articles_block3_ref']['und'])) {
    $array_article = $form['field_articles_block3_ref']['und'];
    foreach ($array_article as $index => $article) {
      // if numeric --> is article id
      if (is_numeric($index)) {
        $id_article = $article['target_id']['#entity']->field_articles_block3_ref['und'][$index]['target_id'];
        if ($id_article) {
          // get alias of this id article
          $query = db_select('url_alias', 'n')
              ->fields('n', array('alias'))
              ->condition('source', 'node/' . $id_article);
          $alias = $query->execute()->fetchCol();
          if (count($alias)) {
            $new_alias = $path_dossier . '/';
            $alias = explode("/", $alias[0]);
            $path_article = $alias[1];
            $new_alias .= $path_article;
            //check if exists this alias
            $query = db_select('url_alias', 'n')
                ->fields('n', array('alias'))
                ->condition('alias', $new_alias);
            $exist_alias = $query->execute()->fetchCol();
            krumo($exist_alias);
            if (!count($exist_alias)) {
              $path = array('source' => "node/$id_article", 'alias' => $new_alias);
              path_save($path);
            }
          }
        }
      }
    }
  }
}
