<?php

define('NUMBER_SIMULATOR', 4);
//Similator page
define('KANDB_SIMULATOR_HEADER_MENU_DEFAULT_TITLES', serialize(array(t('Calculer votre capacité d’achat'), t('Estimer les mensualités de remboursement'), t('Simuler vos droits au PTZ+'), t('Simuler mon investissement avec la loi Pinel'))));
define('KANDB_SIMULATOR_HEADER_MENU_DEFAULT_LINKS', serialize(array('nos-outils/simulateur-capacite-achat', 'nos-outils/simulateur-mensualites-remboursement', 'nos-outils/simulateur-droits-ptz', 'nos-outils/simulateur-loi-pinel')));

/**
 * Implementation of hook_menu()
 * @return array
 */
function kandb_simulator_menu() {
  $items = array();
  $items['nos-outils'] = array(
      'title' => 'simulator capacite achat',
      'page callback' => 'render_simulator_capacite_achat',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
  );
  $items['nos-outils/simulateur-capacite-achat'] = array(
      'title' => 'simulator capacite achat',
      'page callback' => 'render_simulator_capacite_achat',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
  );
  $items['nos-outils/simulateur-mensualites-remboursement'] = array(
      'title' => 'simulator mensualites remboursement',
      'page callback' => 'render_simulator_mensualites_remboursement',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
  );
  $items['nos-outils/simulateur-droits-ptz'] = array(
      'title' => 'simulator droits ptz',
      'page callback' => 'render_simulator_droits_ptz',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
  );
  $items['nos-outils/simulateur-loi-pinel'] = array(
      'title' => 'simulator loi pinel',
      'page callback' => 'render_simulator_loi_pinel',
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/content/ketb/simulator'] = array(
      'title' => 'Simulator',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('kandb_simulator_admin_form'),
      'file' => 'kandb_simulator.admin.inc',
      'access arguments' => array('administer content'),
      'type' => MENU_LOCAL_TASK,
  );
  $items['nos-outils/simulateur-droits-ptz/ajax'] = array(
      'title' => 'simulator droits ptz iframe',
      'page callback' => 'render_iframe_simulator_droits_ptz',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
  );
  $items['nos-outils/simulateur-droits-ptz/ptz_ab1b2c'] = array(
      'title' => 'simulator droits ptz iframe',
      'page callback' => 'render_iframe_simulator_droits_ptz_ptz_ab1b2c',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
  );
  
  $items['nos-outils/simulateur-capacite-achat-fnfg'] = array(
      'title' => 'simulator capacite achat fnfg',
      'page callback' => 'render_simulator_capacite_achat_fnfg',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
  );


  $items['nos-outils/simulateur-mensualites-remboursement-calcfin'] = array(
      'title' => 'simulateur mensualites remboursement calcfin',
      'page callback' => 'render_simulateur_mensualites_remboursement_calcfin',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Render simulator capacite achat.
 */
function render_simulator_capacite_achat() {

  return theme('simulator_capacite_achat', array());
}

/**
 * Render simulator mensualites remboursement.
 */
function render_simulator_mensualites_remboursement() {

  return theme('simulator_mensualites_remboursement', array());
}

/**
 * Render simulator simulator droits ptz
 */
function render_simulator_droits_ptz() {

  return theme('simulator_droits_ptz', array());
}

/**
 * Render simulator loi pinel.
 */
function render_simulator_loi_pinel() {

  return theme('simulator_loi_pinel', array());
}

/**
 * Render simulator capacite achat fnfg.
 */
function render_simulator_capacite_achat_fnfg() {
  
  print theme('simulator_capacite_achat_fnfg', array());
  drupal_exit();

}


/**
 * Render simulator mensualites remboursement calcfin.
 */
function render_simulateur_mensualites_remboursement_calcfin () {
  
  print theme('simulateur_mensualites_remboursement_calcfin', array());
  drupal_exit();

}

/**
 * Implement of hook_theme().
 */
function kandb_simulator_theme($existing, $type, $theme, $path) {
  return array(
    'simulator_capacite_achat' => array(
      'template' => 'templates/simulator_capacite_achat',
      'variables' => array(),
    ),
    'simulator_mensualites_remboursement' => array(
      'template' => 'templates/simulator_mensualites_remboursement',
      'variables' => array(),
    ),
    'simulator_droits_ptz' => array(
      'template' => 'templates/simulator_droits_ptz',
      'variables' => array(),
    ),
    'simulator_loi_pinel' => array(
      'template' => 'templates/simulator_loi_pinel',
      'variables' => array(),
    ),
    'simulator_header_block' => array(
      'template' => 'templates/simulator_header_block',
      'variables' => array(),
    ),
    'simulator_ptz_ab1b2c' => array(
      'template' => 'templates/simulator_ptz_ab1b2c',
      'variables' => array(),
    ),
      'simulator_capacite_achat_fnfg' => array(
      'template' => 'templates/simulator_capacite_achat_fnfg',
      'variables' => array(),
    ),
    'simulateur_mensualites_remboursement_calcfin' => array(
      'template' => 'templates/simulateur_mensualites_remboursement_calcfin',
      'variables' => array(),
    ),
  );
}

function render_iframe_simulator_droits_ptz() {
  $path = realpath(drupal_get_path('module', 'kandb_simulator'));
  $content = file_get_contents($path . '/files/ptz_plus_neuf.html');
  print $content;
}

function render_iframe_simulator_droits_ptz_ptz_ab1b2c() {
  print theme('simulator_ptz_ab1b2c');
}
