<?php

/**
 * Implements hook_menu().
 */
function kandb_update_schema_menu() {

  $items['update_field_locnum'] = array(
    'page callback' => 'update_field_locnum',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
    'weight' => -7
  );

  $items['update_avant_premiere_arrondissement'] = array(
    'page callback' => 'update_avant_premiere_arrondissement',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
    'weight' => -7
  );
  return $items;
}

/**
 * Update type field from longtext to text for field_avant_premiere_arrondissem.
 */
function update_avant_premiere_arrondissement() {
  $content_type = 'avant_premiere';
  //field_avant_premiere_arrondissem
  $data = array(
    'field_name' => 'field_avant_premiere_arrondissem',
    'title' => 'Arrondissement',
    'type' => 'text',
    'widget' => 'textfield',
    'max_length' => 255,
    'weight' => 8,
  );
  
  $field_name = $data['field_name'];
  // delete field if exist
  if ($instance = field_info_instance('node', $field_name, $content_type)) {
    if ($instance['widget']['type'] == 'text_textfield') {
      dpm('Current type field is text field. No need update.');
      drupal_goto('/admin/structure/types/manage/avant-premiere/fields');
    }

    // First, delete the instance in case the field type is difference textfield.
    field_delete_instance($instance, TRUE);
    field_purge_batch(1);
  }  
  
  // Make sure the field doesn't already exist.
  if (!field_info_field($field_name)) {
    // Create the field.
    $field = array(
      'field_name' => $field_name,
      'type' => $data['type'],
      'settings' => array(),
    );

    if (isset($data['max_length'])) {
      $field['settings']['max_length'] = $data['max_length'];
    }

    field_create_field($field);
    // Create the instance.
    $instance = array(
      'field_name' => $field_name,
      'entity_type' => 'node',
      'bundle' => $content_type,
      'label' => $data['title'],
      'description' => '',
      'required' => FALSE,
      'widget' => array(
        'type' => $data['widget'],
      ),
    );

    if (isset($instance['widget']['weight'])) {
      $instance['widget']['weight'] = $instance['widget']['weight'];
    }
    else {
      $instance['widget']['weight'] = 8;
    }
    field_create_instance($instance);

    // Return the manage fields in Avant Premiere CT after create an instance.
    dpm('Just change the type field "textfield" for field_avant_premiere_arrondissem.');
    drupal_goto('/admin/structure/types/manage/avant-premiere/fields');
  }
  else {
    dpm('Have no update.');
    drupal_goto('/admin/structure/types/manage/avant-premiere/fields');
  }
  
}

/**
 * Update type field from integer to text for field_programme_loc_num. 
 */
function update_field_locnum() {
  $content_type = 'programme';
  $data = array(
    'field_name' => 'field_programme_loc_num',
    'title' => 'Numéro de voie',
    'type' => 'text',
    'widget' => 'textfield',
    'max_length' => 255,
    'weight' => 59,
  );

  $field_name = $data['field_name'];
  // delete field if exist
  if ($instance = field_info_instance('node', $field_name, $content_type)) {
    if ($instance['widget']['type'] == 'text_textfield') {
      dpm('Current type field is text field. No need update.');
      drupal_goto('/admin/structure/types/manage/programme/fields');
    }

    // First, delete the instance in case the field type is difference textfield.
    field_delete_instance($instance, TRUE);
    field_purge_batch(1);
  }

  // Make sure the field doesn't already exist.
  if (!field_info_field($field_name)) {
    // Create the field.
    $field = array(
      'field_name' => $field_name,
      'type' => $data['type'],
      'settings' => array(),
    );

    if (isset($data['max_length'])) {
      $field['settings']['max_length'] = $data['max_length'];
    }

    field_create_field($field);
    // Create the instance.
    $instance = array(
      'field_name' => $field_name,
      'entity_type' => 'node',
      'bundle' => $content_type,
      'label' => $data['title'],
      'description' => '',
      'required' => FALSE,
      'widget' => array(
        'type' => $data['widget'],
      ),
    );

    if (isset($instance['widget']['weight'])) {
      $instance['widget']['weight'] = $instance['widget']['weight'];
    }
    else {
      $instance['widget']['weight'] = 59;
    }
    field_create_instance($instance);

    // Return the manage fields in Programme CT after create an instance.
    dpm('Just change the type field "textfield" for field_programme_loc_num.');
    drupal_goto('/admin/structure/types/manage/programme/fields');
  }
  else {
    dpm('Have no update.');
    drupal_goto('/admin/structure/types/manage/programme/fields');
  }
}
