language: php
cache:
  bundler: true
  apt: true
  composer: true
  directories:
  - /home/travis/.composer/cache
php:
- 5.5
mysql:
  database: drupal
  username: root
  encoding: utf8
sudo: false
install:
- composer selfupdate
- mysql -e 'SET GLOBAL wait_timeout = 5400;'
- mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"
- echo 'max_execution_time = 120' >> drupal.php.ini;
- echo 'sendmail_path = /bin/true' >> drupal.php.ini;
- phpenv config-add drupal.php.ini
- phpenv rehash
- composer global require drush/drush:dev-master
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- git clone --branch 8.x-1.x http://git.drupal.org/project/composer.git ~/.drush/composer
- cd ..
- drush make --concurrency=5 lightning/drupal-org-core.make drupal -y
- mkdir drupal/profiles/lightning
- cp -R lightning/* drupal/profiles/lightning/.
- cd drupal
- drush make --concurrency=5 profiles/lightning/drupal-org.make --no-core --contrib-destination=profiles/lightning  -y
before_script:
- drush si lightning --db-url=mysql://root:@localhost/drupal -y
- drush cc all
- drush runserver --server=builtin 8080 &>/dev/null &
script:
- drush le lightning_demo
matrix:
  fast_finish: true
notifications:
  slack:
    secure: tCVe1Xghqnx2j1nELDs1ekwcNY69MRLdTkSrv4Rw1hJFJzKn68JwdOFPFODMauOrbavPDVMVCqHfCuGWgQFbnqiq6YzNnl0ectIIB+/qLs1nMCDKWyoHlAa13U6OJxgTpsal1Khwo7mKpLxjTQDgCrf0IO0l+7VJeY3I19PLH10fzP85rZ5Zmfq6Hf9tAlZFdecABpCZMn3PAFv+M1tIDMX23bnFFPUcIXkqRymz5qcEPFLpUPAPmc1rQk+WvI8sR2yrpFEHUNl2Wz24iiNLi5Sl1d8aPu2NCg9prein9WwciyyJreNSGO2dpEw4rsywrhgClhMO6BtPYYau5EfdK77UG0Zj0O7bk6bpZSvLj6KMOdlVQWDjhBNjH0VgJaxxKQnKcuL5lsIoJ7edxv1s56g2zW12/0XmdJTPi7Qf9YCssdhGDqCsW52QHibRMlosKLaSJdRSuC13z+GA7qnJbg/NcGzSGLATT9EXo6AvZM9r4PAMlsmgHdwXXbqNuV4LXvS1ME8pXpQC5qZlmoyJ1Pw61wrAiBnkUpZfDpJZ0pybB4XNrJnqDSA/MkLIiSWuD/xrAWCqWZGRlnVZiDsYNbEzJVKavwNCPcwfLDPKhSkYczeyWsgXWKFut45DA2u/h8JRR88j97KeXsDML2zviJltTNI7pRF3H1hH9WKL2XM=
