<?php
/**
 * @file
 * kandb_programme.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function kandb_programme_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Massy- Palaiseau - Les Ulis (A10)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '03094f45-5d78-4a3b-8325-df2fd190ddba',
    'vocabulary_machine_name' => 'zone_activite',
    'field_id_zone_activite' => array(
      'und' => array(
        0 => array(
          'value' => 8,
          'format' => NULL,
          'safe_value' => 8,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Evry (A6)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1083a0bc-21b4-4eb5-8961-fa3157973055',
    'vocabulary_machine_name' => 'zone_activite',
    'field_id_zone_activite' => array(
      'und' => array(
        0 => array(
          'value' => 4,
          'format' => NULL,
          'safe_value' => 4,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Paris La Défense',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '11074d8d-72dc-4821-acc0-8d59281821f7',
    'vocabulary_machine_name' => 'zone_activite',
    'field_id_zone_activite' => array(
      'und' => array(
        0 => array(
          'value' => 1,
          'format' => NULL,
          'safe_value' => 1,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Est Parisien (A3)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '182bbdf5-1622-4f0f-abc7-061650825ed4',
    'vocabulary_machine_name' => 'zone_activite',
    'field_id_zone_activite' => array(
      'und' => array(
        0 => array(
          'value' => 3,
          'format' => NULL,
          'safe_value' => 3,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'SM2I',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1dcc0274-f74c-436c-a722-6cf2e203cc4a',
    'vocabulary_machine_name' => 'marque_commercialisation',
    'field_id_marque_comm' => array(
      'und' => array(
        0 => array(
          'value' => 'SM2I',
          'format' => NULL,
          'safe_value' => 'SM2I',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Cergy - Pontoise (A15)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '241898f3-5914-4655-abbc-242cdb6d877e',
    'vocabulary_machine_name' => 'zone_activite',
    'field_id_zone_activite' => array(
      'und' => array(
        0 => array(
          'value' => 10,
          'format' => NULL,
          'safe_value' => 10,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Senart (A5)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2b0e7ea9-2270-4278-9144-9e7c75728510',
    'vocabulary_machine_name' => 'zone_activite',
    'field_id_zone_activite' => array(
      'und' => array(
        0 => array(
          'value' => 5,
          'format' => NULL,
          'safe_value' => 5,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Appartement',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '375f3578-f03b-455c-894a-2ad3891cdfba',
    'vocabulary_machine_name' => 'type_de_programme',
    'field_id_type_programme' => array(
      'und' => array(
        0 => array(
          'value' => 'AP',
          'format' => NULL,
          'safe_value' => 'AP',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Vallée de Seine (A6)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '54255144-fcba-4523-9f68-1761c198549b',
    'vocabulary_machine_name' => 'zone_activite',
    'field_id_zone_activite' => array(
      'und' => array(
        0 => array(
          'value' => 7,
          'format' => NULL,
          'safe_value' => 7,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Breguet',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5c1cf8a0-2ec1-4246-886b-e75bbf71cad4',
    'vocabulary_machine_name' => 'marque_commercialisation',
    'field_id_marque_comm' => array(
      'und' => array(
        0 => array(
          'value' => 'BREG',
          'format' => NULL,
          'safe_value' => 'BREG',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Séfima',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6668a41d-3dd2-4bdf-b42b-e5c5ccb2d3bf',
    'vocabulary_machine_name' => 'marque_commercialisation',
    'field_id_marque_comm' => array(
      'und' => array(
        0 => array(
          'value' => 'SEFI',
          'format' => NULL,
          'safe_value' => 'SEFI',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Malardeau',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6a771d1e-1a34-403a-8aa8-7cd20ee92685',
    'vocabulary_machine_name' => 'marque_commercialisation',
    'field_id_marque_comm' => array(
      'und' => array(
        0 => array(
          'value' => 'MALA',
          'format' => NULL,
          'safe_value' => 'MALA',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'St Quentin en Yvelines (N118 – A12)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '74fbd30f-1d13-4571-b205-7d46b1274578',
    'vocabulary_machine_name' => 'zone_activite',
    'field_id_zone_activite' => array(
      'und' => array(
        0 => array(
          'value' => 9,
          'format' => NULL,
          'safe_value' => 9,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Groupe Avantis',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '81b0edaf-ff70-42da-9453-46fabfce5a94',
    'vocabulary_machine_name' => 'marque_commercialisation',
    'field_id_marque_comm' => array(
      'und' => array(
        0 => array(
          'value' => 'AVAN',
          'format' => NULL,
          'safe_value' => 'AVAN',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'SMCI',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '85a702fc-fa0a-4a0a-9033-e6ea7fc6577a',
    'vocabulary_machine_name' => 'marque_commercialisation',
    'field_id_marque_comm' => array(
      'und' => array(
        0 => array(
          'value' => 'SMCI',
          'format' => NULL,
          'safe_value' => 'SMCI',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Bati Service',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8a589dc3-c305-4b4d-af15-d654e4541730',
    'vocabulary_machine_name' => 'marque_commercialisation',
    'field_id_marque_comm' => array(
      'und' => array(
        0 => array(
          'value' => 'BATI',
          'format' => NULL,
          'safe_value' => 'BATI',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Garonor – Aéroport Charles de Gaulle (A1)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'aac28985-1798-4e1d-8ae6-095f89fd0600',
    'vocabulary_machine_name' => 'zone_activite',
    'field_id_zone_activite' => array(
      'und' => array(
        0 => array(
          'value' => 6,
          'format' => NULL,
          'safe_value' => 6,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Franck Arthur Promotion',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'aceca57b-df0d-4fd1-afbc-f879cc98b985',
    'vocabulary_machine_name' => 'marque_commercialisation',
    'field_id_marque_comm' => array(
      'und' => array(
        0 => array(
          'value' => 'FAPR',
          'format' => NULL,
          'safe_value' => 'FAPR',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Maisons et appartements',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b16e053a-18c5-409c-bc98-e6bb7678d046',
    'vocabulary_machine_name' => 'type_de_programme',
    'field_id_type_programme' => array(
      'und' => array(
        0 => array(
          'value' => 'MI',
          'format' => NULL,
          'safe_value' => 'MI',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Sopra Promotion',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b3ff5d64-9bb2-4aae-bbaf-a3853e89c10e',
    'vocabulary_machine_name' => 'marque_commercialisation',
    'field_id_marque_comm' => array(
      'und' => array(
        0 => array(
          'value' => 'SOPR',
          'format' => NULL,
          'safe_value' => 'SOPR',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Marne la Vallée (A4)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b82a56b6-79fc-45ce-a077-97f6547468b9',
    'vocabulary_machine_name' => 'zone_activite',
    'field_id_zone_activite' => array(
      'und' => array(
        0 => array(
          'value' => 2,
          'format' => NULL,
          'safe_value' => 2,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Kaufman & Broad',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c3de611d-a132-4922-ac5a-cb421e6994f7',
    'vocabulary_machine_name' => 'marque_commercialisation',
    'field_id_marque_comm' => array(
      'und' => array(
        0 => array(
          'value' => 'KETB',
          'format' => NULL,
          'safe_value' => 'KETB',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Patrimoine Compagnie',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd9dc895b-21bf-4353-b38d-211adc81c067',
    'vocabulary_machine_name' => 'marque_commercialisation',
    'field_id_marque_comm' => array(
      'und' => array(
        0 => array(
          'value' => 'PATR',
          'format' => NULL,
          'safe_value' => 'PATR',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Maison Individuelle',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'db7212df-0ccf-4f57-985c-156c1181338b',
    'vocabulary_machine_name' => 'type_de_programme',
    'field_id_type_programme' => array(
      'und' => array(
        0 => array(
          'value' => 'MA',
          'format' => NULL,
          'safe_value' => 'MA',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Park Promotion',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'dde7e372-b3c3-49ad-848e-dda77f70a220',
    'vocabulary_machine_name' => 'marque_commercialisation',
    'field_id_marque_comm' => array(
      'und' => array(
        0 => array(
          'value' => 'PARK',
          'format' => NULL,
          'safe_value' => 'PARK',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Résidence Bernard Teillaud',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'fc3c1d8f-0b36-4720-bf02-aac92fd4cdc1',
    'vocabulary_machine_name' => 'marque_commercialisation',
    'field_id_marque_comm' => array(
      'und' => array(
        0 => array(
          'value' => 'RBTG',
          'format' => NULL,
          'safe_value' => 'RBTG',
        ),
      ),
    ),
  );
  return $terms;
}
