<?php
/**
 * @file
 * kandb_plan_du_site.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function kandb_plan_du_site_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'Plan du site',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '7cec0d3c-7c53-472f-bef9-16135cc2b2bb',
  'type' => 'standard_page',
  'language' => 'en',
  'created' => 1454388370,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '88976515-6705-459e-adc0-22169e94c020',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<div class="typeLogements wrapper">
<div class="typeLogements__list bg-white">
<p>Notre offre</p>

<ul>
	<li><a href="/content/avant-premiere" title="Grandes Ouvertures">Grandes Ouvertures</a></li>
	<li><a href="/content/nouveaute" title="Nouveautés">Nouveautés</a></li>
	<li><a href="/content/livraisons" title="Livraisons immédiates">Livraisons immédiates</a></li>
	<li><a href="/notre-offre" title="Notre offre">Notre offre</a></li>
</ul>
</div>

<div class="typeLogements__list bg-white">
<p>Nos conseils</p>

<ul>
	<li><a href="/nos-conseils/pourquoi-acheter-neuf" title="Pourquoi acheter neuf ?">Pourquoi acheter neuf ?</a></li>
	<li><a href="/nos-conseils/acheter-pour-la-premiere-fois-test" title="Réaliser votre premier achat immobilier">Réaliser votre premier achat immobilier</a></li>
	<li><a href="/nos-conseils/concretiser-votre-nouvelle-vie" title="Concrétiser votre nouvelle vie">Concrétiser votre nouvelle vie</a></li>
	<li><a href="/nos-conseils/les-benefices-de-linvestissement-dans-un-bien-immobilier-neuf" title="Les bénéfices de l\'investissement dans un bien immobilier neuf">Les bénéfices de l\'investissement dans un bien immobilier neuf</a></li>
	<li><a href="/nos-conseils/preparer-votre-retraite" title="Préparer votre retraite">Préparer votre retraite</a></li>
</ul>
</div>

<div class="typeLogements__list bg-white">
<p>Articles</p>

<ul>
	<li><a href="/tva-55-ou-7" title="TVA 5,5% ou 7%">TVA 5,5% ou 7%</a></li>
	<li><a href="/exoneration-de-la-taxe-fonciere" title="Exonération de la taxe foncière">Exonération de la taxe foncière</a></li>
	<li><a href="/frais-de-notaire-reduits" title="Frais de notaire réduits">Frais de notaire réduits</a></li>
</ul>
</div>

<div class="typeLogements__list bg-white">
<p>Corporate</p>

<h4>Finance</h4>

<ul>
	<li><a href="/corporate/finance/presentation/fr" title="Présentation">Présentation</a></li>
	<li><a href="/corporate/finance/publication/fr" title="Publication">Publication</a></li>
	<li><a href="/corporate/finance/assemblee-generale/fr" title="Assemblée">Assemblée</a></li>
	<li><a href="/corporate/finance/gouvernance/fr" title="Gouvernance">Gouvernance</a></li>
	<li><a href="/corporate/finance/archives/fr" title="Archives">Archives</a></li>
</ul>

<h4>Ressources Humaines</h4>

<ul>
	<li><a href="/corporate/ressources-humaines/recrutement" title="Edito">Edito</a></li>
	<li><a href="/corporate/ressources-humaines/nos-metiers" title="Explorer nos metiers">Explorer nos metiers</a></li>
	<li><a href="/corporate/ressources-humaines/votre-carriere" title="Votre carriere">Votre carriere</a></li>
	<li><a href="/corporate/ressources-humaines/postuler" title="Postuler">Postuler</a></li>
</ul>

<h4>Finance</h4>

<ul>
	<li><a href="/corporate/finance/presentation/fr" title="Présentation">Présentation</a></li>
	<li><a href="/corporate/finance/publication/fr" title="Publication">Publication</a></li>
	<li><a href="/corporate/finance/assemblee-generale/fr" title="Assemblée">Assemblée</a></li>
	<li><a href="/corporate/finance/gouvernance/fr" title="Gouvernance">Gouvernance</a></li>
	<li><a href="/corporate/finance/archives/fr" title="Archives">Archives</a></li>
</ul>

<h4>Activités</h4>

<ul>
	<li><a href="/corporate/ressources-humaines/recrutement" title="Edito">Edito</a></li>
	<li><a href="/corporate/ressources-humaines/nos-metiers" title="Explorer nos metiers">Explorer nos metiers</a></li>
	<li><a href="/corporate/ressources-humaines/votre-carriere" title="Votre carriere">Votre carriere</a></li>
	<li><a href="/corporate/ressources-humaines/postuler" title="Postuler">Postuler</a></li>
</ul>

<h4>Actualités</h4>

<ul>
	<li><a href="/corporate/actualites" title="Actualité">Actualité</a></li>
	<li><a href="/corporate/actualites/nos-valeurs" title="Nos valeurs">Nos valeurs</a></li>
	<li><a href="/corporate/actualites/notre-histoire" title="Notre histoire">Notre histoire</a></li>
</ul>

<h4>Développement Durable</h4>

<ul>
	<li><a href="/corporate/developpement-durable/charte-rse" title="Charte RSE">Charte RSE</a></li>
	<li><a href="/corporate/developpement-durable/nos-engagements-clients" title="Nos engagements clients">Nos engagements clients</a></li>
	<li><a href="/corporate/developpement-durable/nos-engagements-partenaires" title="Nos engagements partenaires">Nos engagements partenaires</a></li>
	<li><a href="/corporate/developpement-durable/nos-engagements-equipes" title="Nos engagements equipes">Nos engagements equipes</a></li>
	<li><a href="/corporate/developpement-durable/nos-realisation" title="Realisations">Realisations</a></li>
</ul>
</div>
</div>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<div class="typeLogements wrapper">
<div class="typeLogements__list bg-white">
<p>Notre offre</p>

<ul>
	<li><a href="/content/avant-premiere" title="Grandes Ouvertures">Grandes Ouvertures</a></li>
	<li><a href="/content/nouveaute" title="Nouveautés">Nouveautés</a></li>
	<li><a href="/content/livraisons" title="Livraisons immédiates">Livraisons immédiates</a></li>
	<li><a href="/notre-offre" title="Notre offre">Notre offre</a></li>
</ul>
</div>

<div class="typeLogements__list bg-white">
<p>Nos conseils</p>

<ul>
	<li><a href="/nos-conseils/pourquoi-acheter-neuf" title="Pourquoi acheter neuf ?">Pourquoi acheter neuf ?</a></li>
	<li><a href="/nos-conseils/acheter-pour-la-premiere-fois-test" title="Réaliser votre premier achat immobilier">Réaliser votre premier achat immobilier</a></li>
	<li><a href="/nos-conseils/concretiser-votre-nouvelle-vie" title="Concrétiser votre nouvelle vie">Concrétiser votre nouvelle vie</a></li>
	<li><a href="/nos-conseils/les-benefices-de-linvestissement-dans-un-bien-immobilier-neuf" title="Les bénéfices de l\'investissement dans un bien immobilier neuf">Les bénéfices de l\'investissement dans un bien immobilier neuf</a></li>
	<li><a href="/nos-conseils/preparer-votre-retraite" title="Préparer votre retraite">Préparer votre retraite</a></li>
</ul>
</div>

<div class="typeLogements__list bg-white">
<p>Articles</p>

<ul>
	<li><a href="/tva-55-ou-7" title="TVA 5,5% ou 7%">TVA 5,5% ou 7%</a></li>
	<li><a href="/exoneration-de-la-taxe-fonciere" title="Exonération de la taxe foncière">Exonération de la taxe foncière</a></li>
	<li><a href="/frais-de-notaire-reduits" title="Frais de notaire réduits">Frais de notaire réduits</a></li>
</ul>
</div>

<div class="typeLogements__list bg-white">
<p>Corporate</p>

<h4>Finance</h4>

<ul>
	<li><a href="/corporate/finance/presentation/fr" title="Présentation">Présentation</a></li>
	<li><a href="/corporate/finance/publication/fr" title="Publication">Publication</a></li>
	<li><a href="/corporate/finance/assemblee-generale/fr" title="Assemblée">Assemblée</a></li>
	<li><a href="/corporate/finance/gouvernance/fr" title="Gouvernance">Gouvernance</a></li>
	<li><a href="/corporate/finance/archives/fr" title="Archives">Archives</a></li>
</ul>

<h4>Ressources Humaines</h4>

<ul>
	<li><a href="/corporate/ressources-humaines/recrutement" title="Edito">Edito</a></li>
	<li><a href="/corporate/ressources-humaines/nos-metiers" title="Explorer nos metiers">Explorer nos metiers</a></li>
	<li><a href="/corporate/ressources-humaines/votre-carriere" title="Votre carriere">Votre carriere</a></li>
	<li><a href="/corporate/ressources-humaines/postuler" title="Postuler">Postuler</a></li>
</ul>

<h4>Finance</h4>

<ul>
	<li><a href="/corporate/finance/presentation/fr" title="Présentation">Présentation</a></li>
	<li><a href="/corporate/finance/publication/fr" title="Publication">Publication</a></li>
	<li><a href="/corporate/finance/assemblee-generale/fr" title="Assemblée">Assemblée</a></li>
	<li><a href="/corporate/finance/gouvernance/fr" title="Gouvernance">Gouvernance</a></li>
	<li><a href="/corporate/finance/archives/fr" title="Archives">Archives</a></li>
</ul>

<h4>Activités</h4>

<ul>
	<li><a href="/corporate/ressources-humaines/recrutement" title="Edito">Edito</a></li>
	<li><a href="/corporate/ressources-humaines/nos-metiers" title="Explorer nos metiers">Explorer nos metiers</a></li>
	<li><a href="/corporate/ressources-humaines/votre-carriere" title="Votre carriere">Votre carriere</a></li>
	<li><a href="/corporate/ressources-humaines/postuler" title="Postuler">Postuler</a></li>
</ul>

<h4>Actualités</h4>

<ul>
	<li><a href="/corporate/actualites" title="Actualité">Actualité</a></li>
	<li><a href="/corporate/actualites/nos-valeurs" title="Nos valeurs">Nos valeurs</a></li>
	<li><a href="/corporate/actualites/notre-histoire" title="Notre histoire">Notre histoire</a></li>
</ul>

<h4>Développement Durable</h4>

<ul>
	<li><a href="/corporate/developpement-durable/charte-rse" title="Charte RSE">Charte RSE</a></li>
	<li><a href="/corporate/developpement-durable/nos-engagements-clients" title="Nos engagements clients">Nos engagements clients</a></li>
	<li><a href="/corporate/developpement-durable/nos-engagements-partenaires" title="Nos engagements partenaires">Nos engagements partenaires</a></li>
	<li><a href="/corporate/developpement-durable/nos-engagements-equipes" title="Nos engagements equipes">Nos engagements equipes</a></li>
	<li><a href="/corporate/developpement-durable/nos-realisation" title="Realisations">Realisations</a></li>
</ul>
</div>
</div>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'domains' => array(
    2 => 2,
    3 => 3,
  ),
  'domain_site' => TRUE,
  'subdomains' => array(
    0 => 'All affiliates',
    1 => 'Kaufman & Broad Patrimoine',
    2 => 'Kaufman & Broad',
  ),
  'locations' => array(),
  'location' => array(),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2016-02-02 11:46:10 +0700',
);
  return $nodes;
}
