<?php

/**
 * @file
 * K&B B2C Group pages Activities.
 */

/**
 * Implement of hook_menu().
 */
function kandb_activities_menu() {
  $items = array();

  $items['corporate/activites/habitat'] = array(
    'title' => 'Le Groupe - Activités - Habitat',
    'page callback' => 'render_group_activities_habitat',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  $items['corporate/activites/nos-agences'] = array(
    'title' => 'Le Groupe - Activités - Nos agences',
    'page callback' => 'render_group_activities_nos_agences',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  $items['admin/content/ketb/group/active/habitat'] = array(
    'title' => '[Activities] - Habitat',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kandb_group_active_habitat_form'),
    'file' => 'kandb_group_active_habitat.admin.inc',
    'access arguments' => array('administer K&B Contact settings'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implement of hook_theme().
 */
function kandb_activities_theme($existing, $type, $theme, $path) {
  return array(
    'group_activities_header' => array(
      'template' => 'templates/group_active_header',
      'variables' => array(),
    ),

    'group_activities_habitat' => array(
      'template' => 'templates/group_active_habitat',
      'variables' => array(),
    ),

    'group_activities_nos_agences' => array(
      'template' => 'templates/group_activities_nos_agences',
      'variables' => array(),
    ),
  );
}

/**
 * Implements render page habitat.
 */
function render_group_activities_habitat() {
  $data = array();
  return theme('group_activities_habitat', array('data' => $data));
}

/**
 * Implements render page Nos agences.
 */
function render_group_activities_nos_agences() {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'region_kb');

  $regions =  $query->execute();
  $region_variables = array();
  $conseiller_variables = array();
  if($regions && isset($regions['node'])) {
    foreach($regions['node'] as $region) {
      $region_nid = isset($region->nid) ? $region->nid : '';
      if($region_nid) {
        $n_region = node_load($region_nid);
        if($n_region) {
          $region_variables[$region_nid]['region_nid'] = $region_nid;
          $region_variables[$region_nid]['region_kb_id'] = isset($n_region->field_region_kb_id[LANGUAGE_NONE][0]['value']) ? $n_region->field_region_kb_id[LANGUAGE_NONE][0]['value'] : '';
          $region_variables[$region_nid]['region_title'] = $n_region->title;
          $region_variables[$region_nid]['region_kb_libelle'] = isset($n_region->field_region_kb_libelle[LANGUAGE_NONE][0]['value']) ? $n_region->field_region_kb_libelle[LANGUAGE_NONE][0]['value'] : '';
          $region_variables[$region_nid]['region_kb_adresse'] = isset($n_region->field_region_kb_adresse[LANGUAGE_NONE][0]['value']) ? $n_region->field_region_kb_adresse[LANGUAGE_NONE][0]['value'] : '';
          $region_variables[$region_nid]['region_kb_telephone'] = isset($n_region->field_region_kb_telephone[LANGUAGE_NONE][0]['value']) ? $n_region->field_region_kb_telephone[LANGUAGE_NONE][0]['value'] : '';
          $region_variables[$region_nid]['region_kb_longitude'] = isset($n_region->field_region_kb_longitude[LANGUAGE_NONE][0]['value']) ? $n_region->field_region_kb_longitude[LANGUAGE_NONE][0]['value'] : '';
          $region_variables[$region_nid]['region_kb_latitude'] = isset($n_region->field_region_kb_latitude[LANGUAGE_NONE][0]['value']) ? $n_region->field_region_kb_latitude[LANGUAGE_NONE][0]['value'] : '';

          $query2 = new EntityFieldQuery();
          $query2->entityCondition('entity_type', 'node')
            ->entityCondition('bundle', 'conseiller_regional')
            ->fieldCondition('field_conseiller_regional_reg_kb', 'target_id', $region_nid);

          $conseillers = $query2->execute();
          if($conseillers && isset($conseillers['node'])) {
            foreach($conseillers['node'] as $conseiller) {
              $conseiller_nid = isset($conseiller->nid) ? $conseiller->nid : '';
              if($conseiller_nid) {
                $n_conseiller = node_load($conseiller_nid);
                if($n_conseiller) {
                  $conseiller_variables[$region_nid][$conseiller_nid]['conseiller_title'] = $n_conseiller->title;
                  $conseiller_variables[$region_nid][$conseiller_nid]['conseiller_regional_telephone1'] = isset($n_conseiller->field_conseiller_regional_tele1[LANGUAGE_NONE][0]['value']) ? $n_conseiller->field_conseiller_regional_tele1[LANGUAGE_NONE][0]['value'] : '';
                  $conseiller_variables[$region_nid][$conseiller_nid]['conseiller_regional_telephone2'] = isset($n_conseiller->field_conseiller_regional_tele2[LANGUAGE_NONE][0]['value']) ? $n_conseiller->field_conseiller_regional_tele2[LANGUAGE_NONE][0]['value'] : '';
                  $conseiller_variables[$region_nid][$conseiller_nid]['conseiller_regional_photo'] = isset($n_conseiller->field_conseiller_regional_photo[LANGUAGE_NONE][0]['uri']) ? $n_conseiller->field_conseiller_regional_photo[LANGUAGE_NONE][0]['uri'] : '';
                  $conseiller_variables[$region_nid][$conseiller_nid]['conseiller_regional_email'] = isset($n_conseiller->field_conseiller_regional_email[LANGUAGE_NONE][0]['value']) ? $n_conseiller->field_conseiller_regional_email[LANGUAGE_NONE][0]['value'] : '';
                }
              }
            }
          }
        }
      }
    }
  }

  return theme('group_activities_nos_agences', array('region_contents' => $region_variables, 'conseiller_contents' => $conseiller_variables));
}