<?php
/**
 * @file
 * Settings for K&B Website
 */

/**
 * Implements hook_menu().
 */
function kandb_settings_menu() {
  $menu = array();
  $menu['admin/content/ketb'] = array(
    'title' => 'K&B',
    'page callback' => 'kandb_setttings_page_content',
    // 'access callback' => array('administer K&B content'),
    'type' => MENU_LOCAL_TASK,
  );

  $menu['admin/content/ketb/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  return $menu;
}

/**
 * Implements hook_permission().
 */
function kandb_settings_permission() {
  return array(
    'administer K&B content' => array(
      'title' => t('Administer K&B content '),
      'description' => t('Give the user the right to change specific K&B texts and image (other than node).'),
    ),
  );
}

/**
 * Page callback
 */
function kandb_setttings_page_content(){
  $parent = menu_link_get_preferred(current_path());
  $parameters = array(
    'active_trail' => array($parent['plid']),
    'only_active_trail' => FALSE,
    'min_depth' => $parent['depth']+1,
    'max_depth' => $parent['depth']+1,
    'conditions' => array('plid' => $parent['mlid']),
  );

  $children = menu_build_tree($parent['menu_name'], $parameters);
  foreach ($children as &$data) {
    if($data['link']['link_path'] != 'admin/content/ketb/list') $data['link']['hidden'] = false;
  }
  $menu_render = menu_tree_output($children);

  return '<div class="content-sub-menu content-padder">' . drupal_render(menu_tree_output($children)) . '</div>';
}