<?php
/**
 * @file
 * Code for the K&B Settings feature.
 */

include_once 'kandb_settings.features.inc';

/**
 * Implements hook_menu().
 */
function kandb_settings_menu() {
  $menu = array();
  $menu['admin/content/ketb'] = array(
    'title' => 'K&B',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'kandb_setttings_page_content',
    'access callback' => 'user_access',
    'access arguments' => array('administer K&B content'),
  );

  $menu['admin/content/ketb/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $menu['admin/content/ketb/footer'] = array(
    'title' => 'Footer',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kandb_selection_page_footer_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer K&B content'),
  );

  return $menu;
}

/**
 * Implements hook_permission().
 */
function kandb_settings_permission() {
  return array(
    'administer K&B content' => array(
      'title' => t('Administer K&B content '),
      'description' => t('Give the user the right to change specific K&B texts and image (other than node).'),
    ),
  );
}

/**
 * Page callback
 */
function kandb_setttings_page_content(){
  $parent = menu_link_get_preferred(current_path());
  $parameters = array(
    'active_trail' => array($parent['plid']),
    'only_active_trail' => FALSE,
    'min_depth' => $parent['depth']+1,
    'max_depth' => $parent['depth']+1,
    'conditions' => array('plid' => $parent['mlid']),
  );

  $children = menu_build_tree($parent['menu_name'], $parameters);
  foreach ($children as &$data) {
    if($data['link']['link_path'] != 'admin/content/ketb/list') $data['link']['hidden'] = false;
  }
  $menu_render = menu_tree_output($children);

  return '<div class="content-sub-menu content-padder">' . drupal_render(menu_tree_output($children)) . '</div>';
}

/**
 * Form callback
 */
function kandb_selection_page_footer_form(){

  $form = array();

  $form['kandb_settings_social_display'] = array(
    '#type' => 'checkbox',
    '#title' => t('Display social icon'),
    '#default_value' => variable_get('kandb_settings_social_display'),
  );
  $form['kandb_settings_footer_link_face'] = array(
    '#type' => 'textfield',
    '#title' => t('Facebook'),
    '#default_value' => variable_get('kandb_settings_footer_link_face'),
  );
  $form['kandb_settings_footer_link_youtube'] = array(
    '#type' => 'textfield',
    '#title' => t('Youtube'),
    '#default_value' => variable_get('kandb_settings_footer_link_youtube'),
  );
  $form['kandb_settings_footer_link_twitter'] = array(
    '#type' => 'textfield',
    '#title' => t('Twitter'),
    '#default_value' => variable_get('kandb_settings_footer_link_twitter'),
  );
  $form['kandb_settings_footer_link_espace_collaborateur'] = array(
    '#type' => 'textfield',
    '#title' => t('Espace prescripteur'),
    '#default_value' => variable_get('kandb_settings_footer_link_espace_collaborateur'),
  );

  return system_settings_form($form);
}

/**
 * hook_form_validate()
 */
function kandb_selection_page_footer_validate($form, &$form_state) {

}

/**
 * hook_form_submit()
 */
function kandb_selection_page_footer_submit($form, &$form_state) {

}