<?php

/**
 *  Implements hook_menu().
 */
function kandb_habiteo_menu() {
  $items = array();
  $items['admin/config/habiteo'] = array(
    'title' => 'Habiteo',
    'description' => 'Habiteo webservice',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('habiteo_page_settings_form'),
    'access arguments' => array('administrator custom settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['maquettes/%/%'] = array(
    'title' => 'Mock habiteo reponse json',
    'description' => 'Habiteo reponse mock',
    'page callback' => 'render_habiteo_json',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
  );

  $items['maquettes/%/lots'] = array(
    'title' => 'Mock habiteo reponse json for Bien',
    'description' => 'Habiteo reponse mock for Bien',
    'page callback' => 'render_habiteo_json_bien',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );

  // For testing case, and will be remove later.
  $items['test/maquettes'] = array(
    'title' => 'Test cron retrive habiteo for programm',
    'description' => 'Habiteo reponse mock',
    'page callback' => 'render_test_habiteo',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );
  $items['test/maquettes_bien'] = array(
    'title' => 'Test cron retrive habiteo for bien',
    'description' => 'Habiteo reponse mock',
    'page callback' => 'render_test_habiteo_bien',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );




  return $items;
}

/**
 *  Implements hook_settings_form().
 */
function habiteo_page_settings_form($form, &$form_state) {

  $form['variable_tab'] = array(
    '#type' => 'vertical_tabs',
  );

  $form['variable_habiteo_page'] = array(
    '#type' => 'fieldset',
    '#title' => t('Habiteo Setting'),
    '#group' => 'variable_tab',
  );


  $form['variable_habiteo_page']['habiteo_feed_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Habiteo feed URL'),
    '#description' => t('example: http://www.habiteo.com/flux"'),
    '#default_value' => variable_get('habiteo_feed_url', ''),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );

  $form['variable_habiteo_page']['habiteo_feed_token'] = array(
    '#type' => 'textfield',
    '#title' => t('Habiteo feed TOKEN'),
    '#description' => t('example: 3c7070bcf6bc98a6ea813ff7ff78953d'),
    '#default_value' => variable_get('habiteo_feed_token', ''),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );

  $form['variable_habiteo_page']['habiteo_widget_security_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Habiteo widget security key'),
    '#description' => t('example: 5dsf66U3QBz1nuLl7zI82E'),
    '#default_value' => variable_get('habiteo_widget_security_key', ''),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );

  $form['variable_habiteo_page']['habiteo_visite-virtuelle_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Habiteo visite virtuelle url'),
    '#description' => t('example:  http://widgets.habiteo.com/visite-virtuelle'),
    '#default_value' => variable_get('habiteo_visite-virtuelle_url', ''),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );

  $form['variable_habiteo_page']['habiteo_video-de-quartier_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Habiteo video de quartier url'),
    '#description' => t('example:  http://widgets.habiteo.com/video-de-quartier'),
    '#default_value' => variable_get('habiteo_video-de-quartier_url', ''),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );

  $form['variable_habiteo_page']['habiteo_plan-3d_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Habiteo plan 3d url'),
    '#description' => t('example:  http://widgets.habiteo.com/plan-3d'),
    '#default_value' => variable_get('habiteo_plan-3d_url', ''),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );



  $form['variable_habiteo_page']['habiteo_vue-generale_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Habiteo vue generale url'),
    '#description' => t('example:   http://widgets.habiteo.com/vue-generale'),
    '#default_value' => variable_get('habiteo_vue-generale_url', ''),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );

  $form['variable_habiteo_page']['habiteo_plan-de-quartier_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Habiteo plan de quartier url'),
    '#description' => t('example:   http://widgets.habiteo.com/plan-de-quartier'),
    '#default_value' => variable_get('habiteo_plan-de-quartier_url', ''),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );


  return system_settings_form($form);
}

/**
 * Implements ouput json from programe mock.
 */
function render_habiteo_json($token, $type) {

  $uri = 'public://';
  $data = '';
  if ($wrapper = file_stream_wrapper_get_instance_by_uri($uri)) {
    $path = $wrapper->realpath();
    $file = $path . '/maquettes/' . $token . '/' . $type;
    if (file_exists($file)) {
      // Do something
      $data = file_get_contents($file);
    }
  }
  print $data;
}

/**
 * Implement mock page for testing imports habiteo_id into CT programes.
 */
function render_test_habiteo() {
  $path = variable_get('habiteo_feed_programme');
  kandb_habiteo_import_programme();
  return 'Import habiteo into programme';
}

/**
 * Update field_programme_habiteo_id when field_id_programme has exist.
 */
function kandb_habiteo_update_programe($id, $habiteo_id, $bon_plan, $type = 'programme') {
  $file_log_name = 'habiteo_programme' . '_log_' . date('Y-m-d') . '.txt';
  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', $type)
    ->fieldCondition('field_id_programme', 'value', $id, '=');

  $result = $query->execute();

  if (isset($result['node'])) {
    $items_nids = array_keys($result['node']);
    $items = entity_load('node', $items_nids);
    if ($items) {
      foreach ($items as $item) {
        $item->field_programme_habiteo_id[LANGUAGE_NONE][0]['value'] = $habiteo_id;
        $item->field_programme_habiteo_bon_plan[LANGUAGE_NONE][0]['value'] = $bon_plan;
        $item->flag_habiteo = 1;
        node_save($item);
        $logging = $habiteo_id . '|programme|' . 'Success import' . '|' . 'nid:' . $item->nid . "\n";
        createFileErrorLogTxt($file_log_name, $logging);
      }
    }
  } else {
    $logging = $habiteo_id . '|programme|' . $habiteo_id . ' not exist in db' . '|' . 'nid: null' . "\n";
    createFileErrorLogTxt($file_log_name, $logging);
  }
}

/**
 * output json from lots file.
 */
function render_habiteo_json_bien($token) {
  $params = drupal_get_query_parameters();
  $id_lots = isset($params['ID']) ? $params['ID'] : '';
  if ($id_lots) {

    $uri = 'public://';
    $data = '';
    if ($wrapper = file_stream_wrapper_get_instance_by_uri($uri)) {
      $path = $wrapper->realpath();
      $file = $path . '/maquettes/' . $token . '/lots/' . $id_lots;
      if (file_exists($file)) {
        // Do something
        $data = file_get_contents($file);
      }
    }
    print $data;
  }
}

/**
 * Import bien_habiteo_id into bien CT.
 */
function render_test_habiteo_bien() {

  $habiteo_feed_url = variable_get('habiteo_feed_url', '');
  $habiteo_feed_token = variable_get('habiteo_feed_token', '');
  $params = drupal_get_query_parameters();
  $id_lots = isset($params['ID']) ? $params['ID'] : '';
  // Check format url has programme_habiteo_id.
  if (!$id_lots) {
    return 'missing programme_habiteo_id ex: /test/maquettes_bien?ID=file_name';
  }

  if ($habiteo_feed_url && $habiteo_feed_token) {
    $path = $habiteo_feed_url . '/' . $habiteo_feed_token . '/lots?ID=' . $id_lots;
    $request = drupal_http_request($path);
    if (isset($request->data)) {
      $imports = json_decode($request->data);
      if ($imports) {
        foreach ($imports as $item) {
          kandb_habiteo_update_bien($item->id_partenaire, $item->id);
        }
      }
    }
  }
  return 'Import habiteo into bien';
}

/**
 * Update field_bien_habiteo_id when field_id_bienhas exist.
 */
function kandb_habiteo_update_bien($id, $habiteo_id, $type = 'bien') {
  $file_log_name = 'habiteo_bien' . '_log_' . date('Y-m-d') . '.txt';
  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'bien')
    ->fieldCondition('field_id_bien', 'value', $id, '=');
  $result = $query->execute();

  if (isset($result['node'])) {
    $items_nids = array_keys($result['node']);
    $items = entity_load('node', $items_nids);
    if ($items) {
      foreach ($items as $item) {
        $item->field_bien_habiteo_id[LANGUAGE_NONE][0]['value'] = $habiteo_id;
        $item->flag_habiteo = 1;
        node_save($item);
        $logging = $habiteo_id . '|bien|' . 'Success import' . '|' . 'nid:' . $item->nid . "\n";
        createFileErrorLogTxt($file_log_name, $logging);
      }
    }
  } else {
    $logging = $habiteo_id . '|bien|' . $habiteo_id . ' not exist in db' . '|' . 'nid: null' . "\n";
    createFileErrorLogTxt($file_log_name, $logging);
  }
}

function kandb_habiteo_cronapi($op, $job = NULL) {
//  $items['import_habiteo_bien'] = array(
//    'description' => 'Import habiteo bien feed 6am',
//    'rule' => '0 6 * * 1-5',
//    'callback' => 'kandb_habiteo_import_bien',
//    'arguments' => array('lots'),
//  );

  $items['import_habiteo_programme'] = array(
    'description' => 'Import habiteo programme feed 6am',
    'rule' => '0 6 * * 1-5',
    'callback' => 'kandb_habiteo_import_programme',
  );


  return $items;
}

/**
 * Import bien_habiteo_id into bien CT.
 */
function kandb_habiteo_import_bien($path) {
  $file_log_name = 'habiteo_bien' . '_log_' . date('Y-m-d') . '.txt';
  $request = drupal_http_request($path);
  if (isset($request->data)) {
    $imports = json_decode($request->data);
    if ($imports && empty($imports->error)) {
      foreach ($imports as $item) {
        if (!isset($item->error)) {
          if ($item->id_partenaire) {
            // Import bien.
            kandb_habiteo_update_bien($item->id_partenaire, $item->id);
          } else {
            $item_id = isset($item->id) ? $item->id : 'null';
            $logging = $item_id . '|bien|' . 'id_partenaire is null' . '|' . $path . "\n";
            createFileErrorLogTxt($file_log_name, $logging);
          }
        }
      }
    } else {
      $logging = 'URL' . '|bien|' . 'URL not exist data' . '|' . $path . "\n";
      createFileErrorLogTxt($file_log_name, $logging);
    }
  } else {
    $logging = 'URL' . '|programme|' . 'URL not exist data' . '|' . $path . "\n";
    createFileErrorLogTxt($file_log_name, $logging);
  }
}

/**
 * Import programme_habiteo_id into programmes CT.
 */
function kandb_habiteo_import_programme() {
  $habiteo_feed_url = variable_get('habiteo_feed_url', '');
  $habiteo_feed_token = variable_get('habiteo_feed_token', '');
  $file_log_name = 'habiteo_programme' . '_log_' . date('Y-m-d') . '.txt';
  if ($habiteo_feed_url && $habiteo_feed_token) {
    $path = $habiteo_feed_url . '/' . $habiteo_feed_token . '/programmes';
    $request = drupal_http_request($path);
    if (isset($request->data)) {
      $imports = json_decode($request->data);
      if ($imports) {
        foreach ($imports as $item) {
          if ($item->id_partenaire) {
            // Import programe.
            kandb_habiteo_update_programe($item->id_partenaire, $item->id, $item->bon_plan);
          } else {
            $item_id = ($item->id) ? $item->id : 'null';
            $logging = $item_id . '|programme|' . 'id_partenaire is null' . '|' . $path . "\n";
            createFileErrorLogTxt($file_log_name, $logging);
          }
          $path_bien = $habiteo_feed_url . '/' . $habiteo_feed_token . '/lots?id=' . $item->id;
          kandb_habiteo_import_bien($path_bien);
        }
      } else {
        $logging = 'URL' . '|programme|' . 'URL not exist data' . '|' . $path . "\n";
        createFileErrorLogTxt($file_log_name, $logging);
      }
    } else {
      $logging = 'URL' . '|programme|' . 'URL not exist data' . '|' . $path . "\n";
      createFileErrorLogTxt($file_log_name, $logging);
    }
  }
}
