<?php

function kb_import_enable() {
  variable_set('feeds_process_limit', 100000);
  $daily_import_status = daily_import_status_default();
  set_daily_import_status($daily_import_status);
  $migration_status = migration_status_default();
  set_migration_status($migration_status);
}

function kb_import_disable() {
    variable_del('feeds_process_limit');
    variable_del('kb_daily_import_status');
    variable_del('kb_migration_status');
}