<?php

/**
 * Implements hook_menu().
 */
function kb_import_menu() {
  $items = array();

  $items['delete-nodes'] = array(
    'title' => 'Import',
    'page callback' => 'action_delete_nodes',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );

  return $items;
}

function action_delete_nodes() {
  $KBAPI = new KAndBAPI();
  $results = $KBAPI->getListNodeByBundle('node', 'bien');

  foreach ($results as $id => $value) {
    $nids[] = $id;
  }

  if (!empty($nids)) {
    node_delete_multiple($nids);
    drupal_set_message(t('Deleted %count nodes.', array('%count' => count($nids))));
  }
}

/**
 * Implements hook_cronapi
 * @param type $op
 * @param type $job
 * @return string
 */
function kb_import_cronapi($op, $job = NULL) {
//  City import
  $items['fetch_city_feed_import_3am'] = array(
    'description' => 'Fetch city feed 3am',
    'rule' => '0 3 * * 1-5',
    'callback' => 'kb_import_fetch_import_cron' ,
    'arguments' => array(array('city_feed_import'))
  );

  $items['fetch_city_feed_import_4pm'] = array(
    'description' => 'Fetch city feed 4pm',
    'rule' => '0 16 * * 5',
    'callback' => 'kb_import_fetch_import_cron' ,
    'arguments' => array(array('city_feed_import'))
  );
//  District import
  $items['fetch_district_feed_import_3am'] = array(
    'description' => 'Fetch district feed 3am',
    'rule' => '0 3 * * 1-5',
    'callback' => 'kb_import_fetch_import_cron' ,
    'arguments' => array(array('district_feed_import'))
  );

  $items['fetch_district_feed_import_4pm'] = array(
    'description' => 'Fetch district feed 4pm',
    'rule' => '0 16 * * 5',
    'callback' => 'kb_import_fetch_import_cron' ,
    'arguments' => array(array('district_feed_import'))
  );
//  Maison import
  $items['fetch_maison_feed_import_3am'] = array(
    'description' => 'Fetch maison feed 3am',
    'rule' => '0 3 * * 1-5',
    'callback' => 'kb_import_fetch_import_cron' ,
    'arguments' => array(array('maison_feed_import'))
  );

  $items['fetch_maison_feed_import_4pm'] = array(
    'description' => 'Fetch maison feed 4pm',
    'rule' => '0 16 * * 5',
    'callback' => 'kb_import_fetch_import_cron' ,
    'arguments' => array(array('maison_feed_import'))
  );
//  Programme import
  $items['fetch_programme_feed_import_3am'] = array(
    'description' => 'Fetch programme feed 3am',
    'rule' => '0 3 * * 1-5',
    'callback' => 'kb_import_fetch_import_cron' ,
    'arguments' => array(array('programme_feed_import'))
  );

  $items['fetch_programme_feed_import_4pm'] = array(
    'description' => 'Fetch programme feed 4pm',
    'rule' => '0 16 * * 5',
    'callback' => 'kb_import_fetch_import_cron' ,
    'arguments' => array(array('programme_feed_import'))
  );
// Parcel import
  $items['fetch_parcel_feed_import_3am'] = array(
    'description' => 'Fetch parcel feed 3am',
    'rule' => '0 3 * * 1-5',
    'callback' => 'kb_import_fetch_import_cron' ,
    'arguments' => array(array('parcel_feed_import'))
  );

  $items['fetch_parcel_feed_import_4pm'] = array(
    'description' => 'Fetch parcel feed 4pm',
    'rule' => '0 16 * * 5',
    'callback' => 'kb_import_fetch_import_cron' ,
    'arguments' => array(array('parcel_feed_import'))
  );

  return $items;
}

function kb_import_fetch_import_cron($feednames){
  if (function_exists('feeds_source')){
    foreach($feednames as $feedname){
      $source = feeds_source($feedname);
      $source->import();
    }
  }
}