<?php

/**
 * @file
 * K&B B2C Group pages.
 */

/**
 * Implement of hook_menu().
 */
function kandb_group_menu() {
  $items = array();

  $items['group/home'] = array(
    'title' => 'B2B Homepage',
    'page callback' => 'render_group_homepage',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implement of hook_theme().
 */
function kandb_group_theme($existing, $type, $theme, $path) {
  return array(
    'group_homepage' => array(
      'template' => 'templates/group_homepage',
      'variables' => array(),
    ),
  );
}

function render_group_homepage() {
  $data = array();
  $group_header = module_invoke('bean', 'block_view', 'group-header');
  if (isset($group_header['content']) && $group_header['content']) {
    $data['group_header'] = $group_header['content'];
  }
  return theme('group_homepage', array('data' => $data));
}
