<?php

/**
 * @file
 * K&B B2C Group pages.
 */

/**
 * Implement of hook_menu().
 */
function kandb_group_menu() {
  $items = array();

  $items['group/home'] = array(
    'title' => 'B2B Homepage',
    'page callback' => 'render_group_homepage',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  $items['admin/content/ketb/finance/presentation'] = array(
    'title' => '[Finance] Presentation',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kandb_group_finance_presentation_admin_form'),
    'file' => 'kandb_group.admin.inc',
    'access arguments' => array('administer K&B Contact settings'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implement of hook_theme().
 */
function kandb_group_theme($existing, $type, $theme, $path) {
  return array(
    'group_homepage' => array(
      'template' => 'templates/group_homepage',
      'variables' => array(),
    ),
  );
}

function render_group_homepage() {
  $data = array();
  $group_header = module_invoke('bean', 'block_view', 'group-header');
  if (isset($group_header['content']) && $group_header['content']) {
    $data['group_header'] = $group_header['content'];
  }
  return theme('group_homepage', array('data' => $data));
}
