<?php
/**
 * @file
 * kandb_taxonomy.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function kandb_taxonomy_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Plein pied',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '039bd663-6017-487f-8a60-71ac0247ebf6',
    'vocabulary_machine_name' => 'caracteristiques',
    'field_icon_name' => array(),
    'field_searchable' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Hopitaux',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1c65ab25-d08e-4479-b32b-8337d0629025',
    'vocabulary_machine_name' => 'caracteristiques',
    'field_icon_name' => array(),
    'field_searchable' => array(),
  );
  $terms[] = array(
    'name' => 'Métro',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '26cd475e-28a5-40a2-bccc-da0415bfb37b',
    'vocabulary_machine_name' => 'caracteristiques',
    'field_icon_name' => array(),
    'field_searchable' => array(),
  );
  $terms[] = array(
    'name' => 'Garage',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5148ccda-8c3b-4636-b9b3-fdfa0f97368b',
    'vocabulary_machine_name' => 'caracteristiques',
    'field_icon_name' => array(),
    'field_searchable' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Dernier étage',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5bcb4a56-fc94-46f2-ae83-085390b44107',
    'vocabulary_machine_name' => 'caracteristiques',
    'field_icon_name' => array(),
    'field_searchable' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Ascenseur',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5d51c992-aaae-44ac-a276-0339c23ab874',
    'vocabulary_machine_name' => 'caracteristiques',
    'field_icon_name' => array(),
    'field_searchable' => array(),
  );
  $terms[] = array(
    'name' => 'Train',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7ef30dbc-1f5f-4f9d-b6ac-113fc66e0ac9',
    'vocabulary_machine_name' => 'caracteristiques',
    'field_icon_name' => array(),
    'field_searchable' => array(),
  );
  $terms[] = array(
    'name' => 'RER',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '94142950-8942-4790-a010-57d95ba8fb1f',
    'vocabulary_machine_name' => 'caracteristiques',
    'field_icon_name' => array(),
    'field_searchable' => array(),
  );
  $terms[] = array(
    'name' => 'Parking',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'a1e14c18-39e8-425a-9ed2-96071bed666c',
    'vocabulary_machine_name' => 'caracteristiques',
    'field_icon_name' => array(
      'und' => array(
        0 => array(
          'value' => 'icon-car',
          'format' => NULL,
          'safe_value' => 'icon-car',
        ),
      ),
    ),
    'field_searchable' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Ecoles',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'af354588-f627-435e-844d-98e82e6701dd',
    'vocabulary_machine_name' => 'caracteristiques',
    'field_icon_name' => array(),
    'field_searchable' => array(),
  );
  $terms[] = array(
    'name' => 'Jardin',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b62972cd-cf80-45bb-9f1c-eadb9147c7b1',
    'vocabulary_machine_name' => 'caracteristiques',
    'field_icon_name' => array(),
    'field_searchable' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Duplex',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'bc20f6fa-6ccf-4042-a450-69182e7a10c3',
    'vocabulary_machine_name' => 'caracteristiques',
    'field_icon_name' => array(),
    'field_searchable' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Terrasse',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ce124ec1-4ade-4f49-9438-f47e8ab85e86',
    'vocabulary_machine_name' => 'caracteristiques',
    'field_icon_name' => array(),
    'field_searchable' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Commerces',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ce6f6fa8-9ab1-4bfb-b6d2-b627bf110818',
    'vocabulary_machine_name' => 'caracteristiques',
    'field_icon_name' => array(),
    'field_searchable' => array(),
  );
  $terms[] = array(
    'name' => 'Balcon',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fc53ec7e-9b0c-4720-8f10-e4436a6bf4a9',
    'vocabulary_machine_name' => 'caracteristiques',
    'field_icon_name' => array(
      'und' => array(
        0 => array(
          'value' => 'icon-balcony',
          'format' => NULL,
          'safe_value' => 'icon-balcony',
        ),
      ),
    ),
    'field_searchable' => array(
      'und' => array(
        0 => array(
          'value' => 1,
        ),
      ),
    ),
  );
  return $terms;
}
