<?php
/**
 * @file
 * kandb_taxonomy.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function kandb_taxonomy_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Seine et Marne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '003b54c2-78d5-4cb6-a4d9-8b03af410f62',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 77,
          'format' => NULL,
          'safe_value' => 77,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Côte du Nord',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '07cffdc8-1e76-499b-b6d7-3c76d1f7d41a',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 22,
          'format' => NULL,
          'safe_value' => 22,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Meuse',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0c5b9337-495e-4545-98ba-681c93d8b83d',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 55,
          'format' => NULL,
          'safe_value' => 55,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Loire',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1209f04e-6913-4340-b0c5-34113efaed3c',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 42,
          'format' => NULL,
          'safe_value' => 42,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Savoie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '15735e49-070b-4879-9c2d-a6b750b1ca0e',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 73,
          'format' => NULL,
          'safe_value' => 73,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Eure et Loire',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '163aa3c7-cc1d-4105-a589-dbd3436ef9d2',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 28,
          'format' => NULL,
          'safe_value' => 28,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Dordogne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1b8cd301-2c4a-4886-b223-6ca858e16e9d',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 24,
          'format' => NULL,
          'safe_value' => 24,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Calvados',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1dc37db5-36f1-4398-8a0d-c0847b44f931',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 14,
          'format' => NULL,
          'safe_value' => 14,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Aveyron',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1e6b2f36-7b94-4340-b180-094d9f9c29d7',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 12,
          'format' => NULL,
          'safe_value' => 12,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Ariège',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '20753d53-ca80-4676-af88-43c4780829a3',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => '09',
          'format' => NULL,
          'safe_value' => '09',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Pas de Calais',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '23b8b0e4-683c-4133-a67c-379981f95fc3',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 62,
          'format' => NULL,
          'safe_value' => 62,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Landes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '26237abf-2507-475a-96a2-a7b7a3c3693d',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 40,
          'format' => NULL,
          'safe_value' => 40,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Pyrénées Atlantiques',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2b75f5bf-9765-46ad-bfe4-9bd037f04a56',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 64,
          'format' => NULL,
          'safe_value' => 64,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Isère',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2d76b2ac-006d-47d1-b593-991c5b5677f7',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 38,
          'format' => NULL,
          'safe_value' => 38,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Allier',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '36d6a40b-0bde-4079-ab67-855fb4411bf8',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => '03',
          'format' => NULL,
          'safe_value' => '03',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Vaucluse',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '398adaa8-1dce-4c50-8905-a76c26bef3cd',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 84,
          'format' => NULL,
          'safe_value' => 84,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Charente',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3b859c8a-4069-4887-9d29-8a4cdfacb427',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 16,
          'format' => NULL,
          'safe_value' => 16,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Marne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '409b9c89-b3c8-4df5-a4df-20f1a0f8b29c',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 51,
          'format' => NULL,
          'safe_value' => 51,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Vienne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '46fc0eb1-ad53-47b1-8181-4739115ade86',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 86,
          'format' => NULL,
          'safe_value' => 86,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Val de Marne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '47ee4a4e-a085-4435-9d0c-c910037ac285',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 94,
          'format' => NULL,
          'safe_value' => 94,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Paris',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4879f50b-c22d-4758-8a6f-123c6dfce3bc',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 75,
          'format' => NULL,
          'safe_value' => 75,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Côte d’Or',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4936d0af-95ad-4f02-a71b-467fc1191fa3',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 21,
          'format' => NULL,
          'safe_value' => 21,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'NULL',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '499007a6-66a6-4bff-a326-3d2312b94f42',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => '2A',
          'format' => NULL,
          'safe_value' => '2A',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Gard',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4a9c6471-3e16-432f-8730-21f7f2c2d74c',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 30,
          'format' => NULL,
          'safe_value' => 30,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Hautes Pyrénées',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4d7d3b4b-a6ea-44ac-8176-dcfc33ae5dc0',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 65,
          'format' => NULL,
          'safe_value' => 65,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Eure',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '53f05004-9598-4b59-b779-7ee11ebf5d05',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 27,
          'format' => NULL,
          'safe_value' => 27,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Meurthe et Moselle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5599def8-e515-4d6e-bf0a-1d700c8fc545',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 54,
          'format' => NULL,
          'safe_value' => 54,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Rhône-Alpes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '58c51680-b488-4402-9ffc-b8081d74fcea',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 69,
          'format' => NULL,
          'safe_value' => 69,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Ardennes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '59f769d0-1ef2-4aed-93dc-834937eee3f3',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => '08',
          'format' => NULL,
          'safe_value' => '08',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Manche',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5b42a86d-7581-43ba-b28a-2b25f3cb0661',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 50,
          'format' => NULL,
          'safe_value' => 50,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Mayenne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5d48dff2-91d8-44a4-acb1-fb79bdcb54b4',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 53,
          'format' => NULL,
          'safe_value' => 53,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Loiret',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5de821d0-ba20-498c-a9a9-53240e58833a',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 45,
          'format' => NULL,
          'safe_value' => 45,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Hautes Alpes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '61f00e4c-728a-400b-848c-ab6fb2ca71dc',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => '05',
          'format' => NULL,
          'safe_value' => '05',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Haute Savoie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6226ce82-ad3c-43a5-825c-c00ad62e3568',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 74,
          'format' => NULL,
          'safe_value' => 74,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Gironde',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '64929a57-5932-4930-b1ae-62748034916f',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 33,
          'format' => NULL,
          'safe_value' => 33,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Aube',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '65d4fe4d-9e2c-4d8f-9c1d-e5ec2da7cc8c',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 10,
          'format' => NULL,
          'safe_value' => 10,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Charente Maritime',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6edf41b6-917a-47c0-a4f9-866e2ac4befe',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 17,
          'format' => NULL,
          'safe_value' => 17,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Loir et Cher',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '72db5ff7-8b81-46b9-8419-18007573408b',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 41,
          'format' => NULL,
          'safe_value' => 41,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Oise',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '78a8b44b-4ee8-4aee-ad77-869ef9f5fc34',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 60,
          'format' => NULL,
          'safe_value' => 60,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Morbihan',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '78e662cd-3390-4fec-8935-d6de59d4acb3',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 56,
          'format' => NULL,
          'safe_value' => 56,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Lot et Garonne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '79937d57-d74d-4462-aec5-59f969eac2d9',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 47,
          'format' => NULL,
          'safe_value' => 47,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Alpes de Haute Provence',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7b85d957-102a-4e8e-aee8-a1d7c5182b8d',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => '04',
          'format' => NULL,
          'safe_value' => '04',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Nord',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7e7bb61e-5fbd-4b61-bfe3-156f1d5ddf80',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 59,
          'format' => NULL,
          'safe_value' => 59,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Cher',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8604bbde-2337-474f-89cb-12b13d35ecf5',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 18,
          'format' => NULL,
          'safe_value' => 18,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Haute Garonne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8a78376c-3faa-4d73-be27-ac44c075592a',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 31,
          'format' => NULL,
          'safe_value' => 31,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Pyrénées Orientales',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8b67ec97-7775-408a-96c6-ef201a9fc803',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 66,
          'format' => NULL,
          'safe_value' => 66,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Haut Rhin',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8c3c08af-89e4-4d7d-864d-cbe714a2e053',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 68,
          'format' => NULL,
          'safe_value' => 68,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Gers',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8f11b7d9-5db6-4763-9409-1a9a0d5abb27',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 32,
          'format' => NULL,
          'safe_value' => 32,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Jura',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '908a418c-0865-40d5-9655-b3f84efa6e62',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 39,
          'format' => NULL,
          'safe_value' => 39,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Bas Rhin',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '919df960-808e-47a6-b823-d780bfb98c86',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 67,
          'format' => NULL,
          'safe_value' => 67,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Aude',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '97fd6b24-78e0-4ad5-a4c9-cea4403786e7',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 11,
          'format' => NULL,
          'safe_value' => 11,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Lot',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9e556099-0f90-4d0a-9c47-ac4b00a0823f',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 46,
          'format' => NULL,
          'safe_value' => 46,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Yonne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9e64ce17-c2f7-4fee-8817-47ce9a000975',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 89,
          'format' => NULL,
          'safe_value' => 89,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Haute Vienne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9f1c2d14-3eec-426c-997c-46f58ab5707c',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 87,
          'format' => NULL,
          'safe_value' => 87,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Moselle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a14e53f0-2154-40db-bc05-2bd37c6a28a3',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 57,
          'format' => NULL,
          'safe_value' => 57,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Nièvre',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a16b17cf-60b2-4c9f-9d1c-a07dfed37a79',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 58,
          'format' => NULL,
          'safe_value' => 58,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Seine Saint Denis',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a39f3756-b0f2-48b6-9646-3b45cdd21c10',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 93,
          'format' => NULL,
          'safe_value' => 93,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Corrèze',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a62ea4d1-e0e1-46ea-8a85-c470a00a9e5d',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 19,
          'format' => NULL,
          'safe_value' => 19,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Tarn et Garonne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a82f2030-18ac-4641-a10b-b50ee01119d3',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 82,
          'format' => NULL,
          'safe_value' => 82,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Vendée',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a9051175-a9d2-4032-bd1d-5c0013eb6e5c',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 85,
          'format' => NULL,
          'safe_value' => 85,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Bouches du Rhône',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a9705a56-e20b-4b07-b0b2-045bc02dd8aa',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 13,
          'format' => NULL,
          'safe_value' => 13,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'NULL',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b0f40aa1-4ca0-4d11-b0da-b6dfae2d1723',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => '2B',
          'format' => NULL,
          'safe_value' => '2B',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Indre',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b391561b-c72a-43f4-a468-d03edfdae49e',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 36,
          'format' => NULL,
          'safe_value' => 36,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Maine et Loire',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b5cf7be7-ba77-4e2a-8d14-a31be287b755',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 49,
          'format' => NULL,
          'safe_value' => 49,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Vosges',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b60b53fb-6e0a-45d5-8a42-61e982faa4b2',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 88,
          'format' => NULL,
          'safe_value' => 88,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Drôme',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b6ea5411-6eab-4367-9ca8-06d3940ba181',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 26,
          'format' => NULL,
          'safe_value' => 26,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Lozère',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b76d7564-c487-46ab-87ab-7201a78fd526',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 48,
          'format' => NULL,
          'safe_value' => 48,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Orne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b90a3e3c-2618-4321-abb4-edcd067647b0',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 61,
          'format' => NULL,
          'safe_value' => 61,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Sarthe',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ba2c8bc8-0d8a-4310-bd66-9a87a094fb11',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 72,
          'format' => NULL,
          'safe_value' => 72,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Deux Sèvres',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bde24e77-e357-43fe-985e-d0b511dadd44',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 79,
          'format' => NULL,
          'safe_value' => 79,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Seine Maritime',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bf1b303e-e8e2-4c2a-bbd6-c62098dfb1dd',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 76,
          'format' => NULL,
          'safe_value' => 76,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Haute Marne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c06786f6-2124-4b6c-8221-01b5ae14bd04',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 52,
          'format' => NULL,
          'safe_value' => 52,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Yvelines',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c082b577-2c73-4114-b851-09b548cdf03d',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 78,
          'format' => NULL,
          'safe_value' => 78,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Hauts de Seine',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c1b72e0f-f332-4c02-b759-0ba904270312',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 92,
          'format' => NULL,
          'safe_value' => 92,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Tarn',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'caadd915-4620-4612-ad96-31953f029523',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 81,
          'format' => NULL,
          'safe_value' => 81,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Haute Loire',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd35899d3-3f66-44db-98b1-a81082cc3277',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 43,
          'format' => NULL,
          'safe_value' => 43,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Doubs',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd4753597-8dea-4291-a335-49b4ad016c75',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 25,
          'format' => NULL,
          'safe_value' => 25,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Hérault',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd672ec97-aa5b-407f-a00d-a67c6bf54a43',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 34,
          'format' => NULL,
          'safe_value' => 34,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Var',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'de54d1b2-f2e9-415f-8f55-802cc2e0d54a',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 83,
          'format' => NULL,
          'safe_value' => 83,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Ain',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'df171e69-d5aa-4bd3-969b-18abdc862b9a',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => '01',
          'format' => NULL,
          'safe_value' => '01',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Alpes Maritimes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'df4c9b9b-c26a-4db2-a223-92537aef85c5',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => '06',
          'format' => NULL,
          'safe_value' => '06',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Creuse',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e2e264f8-5230-4a42-b69d-2800588bf434',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 23,
          'format' => NULL,
          'safe_value' => 23,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Haute Saône',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e7d0d6ea-2b07-4af8-80ff-b7a0ac286bda',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 70,
          'format' => NULL,
          'safe_value' => 70,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Saône et Loire',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e92faf6d-726a-445d-8389-830e9276b8aa',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 71,
          'format' => NULL,
          'safe_value' => 71,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Val d’Oise',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'eadca26f-5547-4fb9-9630-eb5da5486747',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 95,
          'format' => NULL,
          'safe_value' => 95,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Loire Atlantique',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'eb4e5a9a-82f9-4883-9a7e-1f4fb1d93999',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 44,
          'format' => NULL,
          'safe_value' => 44,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Cantal',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'eccdcca3-7f89-40b9-8d15-20528a38d2b7',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 15,
          'format' => NULL,
          'safe_value' => 15,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Finistère',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f36c4490-1c27-41c9-beed-7010918b5dbb',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 29,
          'format' => NULL,
          'safe_value' => 29,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Ille et Vilaine',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f66c9724-6b76-4d8e-b100-282c2edf011f',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 35,
          'format' => NULL,
          'safe_value' => 35,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Indre et Loire',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f72f135e-c9b6-4d7b-a8b1-035c7fb80a01',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 37,
          'format' => NULL,
          'safe_value' => 37,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Essonne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f732ce9c-84ac-412c-a890-c557cad90d21',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => 91,
          'format' => NULL,
          'safe_value' => 91,
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Ardèche',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fdd69392-db48-412d-92dc-1fb86a4e0039',
    'vocabulary_machine_name' => 'departement',
    'field_numero_departement' => array(
      'und' => array(
        0 => array(
          'value' => '07',
          'format' => NULL,
          'safe_value' => '07',
        ),
      ),
    ),
  );
  return $terms;
}
