<?php

/**
 * @file
 * Code for the K&B Recherche feature.
 */
include_once 'kandb_recherche.features.inc';

/**
 * Implements hook_menu().
 */
function kandb_recherche_menu() {
  $menu['recherche_minimal'] = array(
    'title' => 'Recherche minimal',
    'page callback' => 'recherche_minimal_form_submit',
    'access arguments' => array('access content'),
  );

  $menu['recherche_simple'] = array(
    'title' => 'Recherche minimal',
    'page callback' => 'recherche_simple_form_submit',
    'access arguments' => array('access content'),
  );

  $menu['recherche_complete_b2c'] = array(
    'title' => 'Recherche minimal',
    'page callback' => 'recherche_complete_b2c_form_submit',
    'access arguments' => array('access content'),
  );

  return $menu;
}

/**
 * Implements hook_block_info().
 */
function kandb_recherche_block_info() {
  $blocks = array();

  $blocks['recherche_minimal'] = array(
    'info' => t('Recherche minimal'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  $blocks['recherche_simple'] = array(
    'info' => t('Recherche simple'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  $blocks['recherche_complete_b2c'] = array(
    'info' => t('Recherche complète B2C'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  $blocks['recherche_complete_b2b'] = array(
    'info' => t('Recherche complète B2B'),
    'cache' => DRUPAL_NO_CACHE,
    'status' => 0,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function kandb_recherche_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'recherche_minimal':
      $block['subject'] = '';
      $block['content'] = theme('recherche_minimal', array('form' => drupal_get_form('recherche_minimal_form')));
      break;
    case 'recherche_simple':
      $block['subject'] = '';
      $block['content'] = theme('recherche_simple', array('form' => drupal_get_form('recherche_simple_form')));
      break;
    case 'recherche_complete_b2c':
      $block['subject'] = '';
      $block['content'] = theme('recherche_complete_b2c', array('form' => drupal_get_form('recherche_complete_b2c_form')));
      break;
    case 'recherche_complete_b2b':
      $block['subject'] = '';
      $block['content'] = theme('recherche_complete_b2b', array());
      break;
  }

  return $block;
}

/**
 * Implements of hook_theme().
 */
function kandb_recherche_theme($existing, $type, $theme, $path) {
  return array(
    'recherche_minimal' => array(
      'template' => 'templates/recherche_minimal',
      'variables' => array('form' => NULL),
    ),
    'recherche_simple' => array(
      'template' => 'templates/recherche_simple',
      'variables' => array('form' => NULL),
    ),
    'recherche_complete_b2c' => array(
      'template' => 'templates/recherche_complete_b2c',
      'variables' => array('form' => NULL),
    ),
    'recherche_complete_b2b' => array(
      'template' => 'templates/recherche_complete_b2b',
      'variables' => array(),
    ),
    'recherche_check_box' => array(
      'render element' => 'element',
    ),
    'recherche_check_box_item' => array(
      'render element' => 'element',
    ),
    'recherche_button' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Create form 'Recherche Minimal'
 * @param type $form
 * @param type $form_state
 * @return string
 */
function recherche_minimal_form($form, &$form_state) {
  $form['place'] = array(
    '#type' => 'textfield',
    '#attributes' => array('required' => 'required', 'placeholder' => array('Ville, département ou programme'), 'class' => array('input__search')),
    '#theme_wrappers' => array()
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Trouver un bien'),
    '#theme_wrappers' => array(),
    '#attributes' => array('class' => array('btn-icon')),
    '#theme' => 'recherche_button'
  );

  $form['#method'] = 'get';
  $form['#action'] = '/recherche_minimal';
  $form['#theme'] = array('recherche_minimal');

  return $form;
}

/**
 * Implements hook_form_validate()
 * @param type $form
 * @param type $form_state
 */
function recherche_minimal_form_validate($form, &$form_state) {

}

/**
 * Implements hook_form_submit()
 * @param type $form
 * @param type $form_state
 */
function recherche_minimal_form_submit() {

}

/**
 * Create form 'Recherche Simple'
 * @param type $form
 * @param type $form_state
 * @return string
 */
function recherche_simple_form($form, &$form_state) {
  $form['place'] = array(
    '#type' => 'textfield',
    '#attributes' => array('required' => 'required', 'placeholder' => array('Ville, département ou programme'), 'class' => array('input__search')),
    '#theme_wrappers' => array()
  );

  $form['type'] = array(
    '#type' => 'checkboxes',
    '#options' => drupal_map_assoc(
      array(
        t('Maison'),
        t('Appartment'),
        t('Commerce et bureaux'),
        t('Déménagement')
      )
    ),
    '#theme_wrappers' => array(),
    '#theme' => 'recherche_check_box'
  );

  $form['prix_min'] = array(
    '#type' => 'textfield',
    '#size' => 1,
    '#attributes' => array('placeholder' => array('Min'), 'class' => array('input__text small-padding text-center')),
    '#theme_wrappers' => array(),
  );

  $form['prix_max'] = array(
    '#type' => 'textfield',
    '#size' => 1,
    '#attributes' => array('placeholder' => array('Max'), 'class' => array('input__text small-padding text-center')),
    '#theme_wrappers' => array()
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Trouver un bien'),
    '#theme_wrappers' => array(),
    '#attributes' => array('class' => array('btn-icon')),
    '#theme' => 'recherche_button'
  );

  $form['#method'] = 'get';
  $form['#action'] = '/recherche_simple';
  $form['#theme'] = array('recherche_simple');

  return $form;
}

/**
 * Implements hook_form_validate()
 * @param type $form
 * @param type $form_state
 */
function recherche_simple_form_validate(&$form, &$form_state) {

}

/**
 * Implements hook_form_submit()
 * @param type $form
 * @param type $form_state
 */
function recherche_simple_form_submit() {

}

/**
 * Create form 'Recherche Complete B2C'
 * @param type $form
 * @param type $form_state
 * @return type
 */
function recherche_complete_b2c_form($form, &$form_state) {
  $form['place'] = array(
    '#type' => 'textfield',
    '#attributes' => array('required' => 'required', 'placeholder' => array('Ville, département ou programme'), 'class' => array('input__search')),
    '#theme_wrappers' => array()
  );

  $form['type'] = array(
    '#type' => 'checkboxes',
    '#options' => drupal_map_assoc(
      array(
        t('Maison'),
        t('Appartment'),
        t('Commerce et bureaux'),
        t('Déménagement')
      )
    ),
    '#theme_wrappers' => array(),
    '#theme' => 'recherche_check_box'
  );

  $form['prix_min'] = array(
    '#type' => 'textfield',
    '#size' => 1,
    '#attributes' => array('placeholder' => array('Min'), 'class' => array('input__text small-padding text-center')),
  );

  $form['prix_max'] = array(
    '#type' => 'textfield',
    '#size' => 1,
    '#attributes' => array('placeholder' => array('Max'), 'class' => array('input__text small-padding text-center')),
  );

  $form['pieces'] = array(
    '#type' => 'checkboxes',
    '#options' => drupal_map_assoc(
      array(
        t('1 pièce'),
        t('2 pièce'),
        t('3 pièce'),
        t('4 pièce'),
        t('5 pièce et +')
      )
    ),
    '#theme_wrappers' => array(),
    '#theme' => 'recherche_check_box'
  );

  $form['surface_min'] = array(
    '#type' => 'textfield',
    '#size' => 1,
    '#attributes' => array('placeholder' => array('Min')),
  );

  $form['services'] = array(
    '#type' => 'checkboxes',
    '#options' => drupal_map_assoc(
      array(
        t('Duplex'),
        t('Plein-pied'),
        t('Dernier étage'),
        t('Garage / Parking'),
        t('Balcon / Terrasse / Jardin'),
        t('Pack silver'),
      )
    ),
    '#theme_wrappers' => array(),
    '#theme' => 'recherche_check_box'
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Trouver un bien'),
    '#theme_wrappers' => array(),
    '#attributes' => array('class' => array('btn-icon')),
    '#theme' => 'recherche_button'
  );

  $form['#method'] = 'get';
  $form['#action'] = '/recherche_complete_b2c';
  $form['#theme'] = array('recherche_complete_b2c');

  return $form;
}

/**
 * Implements hook_form_validate()
 * @param type $form
 * @param type $form_state
 */
function recherche_complete_b2c_form_validate(&$form, &$form_state) {

}

/**
 * Implements hook_form_submit()
 * @param type $form
 * @param type $form_state
 */
function recherche_complete_b2c_form_submit() {

}

/**
 * Custom theme of checkboxes for the gender field.
 */
function theme_recherche_check_box($variables) {
  $element = $variables['element'];
  $options = array_keys($element['#options']);
  $output = '';

  $totalOptions = count($options);
  $count = 1;
  foreach ($options as $option) {
    $element[$option]['#class'] = 'class="bordered"';
    if($count == $totalOptions) {
      $element[$option]['#class'] = '';
    }
    $output .= theme('recherche_check_box_item', $element[$option]);
    $count++;
  }

  return $output;
}

/**
 * Custom theme of checkboxes for the gender field.
 */
function theme_recherche_check_box_item($variables) {
  $element = $variables['element'];
  $element['#attributes']['class'] = array('input-checkbox');

  $attributes = array('#return_value' => 'value', 'id', 'type');
  element_set_attributes($element, $attributes);
  if ($element['#default_value'] == $element['#return_value']) {
    $element['#attributes']['checked'] = 'checked';
  }

  $output = '<li ' . $element['#class'] . '>'
    . '<input name="' . $element['#name'] . '" ' . drupal_attributes($element['#attributes']) . '/>'
    . '<label class="label-checkbox" for="' . $element['#id'] . '"><span>' . $element['#title'] . '</span></label>'
    . '</li>';

  return $output;
}

/**
 * Override of theme_button().
 *
 * Render the button element as a button and the submit element as an input element.
 */
function theme_recherche_button($variables) {
  $element = $variables['element'];
  $element['#attributes']['type'] = 'submit';

  element_set_attributes($element, array('id', 'name', 'value'));

  if (!empty($element['#attributes']['disabled'])) {
    $element['#attributes']['class'][] = 'form-button-disabled';
  }

  $value = $element['#value'];
  unset($element['#attributes']['value']);

  return '<button value="' . $value . '"' . drupal_attributes($element['#attributes']) . '><span class="button__content"><span class="icon icon-search"></span>' . $value . '</span></button>';
}
