<?php

/**
 * @file
 * K&B B2B.
 */

/**
 * Implement of hook_menu().
 */
function kandb_b2b_menu() {
  $items = array();

  $items['b2b-homepage'] = array(
    'title' => 'B2B Homepage',
    'page callback' => 'render_b2b_homepage',
    'file' => 'kandb_b2b.inc',
    'access callback' => 'kandb_b2b_check_domain',
    'type' => MENU_CALLBACK,
  );

  $items['admin/content/kandb-b2b'] = array(
    'title' => 'K&B Patrimoine',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'kandb_b2b_setttings_page_content',
    'file' => 'kandb_b2b.admin.inc',
    'access callback' => 'user_access',
    'access arguments' => array('administer K&B B2B content'),
  );

  $items['admin/content/kandb-b2b/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items['admin/content/kandb-b2b/homepage'] = array(
    'title' => 'Homepage',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kandb_b2b_homepage_settings'),
    'file' => 'kandb_b2b.admin.inc',
    'access callback' => 'user_access',
    'access arguments' => array('administer K&B B2B content'),
  );

  $items['admin/content/kandb-b2b/homepage-programme/autocomplete'] = array(
    'title' => 'Programme - Homepage',
    'type' => MENU_CALLBACK,
    'page callback' => '_kandb_b2b_homepage_programme_autocomplete',
    'file' => 'kandb_b2b.admin.inc',
    'access callback' => 'user_access',
    'access arguments' => array('administer K&B B2B content'),
  );


  $items['admin/content/kandb-b2b/register'] = array(
    'title' => 'Register Page',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('kandb_b2b_register_page_settings'),
    'file' => 'kandb_b2b.admin.inc',
    'access callback' => 'user_access',
    'access arguments' => array('administer K&B B2B content'),
  );

  return $items;
}

/**
 * Implements of hook_permission().
 */
function kandb_b2b_permission() {
  return array(
    'administer K&B B2B content' => array(
      'title' => t('Administer K&B B2B content '),
      'description' => t('Give the user the right to change specific K&B B2B texts and image (other than node).'),
    ),
  );
}

/**
 * Check current domain is K&B B2B.
 */
function kandb_b2b_check_domain() {
  $result = FALSE;

  $domain = domain_get_domain();
  $domain_obj = isset($domain['domain_id']) ? domain_load($domain['domain_id']) : '';
  if (isset($domain_obj['machine_name']) AND $domain_obj['machine_name'] == 'kandb_b2b') {
    $result = TRUE;
  }

  return $result;
}

/**
 * Implement of hook_theme().
 */
function kandb_b2b_theme($existing, $type, $theme, $path) {
  return array(
    // Contact buttons
    'b2b_homepage' => array(
      'template' => 'templates/b2b_homepage',
      'variables' => array(),
    ),
    'b2b_register_header' => array(
      'template' => 'templates/b2b_register_header',
      'variables' => array(),
    ),
  );
}

/**
 * Implements of hook_date_formats().
 */
function kandb_b2b_date_formats() {
  return array(
    array(
      'type' => 'date_format_dd_mm_yyyy',
      'format' => 'd.m.Y',
      'locales' => array(),
    ),
  );
}

/**
 * Implements of hook_date_format_types().
 */
function kandb_b2b_date_format_types() {
  return array(
    'date_format_dd_mm_yyyy' => t('DD.MM.YYYY'),
  );
}

/**
 * Implements of hook_user_login().
 */
function kandb_b2b_user_login(&$edit, $account) {
  $edit['redirect'] = 'dash-board';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function kandb_form_user_register_form_alter(&$form, &$form_state) {
  global $user, $theme;
  if ($theme == 'kandb_b2b_theme') {
    $form['account']['name']['#required'] = FALSE;
    array_unshift($form['#validate'], 'kandb_user_register_validate_username');
  }
}

/**
 * Implement hook_form_validate().
 */
function kandb_user_register_validate_username(&$form, &$form_state) {
  if ($form_state['values']['mail']) {
    $form_state['values']['name'] = $form_state['values']['mail'];
  }
}
