<?php
/**
 * @file
 * kandb_feed.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function kandb_feed_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'taxonomy_term-ville-field_code_departement'
  $field_instances['taxonomy_term-ville-field_code_departement'] = array(
    'bundle' => 'ville',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_code_departement',
    'label' => 'Code departement',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'taxonomy_term-ville-field_idk'
  $field_instances['taxonomy_term-ville-field_idk'] = array(
    'bundle' => 'ville',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_idk',
    'label' => 'IDK',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 1,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Code departement');
  t('IDK');

  return $field_instances;
}
