<?php
/**
 * @file
 * kandb_feed.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function kandb_feed_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => '13ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0dac5757-9c04-4634-b652-e94968be899d',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000003',
          'format' => 'plain_text',
          'safe_value' => '000003',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000042',
          'format' => 'plain_text',
          'safe_value' => '000042',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '9ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '28d6f0df-c67c-4677-9678-bbc43aac312b',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000003',
          'format' => 'plain_text',
          'safe_value' => '000003',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000038',
          'format' => 'plain_text',
          'safe_value' => '000038',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '19ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '390a9369-ee3b-4aca-be3e-c3da0cac397e',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000001',
          'format' => 'plain_text',
          'safe_value' => '000001',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000019',
          'format' => 'plain_text',
          'safe_value' => '000019',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '10ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '44785775-aff6-44a5-8d33-dedf6ceadbec',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000003',
          'format' => 'plain_text',
          'safe_value' => '000003',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000039',
          'format' => 'plain_text',
          'safe_value' => '000039',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '15ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '649f4238-07e4-49ea-a85c-cce24f00d6a6',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000003',
          'format' => 'plain_text',
          'safe_value' => '000003',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000044',
          'format' => 'plain_text',
          'safe_value' => '000044',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '1er arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '82ef3cc6-d158-4c56-9db7-28ca54703e73',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000003',
          'format' => 'plain_text',
          'safe_value' => '000003',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000030',
          'format' => 'plain_text',
          'safe_value' => '000030',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '7ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '85eba2d1-5333-499d-be86-130ccaec74c4',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000003',
          'format' => 'plain_text',
          'safe_value' => '000003',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000036',
          'format' => 'plain_text',
          'safe_value' => '000036',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '2ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8e164b47-7d93-4420-9e95-d4c0f61945e3',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000003',
          'format' => 'plain_text',
          'safe_value' => '000003',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000031',
          'format' => 'plain_text',
          'safe_value' => '000031',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '5ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8e4b64ab-2916-493e-b5cf-abdc78d28aaa',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000003',
          'format' => 'plain_text',
          'safe_value' => '000003',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000034',
          'format' => 'plain_text',
          'safe_value' => '000034',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '14ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '97f5de4b-16bd-43f4-a7c9-309c2ade8d6b',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000003',
          'format' => 'plain_text',
          'safe_value' => '000003',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000043',
          'format' => 'plain_text',
          'safe_value' => '000043',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '12ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9a57ab95-5d2c-42b3-9598-2cd8e0ebd4ec',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000003',
          'format' => 'plain_text',
          'safe_value' => '000003',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000041',
          'format' => 'plain_text',
          'safe_value' => '000041',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '16ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bbf7eb2e-489d-4501-b686-769e469963f2',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000003',
          'format' => 'plain_text',
          'safe_value' => '000003',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000045',
          'format' => 'plain_text',
          'safe_value' => '000045',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '8ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bd0ef84e-d117-4c40-8157-c8b3031f7d39',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000003',
          'format' => 'plain_text',
          'safe_value' => '000003',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000037',
          'format' => 'plain_text',
          'safe_value' => '000037',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '20ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c469d214-b364-4529-b5fc-5fdb89dc48a0',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000001',
          'format' => 'plain_text',
          'safe_value' => '000001',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000020',
          'format' => 'plain_text',
          'safe_value' => '000020',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '17ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd969718d-9736-49aa-ab98-5de99432c95c',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000001',
          'format' => 'plain_text',
          'safe_value' => '000001',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000017',
          'format' => 'plain_text',
          'safe_value' => '000017',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '3ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dcd2f61d-47e5-4cd5-9824-609210ca74f1',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000003',
          'format' => 'plain_text',
          'safe_value' => '000003',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000032',
          'format' => 'plain_text',
          'safe_value' => '000032',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '6ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e08ba4e6-8565-4818-8865-12441b61084c',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000003',
          'format' => 'plain_text',
          'safe_value' => '000003',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000035',
          'format' => 'plain_text',
          'safe_value' => '000035',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '18ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e3256a62-7ec9-4ce9-a03c-95663bb76c64',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000001',
          'format' => 'plain_text',
          'safe_value' => '000001',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000018',
          'format' => 'plain_text',
          'safe_value' => '000018',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '11ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ed0ac7fb-48d6-4a01-ba31-77584e7d3d23',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000003',
          'format' => 'plain_text',
          'safe_value' => '000003',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000040',
          'format' => 'plain_text',
          'safe_value' => '000040',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => '4ème arrondissement',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'efa87a52-9a13-4ce3-aae7-246249f642c9',
    'vocabulary_machine_name' => 'arrondissement',
    'field_idk' => array(
      'und' => array(
        0 => array(
          'value' => '000003',
          'format' => 'plain_text',
          'safe_value' => '000003',
        ),
      ),
    ),
    'field_idka' => array(
      'und' => array(
        0 => array(
          'value' => '000033',
          'format' => 'plain_text',
          'safe_value' => '000033',
        ),
      ),
    ),
  );
  return $terms;
}
