<?php
/**
 * @file
 * kandb_region.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function kandb_region_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Alsace',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1ed087c9-3194-4cfa-84f7-c2a6f925e473',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Midi-Pyrénées',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1f3f6a1e-95bc-4ed1-ba60-9c689d67b465',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Limousin',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '245df3db-5d0a-457a-a10d-62d32bb7a210',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Île-de-France',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2956b1cb-c11f-4f84-aa32-88b18fc8e4f8',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Franche-Comté',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2ca53758-bcdb-41c7-92f3-b8d5d60eb7d3',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Nord-Pas-de-Calais',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3cdd9af9-2602-44df-aebc-1398b96e71f0',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Languedoc-Roussillon',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3db2435d-253c-4532-95d3-18e23eb6f4a3',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Aquitaine',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4a76aae3-e079-479a-8eb7-f6487368e373',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Rhône-Alpes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4f84d10a-f5d8-421c-8d9b-be85a16d1da1',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Bourgogne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5e1f5528-99c7-4d49-9547-3c59cccfccd9',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Corse',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6da35950-78ae-4dd3-839c-1328aacc7c18',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Haute-Normandie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '723d0675-3101-4ff2-adb5-b9b6f3f97efa',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Champagne-Ardenne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7ed7b2d7-d559-42aa-b43d-e476d1768d75',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Pays de la Loire',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '80104c9b-452e-4a49-9182-6a7ec9cb4ae8',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Poitou-Charentes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9581c854-9cab-4980-a7b1-0e980d75fd1c',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Basse-Normandie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9cc83e55-f13e-43bc-b9c1-ea5b0c6b55f5',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Lorraine',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a89a4f16-708d-4f5a-9ef3-ce187a70c750',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Picardie',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b78c6caf-7b42-48b3-8b50-0cdd01c755d4',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Centre-Val de Loire',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c3cd05c0-9769-4472-bf08-53d8973a4f2f',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Bretagne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c8a5e49d-bab3-4087-8d39-5313239ab02e',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Auvergne',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd7f33d4d-e5b0-4156-bfcb-963bfec1c757',
    'vocabulary_machine_name' => 'region',
  );
  $terms[] = array(
    'name' => 'Provence-Alpes-Côte d\'Azur',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e8dbcf90-ee7c-462e-853a-36c209a2f82d',
    'vocabulary_machine_name' => 'region',
  );
  return $terms;
}
