<?php

define('TAGCOMMANDER_XTCLICK_S2_HOMEPAGE', 1);
define('TAGCOMMANDER_CHAPITRE_NOS_CONSEILS', 'nos_conseils');
define('TAGCOMMANDER_SOUS_CHAPITRE_PLAYER_VIDEO', 'player_video');
define('TAGCOMMANDER_SOUS_CHAPITRE_DOSSIERS', 'dossiers');
define('TAGCOMMANDER_CHAPITRE_CARROUSEL_MEILLEURS_OFFRES', 'carrousel_meilleurs_offres');
define('TAGCOMMANDER_CHAPITRE_CARROUSEL_NOS_REFERENCES', 'carrousel_nos_references');

define('TAGCOMMANDER_XTCLICK_S2_NOS_OFFRES', 2);
define('TAGCOMMANDER_CHAPITRE_AJOUT_SELECTIONS', 'ajout_selections');
define('TAGCOMMANDER_SOUS_CHAPITRE_FICHES_PROGRAMMES', 'fiches_programmes');
define('TAGCOMMANDER_SOUS_CHAPITRE_FICHES_BIENS', 'fiches_biens');
define('TAGCOMMANDER_CHAPITRE_AJOUT_SELECTIONS', 'impression');
define('TAGCOMMANDER_CHAPITRE_AJOUT_SELECTIONS', 'envoi_par_email');
define('TAGCOMMANDER_CHAPITRE_AJOUT_SELECTIONS', 'partage_facebook');
define('TAGCOMMANDER_CHAPITRE_AJOUT_SELECTIONS', 'partage_twitter');
define('TAGCOMMANDER_CHAPITRE_AJOUT_SELECTIONS', 'pages_programmes');
define('TAGCOMMANDER_SOUS_CHAPITRE_ANCRES', 'ancres');
define('TAGCOMMANDER_SOUS_CHAPITRE_PRESTATIONS', 'prestations');

define('TAGCOMMANDER_XTCLICK_S2_CORPORATE', 5);
define('TAGCOMMANDER_CHAPITRE_FINANCE', 'finance');
define('TAGCOMMANDER_CHAPITRE_ACTIVITES', 'activites');
define('TAGCOMMANDER_CHAPITRE_RESSOURCES_HUMAINES', 'ressources_humaines');
define('TAGCOMMANDER_CHAPITRE_ACTUALITES', 'actualites');

define('TAGCOMMANDER_XTCLICK_S2_MOTEUR_INTEME', 8);
define('TAGCOMMANDER_XTCLICK_S2_CLICS_TRANSVERSAUX', 11);


/**
 * hook_preprocess_views_view
 * @param type $vars
 */
function kandb_admin_content_preprocess_views_view(&$vars){
  if(isset($vars['view']->name) && $vars['view']->name == 'admin_views_node'){
    drupal_add_js(drupal_get_path('module', 'kandb_admin_content') . '/js/custom_view_admin_content.js');
  }
}
/**
 * Implementation of hook_form_alter()
 */
function kandb_admin_content_form_alter(&$form, &$form_state, $form_id){
    if ($form_id == 'bien_node_form') {
        $form['field_bien_low_tva_price']['#disabled'] = TRUE;
    } elseif ($form_id == 'programme_node_form') {
        $form['field_program_low_tva_price_min']['#disabled'] = TRUE;
        $form['field_program_low_tva_price_max']['#disabled'] = TRUE;
    }
}

/**
 * Translate month to France
 * @param string $monthString Description
 */
function translatorMonth($monthString, $language_code = 'fr') {
  $language = array(
    'en' => array('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'),
    'fr' => array('Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'));
  if (isset($language[$language_code])) {
    return str_replace($language['en'], $language[$language_code], $monthString);
  }
  return $monthString;
}
