<?php

/**
 * hook_preprocess_views_view
 * @param type $vars
 */
function kandb_admin_content_preprocess_views_view(&$vars){
  if(isset($vars['view']->name) && $vars['view']->name == 'admin_views_node'){
    drupal_add_js(drupal_get_path('module', 'kandb_admin_content') . '/js/custom_view_admin_content.js');
  }
}
/**
 * Implementation of hook_form_alter()
 */
function kandb_admin_content_form_alter(&$form, &$form_state, $form_id){
    if ($form_id == 'bien_node_form') {
        $form['field_bien_low_tva_price']['#disabled'] = TRUE;
    } elseif ($form_id == 'programme_node_form') {
        $form['field_program_low_tva_price_min']['#disabled'] = TRUE;
        $form['field_program_low_tva_price_max']['#disabled'] = TRUE;
    }
}

/**
 * Translate month to France
 * @param string $monthString Description
 */
function translatorMonth($monthString, $language_code = 'fr') {
  $language = array(
    'en' => array('Jan', 'Febr', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'),
    'fr' => array('Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'));
  if (isset($language[$language_code])) {
    return str_replace($language['en'], $language[$language_code], $monthString);
  }
  return $monthString;
}
