<?php

/**
 * Implements hook_menu().
 */
function kb_import_menu() {
  $items = array();

  $items['delete-nodes'] = array(
    'title' => 'Import',
    'page callback' => 'action_delete_nodes',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );

  return $items;
}

function action_delete_nodes() {
  $KBAPI = new KAndBAPI();
  $results = $KBAPI->getListNodeByBundle('node', 'programme');

  foreach ($results as $id => $value) {
    $nids[] = $id;
  }

  if (!empty($nids)) {
    node_delete_multiple($nids);
    drupal_set_message(t('Deleted %count nodes.', array('%count' => count($nids))));
  }
}

/**
 * Implements hook_cronapi
 * @param type $op
 * @param type $job
 * @return string
 */
function kb_import_cronapi($op, $job = NULL) {
  $items['fetch_programme_import_cron'] = array(
    'description' => 'Fetch Programme Import',
    'rule' => '*/5 * * * *',
    'callback' => 'kb_import_fetch_programme_import_cron' ,
    'arguments' => array(array('programme_import'))
  );

  return $items;
}

function kb_import_fetch_programme_import_cron($feednames){
  if (function_exists('feeds_source')){
    foreach($feednames as $feedname){
      $source = feeds_source($feedname);
      $source->import();
    }
  }
}